# 1. Persiapan dan Pemeriksaan Data Venue

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files

In [ ]:
uploaded = files.upload()
file_name = next(iter(uploaded))
print(f"File: {file_name}")

Saving dataset_dashboard_fasilitas_olahraga_surabaya.csv to dataset_dashboard_fasilitas_olahraga_surabaya (1).csv
File: dataset_dashboard_fasilitas_olahraga_surabaya (1).csv

In [ ]:
df = pd.read_csv(file_name, sep=',', encoding='utf-8-sig')

In [ ]:
print(f"\nUkuran dataset: {df.shape[0]:,} baris × {df.shape[1]} kolom")

print("\nNama kolom:")
print(df.columns.tolist())

print("\n5 data pertama:")
display(df.head())

Ukuran dataset: 1,116 baris × 16 kolom

Nama kolom:
['data_bulan', 'data_tahun', 'periode', 'kecamatan', 'kelurahan', 'nama_fasilitas_olahraga', 'jenis_olahraga', 'alamatlokasi', 'luas', 'dilakukan_penambahan_pembanguna', 'difasilitasi_dan_dipelihara', 'tanggal_pemeliharaan_dan_perbai', 'deskripsi_pemeliharaan', 'tahun_dilakukan_pemeliharaan', 'deskripsi_pemanfaatan', 'tahun_dilakukan_pemanfaatan']

5 data pertama:

,data_bulan,data_tahun,periode,kecamatan,kelurahan,nama_fasilitas_olahraga,jenis_olahraga,alamatlokasi,luas,dilakukan_penambahan_pembanguna,difasilitasi_dan_dipelihara,tanggal_pemeliharaan_dan_perbai,deskripsi_pemeliharaan,tahun_dilakukan_pemeliharaan,deskripsi_pemanfaatan,tahun_dilakukan_pemanfaatan
0,9.0,2023.0,2023-09,Kec. Benowo,Kel. Kandangan,Lapangan Basket Jl. Bandarejo Tahap II,Bola Basket,Jl. Bandarejo Tahap II,686.0,Tidak,Ya,1.0,NaN,NaN,NaN,NaN
1,9.0,2023.0,2023-09,Kec. Benowo,Kel. Romokalisari,Lapangan Futsal Jl. Dukuh Gendong,Futsal,Jl. Dukuh Gendong,1260.0,Tidak,Ya,1.0,NaN,NaN,NaN,NaN
2,9.0,2023.0,2023-09,Kec. Benowo,Kel. Sememi,Lapangan Futsal Bandarejo,Futsal,Bandarejo,504.0,Tidak,Ya,1.0,NaN,NaN,NaN,NaN
3,9.0,2023.0,2023-09,Kec. Benowo,Kel. Sememi,Lapangan Futsal Jl. Sememi Jaya,Futsal,Jl. Sememi Jaya,504.0,Tidak,Ya,1.0,NaN,NaN,NaN,NaN
4,9.0,2023.0,2023-09,Kec. Benowo,Tengger,Lapangan Futsal Jl. Raya Tengger,Futsal,Jl. Raya Tengger,504.0,Tidak,Ya,1.0,NaN,NaN,NaN,NaN

In [ ]:
print("=== INFO DATASET ===")
df.info()

print("\n=== MISSING VALUE ===")

missing = pd.DataFrame({
    'Jumlah Missing': df.isna().sum(),
    'Persentase (%)': (df.isna().mean() * 100).round(2)
})

display(missing)

print("\n=== DUPLIKASI ===")
print("Jumlah baris duplikat:", df.duplicated().sum())

print("\n=== JUMLAH UNIK ===")
print("Kecamatan :", df['kecamatan'].nunique())
print("Kelurahan :", df['kelurahan'].nunique())
print("Fasilitas :", df['nama_fasilitas_olahraga'].nunique())
print("Jenis olahraga :", df['jenis_olahraga'].nunique())

=== INFO DATASET ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1116 entries, 0 to 1115
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   data_bulan                       1116 non-null   float64
 1   data_tahun                       1116 non-null   float64
 2   periode                          1116 non-null   object
 3   kecamatan                        1116 non-null   object
 4   kelurahan                        1116 non-null   object
 5   nama_fasilitas_olahraga          1116 non-null   object
 6   jenis_olahraga                   1116 non-null   object
 7   alamatlokasi                     1116 non-null   object
 8   luas                             1094 non-null   float64
 9   dilakukan_penambahan_pembanguna  621 non-null    object
 10  difasilitasi_dan_dipelihara      918 non-null    object
 11  tanggal_pemeliharaan_dan_perbai  918 non-null    float64
 12  deskripsi_pemeliharaan           198 non-null    object
 13  tahun_dilakukan_pemeliharaan     198 non-null    float64
 14  deskripsi_pemanfaatan            198 non-null    object
 15  tahun_dilakukan_pemanfaatan      198 non-null    float64
dtypes: float64(6), object(10)
memory usage: 139.6+ KB

=== MISSING VALUE ===

                                 Jumlah Missing  Persentase (%)
data_bulan                                    0            0.00
data_tahun                                    0            0.00
periode                                       0            0.00
kecamatan                                     0            0.00
kelurahan                                     0            0.00
nama_fasilitas_olahraga                       0            0.00
jenis_olahraga                                0            0.00
alamatlokasi                                  0            0.00
luas                                         22            1.97
dilakukan_penambahan_pembanguna             495           44.35
difasilitasi_dan_dipelihara                 198           17.74
tanggal_pemeliharaan_dan_perbai             198           17.74
deskripsi_pemeliharaan                      918           82.26
tahun_dilakukan_pemeliharaan                918           82.26
deskripsi_pemanfaatan                       918           82.26
tahun_dilakukan_pemanfaatan                 918           82.26

=== DUPLIKASI ===
Jumlah baris duplikat: 0

=== JUMLAH UNIK ===
Kecamatan : 31
Kelurahan : 121
Fasilitas : 661
Jenis olahraga : 16

In [ ]:
print("=== DATA PER TAHUN ===")

display(
    df['data_tahun']
    .value_counts()
    .sort_index()
    .rename_axis('Tahun')
    .reset_index(name='Jumlah Data')
)

=== DATA PER TAHUN ===

    Tahun  Jumlah Data
0  2023.0          145
1  2024.0          380
2  2025.0          393
3  2026.0          198

In [ ]:
print("\n=== JENIS OLAHRAGA ===")

display(
    df['jenis_olahraga']
    .value_counts()
    .rename_axis('Jenis Olahraga')
    .reset_index(name='Jumlah Data')
)

=== JENIS OLAHRAGA ===

             Jenis Olahraga  Jumlah Data
0                    Futsal          563
1               Bola Volley          175
2                Sepak Bola          151
3               Bola Basket           99
4               Bulutangkis           37
5                     Tenis           25
6          Gedung Serbaguna           12
7                    Hockey            9
8                  Menembak            8
9                  Softball            8
10                   Renang            7
11                  Atletik            7
12  Balap Motor & Drag Race            6
13            Basket 3 on 3            6
14            Jogging Track            2
15                     Judo            1

In [ ]:
print("\n=== KECAMATAN ===")

display(
    df['kecamatan']
    .value_counts()
    .rename_axis('Kecamatan')
    .reset_index(name='Jumlah Data')
)

=== KECAMATAN ===

                Kecamatan  Jumlah Data
0              Kec. Pakal          129
1             Kec. Benowo          112
2            Kec. Rungkut           92
3          Kec. Jambangan           68
4             Kec. Tandes           64
5         Kec. Sambikerep           63
6             Kec. Gubeng           63
7        Kec. Lakarsantri           55
8         Kec. Krembangan           51
9          Kec. Wonokromo           49
10            Kec. Wiyung           40
11             Kec. Bulak           30
12          Kec. Wonocolo           28
13     Kec. Sukomanunggal           28
14        Kec. Tambaksari           28
15          Kec. Sukolilo           27
16         Kec. Mulyorejo           25
17      Kec. Karangpilang           24
18          Kec. Kenjeran           21
19           Kec. Sawahan           19
20           Kec. Genteng           16
21  Kec. Tenggilis Mejoyo           15
22          Kec. Gayungan           14
23         Kec. Tegalsari           11
24          Kec. Asemrowo           10
25    Kec. Pabean Cantian            9
26       Kec. Dukuh Pakis            6
27           Kec. Bubutan            5
28          Kec. Semampir            5
29      Kec. Gunung Anyar            5
30         Kec. Simokerto            4

In [ ]:
df_2023_2025 = df[
    df['data_tahun'].between(2023, 2025)
].copy()

print(
    "Jumlah data 2023–2025:",
    len(df_2023_2025)
)

print(
    "Jumlah fasilitas unik 2023–2025:",
    df_2023_2025['nama_fasilitas_olahraga'].nunique()
)

Jumlah data 2023–2025: 918
Jumlah fasilitas unik 2023–2025: 610

In [ ]:
fasilitas_unik = (
    df_2023_2025[
        [
            'nama_fasilitas_olahraga',
            'jenis_olahraga',
            'kecamatan',
            'kelurahan',
            'alamatlokasi',
            'luas'
        ]
    ]
    .drop_duplicates(subset=['nama_fasilitas_olahraga'])
    .sort_values('nama_fasilitas_olahraga')
    .reset_index(drop=True)
)

print("Jumlah fasilitas unik:", len(fasilitas_unik))

display(fasilitas_unik)

Jumlah fasilitas unik: 610

,nama_fasilitas_olahraga,jenis_olahraga,kecamatan,kelurahan,alamatlokasi,luas
0,Basket 3 on 3 Viaduk Gubeng,Basket 3 on 3,Kec. Gubeng,Kel. Gubeng,Jl. Nias,200.000
1,Futsal Wonorejo Manukan,Futsal,Kec. Tandes,Kel. Manukan Kulon,Wonorejo Manukan,504.000
2,Gedung Koni Kodya Surabaya,Gedung Serbaguna,Kec. Tambaksari,Kel. Ploso,Jl. Bogen 1,11000.000
3,Gelanggang Remaja,Gedung Serbaguna,Kec. Tambaksari,Kel. Ploso,"Jl. Bogen I No.53-Q, Ploso, Tambaksari",4200.000
4,"Gelanggang Remaja Jl. Bogen I No.53-Q, Ploso, Tambaksari",Gedung Serbaguna,Kec. Tambaksari,Kel. Ploso,"Jl. Bogen I No.53-Q, Ploso, Tambaksari",4200.000
...,...,...,...,...,...,...
605,SIRKUIT BALAP MOTOR & DRAG RACE,Balap Motor & Drag Race,Kec. Pakal,Kel. Pakal,GELORA BUNG TOMO SURABAYA,9000.000
606,Sirkuit Balap Motor & Drag Race,Balap Motor & Drag Race,Kec. Pakal,Kel. Benowo,Gelora Bung Tomo,9000.000
607,Stadion Gelora 10 Nopember,Sepak Bola,Kec. Tambaksari,Kel. Tambaksari,Jl. Tambaksari Surabaya,49400.000
608,Stadion Gelora Bung Tomo,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1,60000.000
609,Stadion Indoor Gelora Bung Tomo,Futsal,Kec. Pakal,Kel. Pakal,GELORA BUNG TOMO SURABAYA,31.826

In [ ]:
kata_kunci = (
    'stadion|stadium|gor|gelora|gelanggang|'
    'lapangan|arena|gedung|kolam|hockey|'
    'tenis|tennis|thor'
)

kandidat_venue = fasilitas_unik[
    fasilitas_unik['nama_fasilitas_olahraga']
    .str.contains(
        kata_kunci,
        case=False,
        na=False,
        regex=True
    )
].copy()

print("Jumlah kandidat venue:", len(kandidat_venue))

display(kandidat_venue)

Jumlah kandidat venue: 594

,nama_fasilitas_olahraga,jenis_olahraga,kecamatan,kelurahan,alamatlokasi,luas
2,Gedung Koni Kodya Surabaya,Gedung Serbaguna,Kec. Tambaksari,Kel. Ploso,Jl. Bogen 1,11000.000
3,Gelanggang Remaja,Gedung Serbaguna,Kec. Tambaksari,Kel. Ploso,"Jl. Bogen I No.53-Q, Ploso, Tambaksari",4200.000
4,"Gelanggang Remaja Jl. Bogen I No.53-Q, Ploso, Tambaksari",Gedung Serbaguna,Kec. Tambaksari,Kel. Ploso,"Jl. Bogen I No.53-Q, Ploso, Tambaksari",4200.000
5,Gelora 10 Nopember,Sepak Bola,Kec. Tambaksari,Kel. Ploso,Jl. Tambaksari Surabaya,49400.000
6,Gelora Bung Tomo,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1,60000.000
...,...,...,...,...,...,...
593,Lintasan Atletik Lapangan Thor,Atletik,Kec. Wonokromo,Kel. Darmo,Jl. Padmosusastro Surabaya,4000.000
599,Rehabilitasi Ringan Bangunan Tidak Bertingkat (30%) (LAPANGAN FUTSAL WONOCOLO),Futsal,Kec. Wonocolo,Kel. Wonocolo,LAPANGAN FUTSAL WONOCOLO,400.000
607,Stadion Gelora 10 Nopember,Sepak Bola,Kec. Tambaksari,Kel. Tambaksari,Jl. Tambaksari Surabaya,49400.000
608,Stadion Gelora Bung Tomo,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1,60000.000
609,Stadion Indoor Gelora Bung Tomo,Futsal,Kec. Pakal,Kel. Pakal,GELORA BUNG TOMO SURABAYA,31.826

In [ ]:
# NORMALISASI NAMA FASILITAS
import re

fasilitas_unik['nama_bersih'] = (
    fasilitas_unik['nama_fasilitas_olahraga']
    .str.lower()
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
)

# CARI VENUE BERDASARKAN NAMA FASILITAS SAJA
kata_kunci_venue = (
    r'\b(stadion|stadium|gor|gelora|gelanggang|'
    r'arena|gedung|kolam|hockey|tenis|tennis|'
    r'convention hall)\b'
)

kandidat_venue = fasilitas_unik[
    fasilitas_unik['nama_bersih'].str.contains(
        kata_kunci_venue,
        case=False,
        na=False,
        regex=True
    )
].copy()

print("Jumlah kandidat venue:", len(kandidat_venue))

display(
    kandidat_venue[
        [
            'nama_fasilitas_olahraga',
            'jenis_olahraga',
            'kecamatan',
            'kelurahan',
            'alamatlokasi',
            'luas'
        ]
    ]
)

Jumlah kandidat venue: 33

/tmp/ipykernel_3409/2482348833.py:19: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  fasilitas_unik['nama_bersih'].str.contains(

,nama_fasilitas_olahraga,jenis_olahraga,kecamatan,kelurahan,alamatlokasi,luas
2,Gedung Koni Kodya Surabaya,Gedung Serbaguna,Kec. Tambaksari,Kel. Ploso,Jl. Bogen 1,11000.000
3,Gelanggang Remaja,Gedung Serbaguna,Kec. Tambaksari,Kel. Ploso,"Jl. Bogen I No.53-Q, Ploso, Tambaksari",4200.000
4,"Gelanggang Remaja Jl. Bogen I No.53-Q, Ploso, Tambaksari",Gedung Serbaguna,Kec. Tambaksari,Kel. Ploso,"Jl. Bogen I No.53-Q, Ploso, Tambaksari",4200.000
5,Gelora 10 Nopember,Sepak Bola,Kec. Tambaksari,Kel. Ploso,Jl. Tambaksari Surabaya,49400.000
6,Gelora Bung Tomo,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1,60000.000
7,Gelora Pancasila,Bola Basket,Kec. Wonokromo,Kel. Darmo,Jl. Indragiri No. 6,4432.000
10,Kolam Renang,Renang,Kec. Jambangan,Kel. Karah,Jl. Ketintang madya VII,12280.000
11,Kolam Renang Jambangan,Renang,Kec. Jambangan,Kel. Karah,Jl. Ketintang madya VII,12280.000
484,Lapangan Hockey,Hockey,Kec. Gubeng,Kel. Airlangga,Jl. Dharmawangsa sd. Tahap V (2012-2016),6000.000
485,Lapangan Hockey Dharmawangsa,Hockey,Kec. Gubeng,Kel. Airlangga,Jl. Dharmawangsa 2,6000.000
488,Lapangan Latihan B Gelora Bung Tomo,Sepak Bola,Kec. Pakal,Kel. Benowo,GELORA BUNG TOMO B,6090.000
490,Lapangan Latihan Sepak Bola Stadion A,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1 A,8925.000
491,Lapangan Latihan Sepak Bola Stadion B,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1 B,8925.000
492,Lapangan Latihan Sepak Bola Stadion C,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1 C,8925.000
493,Lapangan Olahraga Tenis Dharmawangsa,Tenis,Kec. Gubeng,Kel. Airlangga,Jl. Dharmawangsa 3,1106.000
494,Lapangan Olahraga Tennis Dharmawangsa,Tenis,Kec. Gubeng,Kel. Airlangga,Jl. Dharmawangsa No.4,1106.000
554,Lapangan Tenis Babatan Pratama,Tenis,Kec. Wiyung,Kel. Wiyung,JL. Perumahan Babatan Pratama Wiyung,420.000
555,Lapangan Tenis Babatan Pratama Wiyung,Tenis,Kec. Wiyung,Kel. Wiyung,JL. Perumahan Babatan Pratama Wiyung,420.000
556,Lapangan Tenis Dharmawangsa,Tenis,Kec. Gubeng,Kel. Airlangga,Jl. Dharmawangsa Tenis,1200.000
557,Lapangan Tenis Greges Timur,Tenis,Kec. Asemrowo,Kel. Genting Kalianak,Jl. Greges Timur,630.000
558,Lapangan Tenis Griya Kencana Asri,Tenis,Kec. Rungkut,Kel. Wonorejo (Rungkut),Perum Griya Kencana Asri,420.000
559,Lapangan Tenis JL. SIMOREJO TIMUR NO. 4 RT. 4,Tenis,Kec. Sukomanunggal,Kel. Sukomanunggal,JL. SIMOREJO TIMUR NO. 4 RT. 4,420.000
560,Lapangan Tenis JL. WISMA TENGGER,Tenis,Kec. Benowo,Kel. Kandangan,JL. WISMA TENGGER,630.000
561,Lapangan Tenis Jl. Nginden VI,Tenis,Kec. Sukolilo,Kel. Nginden Jangkungan,Jl. Nginden VI,630.000
562,Lapangan Tenis Ketintang Permai,Tenis,Kec. Jambangan,Kel. Karah,Jl. Ketintang Selatan,630.000
563,Lapangan Tenis PURI KENCANA JAMBANGAN,Tenis,Kec. Jambangan,Kel. Jambangan,PURI KENCANA JAMBANGAN,638.480
564,Lapangan Tenis Pondok Maritim RW 6,Tenis,Kec. Wiyung,Kel. Balas Klumprik,JL. Pondok Maritim RW 6,420.000
565,Lapangan Tennis Ketintang Selatan III,Tenis,Kec. Jambangan,Kel. Karah,Jl. Ketintang Selatan III,500.000
566,Lapangan Tennis Puri Kencana Jambangan,Tenis,Kec. Jambangan,Kel. Jambangan,Puri Kencana Jambangan,63848.000
567,Lapangan Tennis Sambiroto,Tenis,Kec. Sambikerep,Kel. Sambikerep,Lapangan Tennis Sambiroto,504.000
607,Stadion Gelora 10 Nopember,Sepak Bola,Kec. Tambaksari,Kel. Tambaksari,Jl. Tambaksari Surabaya,49400.000
608,Stadion Gelora Bung Tomo,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1,60000.000
609,Stadion Indoor Gelora Bung Tomo,Futsal,Kec. Pakal,Kel. Pakal,GELORA BUNG TOMO SURABAYA,31.826

In [ ]:
# CARI LAPANGAN SECARA TERPISAH
kandidat_lapangan = fasilitas_unik[
    fasilitas_unik['nama_bersih'].str.contains(
        r'\blapangan\b',
        case=False,
        na=False,
        regex=True
    )
].copy()

print("Jumlah fasilitas dengan nama mengandung 'lapangan':",
      len(kandidat_lapangan))

display(
    kandidat_lapangan[
        [
            'nama_fasilitas_olahraga',
            'jenis_olahraga',
            'kecamatan',
            'kelurahan',
            'alamatlokasi',
            'luas'
        ]
    ].head(100)
)

Jumlah fasilitas dengan nama mengandung 'lapangan': 583

,nama_fasilitas_olahraga,jenis_olahraga,kecamatan,kelurahan,alamatlokasi,luas
12,Lapangan 3 on 3 Ngagel,Basket 3 on 3,Kec. Wonokromo,Kel. Ngagel,Taman Asreboyo,200.00
13,Lapangan 3 on 3 Taman ekspresi,Basket 3 on 3,Kec. Genteng,Kel. genteng,Taman ekspresi,200.00
14,Lapangan Basket Puri Kencana Karah Jambangan,Bola Basket,Kec. Jambangan,Kel. Karah,PURI KENCANA KARAH JAMBANGAN,420.00
15,Lapangan Basket 3 on 3 Viaduct,Basket 3 on 3,Kec. Gubeng,Kel. Gubeng,Jl. Nias No. 110,96.00
16,Lapangan Basket Baratajaya,Bola Basket,Kec. Gubeng,Kel. Baratajaya,Jl. Baratajaya 1,504.00
17,Lapangan Basket Dukuh Lempung,Bola Basket,Kec. Sambikerep,Kel. Lontar,Dukuh Lempung,NaN
18,Lapangan Basket Jemursari V,Bola Basket,Kec. Wonocolo,Kel. Jemur Wonosari,Jl. Jemursari V,308.00
19,Lapangan Basket Jl. Bandarejo Tahap II,Bola Basket,Kec. Benowo,Kel. Kandangan,Jl. Bandarejo Tahap II,686.00
20,Lapangan Basket Jl. Ikan Dorang Baru RT 10,Bola Basket,Kec. Krembangan,Kel. Perak Barat,JL. Ikan Dorang Baru RT 10,NaN
21,Lapangan Basket Jl. Luntas RT 3 RW 8,Bola Basket,Kec. Tambaksari,Kel. Pacarkeling,JL. LUNTAS RT. 3 RW 8 KEL. PACAR KELING,237.50
22,Lapangan Basket Jl. Manukan Rejo Blok I Gg Masjid RT 008 RW 006,Bola Basket,Kec. Tandes,Kel. Manukan Kulon,Jl. Manukan Rejo Blok I Gg Masjid RT 008 RW 006,686.00
23,Lapangan Basket Jl. Mulyorejo No. 21 BLK RW 01 RT 06,Bola Basket,Kec. Mulyorejo,Kel. Mulyorejo,Jl. Mulyorejo No. 21 BLK RW 01 RT 06,471.80
24,Lapangan Basket Jl. Sidosermo,Bola Basket,Kec. Wonokromo,Kel. Bendul Merisi,Lapangan Basket Jl. Sidosermo,686.00
25,Lapangan Basket Kawasan Kelurahan Bendul Merisi,Bola Basket,Kec. Wonocolo,Kel. Bendul Merisi,Lapangan Basket Kawasan Kelurahan Bendul Merisi,NaN
26,Lapangan Basket Klakahrejo Gang Sekolahan,Bola Basket,Kec. Pakal,Kel. Kandangan,Lapangan Sepak Bola Klakahrejo Gang Sekolahan RT 001 RW 002,686.00
27,Lapangan Basket Kombes Pol M Duryat,Bola Basket,Kec. Tegalsari,Kel. Tegalsari,JL. KOMBES POL M DURYAT,686.00
28,Lapangan Basket Kota Lama,Bola Basket,Kec. Krembangan,Kel. Krembangan Selatan,Taman Rajawali,504.00
29,Lapangan Basket Medayu Pesona III,Bola Basket,Kec. Rungkut,Kel. Medokan Ayu,Jl. Medokan Ayu Pesona III,375.00
30,Lapangan Basket Medokan Asri Barat RT 4 Rw 5,Bola Basket,Kec. Rungkut,Kel. Medokan Ayu,JL. Medokan Asri Barat RT. 4 RW 5,504.00
31,Lapangan Basket Medokan Asri Utara,Bola Basket,Kec. Rungkut,Kel. Medokan Ayu,JL. MEDOKAN ASRI UTARA,459.00
32,Lapangan Basket Mulyorejo,Bola Basket,Kec. Mulyorejo,Kel. Mulyorejo,Jl. Mulyorejo Utara,472.00
33,Lapangan Basket Pondok Benowo Indah,Bola Basket,Kec. Pakal,Kel. Babat Jerawat,Pondok Benowo Indah,504.00
34,Lapangan Basket Pucang Jajar No. 14A,Bola Basket,Kec. Gubeng,Kel. Kertajaya,Jl. Pucang Jajar No.14A,242.00
35,Lapangan Basket Puri Kencana Karah,Bola Basket,Kec. Jambangan,Kel. Karah,PURI KENCANA KARAH JAMBANGAN,NaN
36,Lapangan Basket Raya Klumprik Utara RW XII,Bola Basket,Kec. Wiyung,Kel. Balas Klumprik,Raya Klumprik Utara RW XII,686.00
37,Lapangan Basket Semampir Tengah RT 11 RW 7,Bola Basket,Kec. Simokerto,Kel. Kapasan,Jl. Semampir Tengah RT 11 RW 7,686.00
38,Lapangan Basket Softball Dharmawangsa,Bola Basket,Kec. Gubeng,Kel. Airlangga,Lapangan Softball Dharmawangsa,504.00
39,Lapangan Basket TAMAN CAHAYA JL. RAYA PAKAL,Bola Basket,Kec. Pakal,Kel. Pakal,TAMAN CAHAYA JL. RAYA PAKAL,686.00
40,Lapangan Basket Taman Cahaya,Bola Basket,Kec. Pakal,Kel. Pakal,Taman Cahaya Pakal,686.00
41,Lapangan Basket Taman Ekspresi,Bola Basket,Kec. Genteng,Kel. Genteng,Taman Ekspresi,504.00
42,Lapangan Basket Taman Sejarah,Bola Basket,Kec. Krembangan,Kel. Krembangan Selatan,Taman Sejarah,504.00
43,Lapangan Bola Basket Baratajaya,Bola Basket,Kec. Gubeng,Kel. Baratajaya,Jl. Baratajaya 1,504.00
44,Lapangan Bola Basket Baratajaya II RT 6,Bola Basket,Kec. Gubeng,Kel. Baratajaya,BARATA JAYA II NO. RT. 6,364.00
45,Lapangan Bola Basket Dukuh Lempung,Bola Basket,Kec. Sambikerep,Kel. Lontar,Dukuh Lempung,686.00
46,Lapangan Bola Basket Dupak Bangunsari,Bola Basket,Kec. Krembangan,Kel. Dupak,DUPAK BANGUNSARI,289.00
47,Lapangan Bola Basket Fasum Rusun Jambangan,Bola Basket,Kec. Jambangan,Kel. Jambangan,L Fasum Rusun Jambangan,686.00
48,Lapangan Bola Basket Ikan Dorang Baru,Bola Basket,Kec. Krembangan,Kel. Perak Barat,JL. Ikan Dorang Baru RT 10,686.00
49,Lapangan Bola Basket JL. Ikan Dorang Baru RT 10,Bola Basket,Kec. Krembangan,Kel. Perak Barat,JL. Ikan Dorang Baru RT 10,686.00
50,Lapangan Bola Basket JL. KOMBES POL M DURYAT,Bola Basket,Kec. Tegalsari,Kel. Tegalsari,JL. KOMBES POL M DURYAT,686.00
51,Lapangan Bola Basket JL. Ngagel Mulyo GG. 16 RT 13,Bola Basket,Kec. Wonokromo,Kel. Ngagelrejo,JL. Ngagel Mulyo GG. 16 RT 13,686.00
52,Lapangan Bola Basket JL. Pagesangan Timur RT 6,Bola Basket,Kec. Jambangan,Kel. Pagesangan,JL. Pagesangan Timur RT 6,686.00
53,Lapangan Bola Basket JL. Rusun Romokalisari,Bola Basket,Kec. Benowo,Kel. Romokalisari,JL. Rusun Romokalisari,686.00
54,Lapangan Bola Basket JL. Simohilir RW 4,Bola Basket,Kec. Sukomanunggal,Kel. Sukomanunggal,JL. Simohilir RW 4,686.00
55,Lapangan Bola Basket JL. WIJAYA KUSUMA 50,Bola Basket,Kec. Genteng,Kel. Ketabang,JL. WIJAYA KUSUMA 50,504.00
56,Lapangan Bola Basket Jl. Bandarejo Tahap II,Bola Basket,Kec. Benowo,Kel. Kandangan,Jl. Bandarejo Tahap II,686.00
57,Lapangan Bola Basket Jl. Baratajaya,Bola Basket,Kec. Gubeng,Kel. Baratajaya,Jl. Baratajaya,504.00
58,Lapangan Bola Basket Jl. Bibis Karah Sawah No. 9,Bola Basket,Kec. Jambangan,Kel. Karah,Jl. Bibis Karah Sawah No.9,686.00
59,Lapangan Bola Basket Jl. Bibis Karah Sawah No.9,Bola Basket,Kec. Jambangan,Kel. Karah,Jl. Bibis Karah Sawah No.9,686.00
60,Lapangan Bola Basket Jl. Jemursari Utara,Bola Basket,Kec. Wonocolo,Kel. Jemur Wonosari,Jl. Jemursari Utara,308.00
61,Lapangan Bola Basket Jl. Kedung Cowek 390,Bola Basket,Kec. Kenjeran,Kel. Tanah Kali Kedinding,Jl. Kedung Cowek 390,696.00
62,Lapangan Bola Basket Jl. Lesti,Bola Basket,Kec. Wonokromo,Kel. Darmo,Jl. Lesti Gang 00 No. 00 RT. 08 RW. 07,686.00
63,Lapangan Bola Basket Jl. Raya Sambikerep,Bola Basket,Kec. Sambikerep,Kel. Sambikerep,Jl. Raya Sambikerep No.41,459.00
64,Lapangan Bola Basket Jl. Sawah Pulo,Bola Basket,Kec. Semampir,Kel. Ujung,Jl. Sawah Pulo,686.00
65,Lapangan Bola Basket Jl. Semampir Tengah RT 11 RW 7,Bola Basket,Kec. Simokerto,Kel. Kapasan,Jl. Semampir Tengah RT 11 RW 7,686.00
66,Lapangan Bola Basket Kalijudan Indah III Rt 1,Bola Basket,Kec. Mulyorejo,Kel. Kalijudan,KALIJUDAN INDAH III RT. 1,453.75
67,Lapangan Bola Basket Kebraon RT 2 RW 1 Samping Makam,Bola Basket,Kec. Karangpilang,Kel. Kebraon,Kebraon RT 2 RW.1 Samping Makam,686.00
68,Lapangan Bola Basket Klakahrejo Gang Sekolahan,Bola Basket,Kec. Benowo,Kel. Sememi,Klakahrejo Gang Sekolahan RT 001 RW 002,686.00
69,Lapangan Bola Basket Klakahrejo Gang Sekolahan RT 001 RW 002,Bola Basket,Kec. Benowo,Kel. Sememi,Klakahrejo Gang Sekolahan RT 001 RW 002,686.00
70,Lapangan Bola Basket Lapangan Basket Kawasan Kelurahan Bendul Merisi,Bola Basket,Kec. Wonocolo,Kel. Bendul Merisi,Lapangan Basket Kawasan Kelurahan Bendul Merisi,686.00
71,Lapangan Bola Basket Lapangan Sepak Bola Klakahrejo Gang Sekolahan RT 001 RW 002,Bola Basket,Kec. Benowo,Kel. Sememi,Lapangan Sepak Bola Klakahrejo Gang Sekolahan RT 001 RW 002,686.00
72,Lapangan Bola Basket Medokan Asri Utara,Bola Basket,Kec. Rungkut,Kel. Medokan Ayu,JL. MEDOKAN ASRI UTARA,459.00
73,Lapangan Bola Basket Ngagel Mulyo Gg 16,Bola Basket,Kec. Wonokromo,Kel. Ngagel Rejo,JL. Ngagel Mulyo GG. 16 RT 13,686.00
74,Lapangan Bola Basket PURI KENCANA KARAH JAMBANGAN,Bola Basket,Kec. Jambangan,Kel. Jambangan,PURI KENCANA KARAH JAMBANGAN,420.00
75,Lapangan Bola Basket Pagesangan Timur RT 6,Bola Basket,Kec. Jambangan,Kel. Pagesangan,JL. Pagesangan Timur RT 6,686.00
76,Lapangan Bola Basket Peruma Nirwana Exclusive,Bola Basket,Kec. Rungkut,Kel. Wonorejo (Rungkut),Taman Wonorejo Permai RT 1 Perum Nirwana Exclusive Blok AA,686.00
77,Lapangan Bola Basket Puri Kencana Karah,Bola Basket,Kec. Jambangan,Kel. Jambangan,PURI KENCANA KARAH JAMBANGAN,420.00
78,Lapangan Bola Basket Rungkut Mejoyo Selatan,Bola Basket,Kec. Rungkut,Kel. Kalirungkut,Jl. Rungkut Mejoyo Selatan IX RT 9 Taman PKK RW 1,686.00
79,Lapangan Bola Basket Rusun Romokalisari,Bola Basket,Kec. Benowo,Kel. Romokalisari,JL. Rusun Romokalisari,686.00
80,Lapangan Bola Basket Semalang Indah RT 9,Bola Basket,Kec. Sukolilo,Kel. Klampis Ngasem,SEMALANG INDAH RT.9,364.00
81,Lapangan Bola Basket TENGGILIS MEJOYO SELATAN NO. 7 RT. 5,Bola Basket,Kec. Tenggilis Mejoyo,Kel. Tenggilis Mejoyo,TENGGILIS MEJOYO SELATAN NO. 7 RT. 5,184.00
82,Lapangan Bola Basket Taman Wonorejo Indah Timur II,Bola Basket,Kec. Rungkut,Kel. Wonorejo (Rungkut),Taman Wonorejo Permai Timur II RT 3 RW 5,686.00
83,Lapangan Bola Basket Taman Wonorejo Permai Timur II RT 3 RW 5,Bola Basket,Kec. Rungkut,Kel. Wonorejo (Rungkut),Taman Wonorejo Permai Timur II RT 3 RW 5,686.00
84,Lapangan Bola Basket Wijaya Kusuma,Bola Basket,Kec. Genteng,Kel. Ketabang,JL. WIJAYA KUSUMA 50,504.00
85,Lapangan Bola Basket Wijaya Kusuma 50,Bola Basket,Kec. Genteng,Kel. Ketabang,JL. WIJAYA KUSUMA 50,504.00
86,Lapangan Bola Volley (Fasum) Jl. Dukuh Kupang Barat I/17-19,Bola Volley,Kec. Sawahan,Kel. Putat Jaya,(Fasum) Jl. Dukuh Kupang Barat I/17-19,200.00
87,Lapangan Bola Volley (JL DUKUH KUPANG BARAT 1),Bola Volley,Kec. Sawahan,Kel. Putat Jaya,Jl Dukuh Kupang Barat 1,152.00
88,Lapangan Bola Volley (JL. TENGGER KANDANGAN IX),Bola Volley,Kec. Benowo,Kel. Kandangan,Jl Tengger Kandangan IX,126.00
89,Lapangan Bola Volley BUNTARAN TELAGA RW 4,Bola Volley,Kec. Tandes,Kel. Manukan Wetan,BUNTARAN TELAGA RW 4,264.00
90,Lapangan Bola Volley Balasklumprik RT 6 RW 7,Bola Volley,Kec. Wiyung,Kel. Balas Klumprik,Kelurahan Balasklumprik RT 6 RW 7,242.00
91,Lapangan Bola Volley Baratajaya,Bola Volley,Kec. Gubeng,Kel. Baratajaya,Jl. Baratajaya,504.00
92,Lapangan Bola Volley Belakang Kantor Kelurahan Lakarsantri,Bola Volley,Kec. Lakarsantri,Kel. Lakarsantri,Jl. Lakarsantri belakang kantor kelurahan RT. - RW.3,200.00
93,Lapangan Bola Volley Depan Colombo,Bola Volley,Kec. Krembangan,Kel. Perak Barat,Jl. Ikan Kerapu (depan Colombo) RT 01 RW V,200.00
94,Lapangan Bola Volley Dukuh Kupang Barat,Bola Volley,Kec. Sawahan,Kel. Putat Jaya,(Fasum) Jl. Dukuh Kupang Barat I/17-19,200.00
95,Lapangan Bola Volley Dukuh Menanggal,Bola Volley,Kec. Gayungan,Kel. Menanggal,JALAN DUKUH MENANGGAL XII NO.6 RT.1,200.00
96,Lapangan Bola Volley Fasum Rusun Jambangan,Bola Volley,Kec. Jambangan,Kel. Jambangan,Fasum Rusun Jambangan,200.00
97,Lapangan Bola Volley Gayungan Pasar,Bola Volley,Kec. Gayungan,Kel. Gayungan,JL. Gayungan Pasar RT 6,242.00
98,Lapangan Bola Volley IKAN MUNGSING I NO.1 RT.11,Bola Volley,Kec. Krembangan,Kel. Perak Barat,IKAN MUNGSING I NO.1 RT.11,200.00
99,Lapangan Bola Volley Ikan Kerapu,Bola Volley,Kec. Krembangan,Kel. Perak Barat,Jl. Ikan Kerapu (depan Colombo) RT 01 RW V,200.00
100,Lapangan Bola Volley JL. Ikan Dorang Baru RT 9,Bola Volley,Kec. Krembangan,Kel. Perak Barat,JL. Ikan Dorang Baru RT 9,242.00
101,Lapangan Bola Volley JL. Jambangan Sentra PKL,Bola Volley,Kec. Jambangan,Kel. Jambangan,JL. Jambangan Sentra PKL,242.00
102,Lapangan Bola Volley JL. KLAKAHREJO III EKS. WISMA LEMBAYUNG,Bola Volley,Kec. Benowo,Kel. Kandangan,JL. KLAKAHREJO III EKS. WISMA LEMBAYUNG,115.20
103,Lapangan Bola Volley JL. KUWUKAN IV RT 5 RW 06,Bola Volley,Kec. Sambikerep,Kel. Lontar,JL. KUWUKAN IV RT 5 RW 06,200.00
104,Lapangan Bola Volley JL. Manukan Dadi GG. VI RT 6,Bola Volley,Kec. Tandes,Kel. Manukan Kulon,JL. Manukan Dadi GG. VI RT 6,242.00
105,Lapangan Bola Volley JL. Raya Tengger Kandangan RT 3,Bola Volley,Kec. Benowo,Kel. Kandangan,JL. Raya Tengger Kandangan RT 3,242.00
106,Lapangan Bola Volley JL. Wonorungkut Utara RT 2 Tanah Fasum,Bola Volley,Kec. Rungkut,Kel. Wonorejo (Rungkut),JL. Wonorungkut Utara RT 2 Tanah Fasum,242.00
107,Lapangan Bola Volley JL.KARANGPOH INDAH,Bola Volley,Kec. Tandes,Kel. Karang Poh,JL.KARANGPOH INDAH,200.00
108,Lapangan Bola Volley Jalan Dukuh Menanggal XII,Bola Volley,Kec. Gayungan,Kel. Menanggal,JALAN DUKUH MENANGGAL XII NO.6 RT.1,200.00
109,Lapangan Bola Volley Jambangan Sentra PKL,Bola Volley,Kec. Jambangan,Kel. Jambangan,JL. Jambangan Sentra PKL,242.00
110,Lapangan Bola Volley Jemur Wonosari,Bola Volley,Kec. Wonocolo,Kel. Jemur Wonosari,Jl. Jemur Wonosari RW.7,200.00
111,Lapangan Bola Volley Jl. Babat Jerawat,Bola Volley,Kec. Pakal,Kel. Babat Jerawat,Jl. Babat Jerawat,200.00

In [ ]:
# Tampilkan seluruh kandidat venue
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_colwidth', 100)

display(
    kandidat_venue[
        [
            'nama_fasilitas_olahraga',
            'jenis_olahraga',
            'kecamatan',
            'kelurahan',
            'alamatlokasi',
            'luas'
        ]
    ].sort_values(
        ['jenis_olahraga', 'nama_fasilitas_olahraga']
    ).reset_index(drop=True)
)

,nama_fasilitas_olahraga,jenis_olahraga,kecamatan,kelurahan,alamatlokasi,luas
0,Gelora Pancasila,Bola Basket,Kec. Wonokromo,Kel. Darmo,Jl. Indragiri No. 6,4432.000
1,Stadion Indoor Gelora Bung Tomo,Futsal,Kec. Pakal,Kel. Pakal,GELORA BUNG TOMO SURABAYA,31.826
2,Gedung Koni Kodya Surabaya,Gedung Serbaguna,Kec. Tambaksari,Kel. Ploso,Jl. Bogen 1,11000.000
3,Gelanggang Remaja,Gedung Serbaguna,Kec. Tambaksari,Kel. Ploso,"Jl. Bogen I No.53-Q, Ploso, Tambaksari",4200.000
4,"Gelanggang Remaja Jl. Bogen I No.53-Q, Ploso, Tambaksari",Gedung Serbaguna,Kec. Tambaksari,Kel. Ploso,"Jl. Bogen I No.53-Q, Ploso, Tambaksari",4200.000
5,Lapangan Hockey,Hockey,Kec. Gubeng,Kel. Airlangga,Jl. Dharmawangsa sd. Tahap V (2012-2016),6000.000
6,Lapangan Hockey Dharmawangsa,Hockey,Kec. Gubeng,Kel. Airlangga,Jl. Dharmawangsa 2,6000.000
7,Kolam Renang,Renang,Kec. Jambangan,Kel. Karah,Jl. Ketintang madya VII,12280.000
8,Kolam Renang Jambangan,Renang,Kec. Jambangan,Kel. Karah,Jl. Ketintang madya VII,12280.000
9,Gelora 10 Nopember,Sepak Bola,Kec. Tambaksari,Kel. Ploso,Jl. Tambaksari Surabaya,49400.000
10,Gelora Bung Tomo,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1,60000.000
11,Lapangan Latihan B Gelora Bung Tomo,Sepak Bola,Kec. Pakal,Kel. Benowo,GELORA BUNG TOMO B,6090.000
12,Lapangan Latihan Sepak Bola Stadion A,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1 A,8925.000
13,Lapangan Latihan Sepak Bola Stadion B,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1 B,8925.000
14,Lapangan Latihan Sepak Bola Stadion C,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1 C,8925.000
15,Stadion Gelora 10 Nopember,Sepak Bola,Kec. Tambaksari,Kel. Tambaksari,Jl. Tambaksari Surabaya,49400.000
16,Stadion Gelora Bung Tomo,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1,60000.000
17,Lapangan Olahraga Tenis Dharmawangsa,Tenis,Kec. Gubeng,Kel. Airlangga,Jl. Dharmawangsa 3,1106.000
18,Lapangan Olahraga Tennis Dharmawangsa,Tenis,Kec. Gubeng,Kel. Airlangga,Jl. Dharmawangsa No.4,1106.000
19,Lapangan Tenis Babatan Pratama,Tenis,Kec. Wiyung,Kel. Wiyung,JL. Perumahan Babatan Pratama Wiyung,420.000
20,Lapangan Tenis Babatan Pratama Wiyung,Tenis,Kec. Wiyung,Kel. Wiyung,JL. Perumahan Babatan Pratama Wiyung,420.000
21,Lapangan Tenis Dharmawangsa,Tenis,Kec. Gubeng,Kel. Airlangga,Jl. Dharmawangsa Tenis,1200.000
22,Lapangan Tenis Greges Timur,Tenis,Kec. Asemrowo,Kel. Genting Kalianak,Jl. Greges Timur,630.000
23,Lapangan Tenis Griya Kencana Asri,Tenis,Kec. Rungkut,Kel. Wonorejo (Rungkut),Perum Griya Kencana Asri,420.000
24,Lapangan Tenis JL. SIMOREJO TIMUR NO. 4 RT. 4,Tenis,Kec. Sukomanunggal,Kel. Sukomanunggal,JL. SIMOREJO TIMUR NO. 4 RT. 4,420.000
25,Lapangan Tenis JL. WISMA TENGGER,Tenis,Kec. Benowo,Kel. Kandangan,JL. WISMA TENGGER,630.000
26,Lapangan Tenis Jl. Nginden VI,Tenis,Kec. Sukolilo,Kel. Nginden Jangkungan,Jl. Nginden VI,630.000
27,Lapangan Tenis Ketintang Permai,Tenis,Kec. Jambangan,Kel. Karah,Jl. Ketintang Selatan,630.000
28,Lapangan Tenis PURI KENCANA JAMBANGAN,Tenis,Kec. Jambangan,Kel. Jambangan,PURI KENCANA JAMBANGAN,638.480
29,Lapangan Tenis Pondok Maritim RW 6,Tenis,Kec. Wiyung,Kel. Balas Klumprik,JL. Pondok Maritim RW 6,420.000
30,Lapangan Tennis Ketintang Selatan III,Tenis,Kec. Jambangan,Kel. Karah,Jl. Ketintang Selatan III,500.000
31,Lapangan Tennis Puri Kencana Jambangan,Tenis,Kec. Jambangan,Kel. Jambangan,Puri Kencana Jambangan,63848.000
32,Lapangan Tennis Sambiroto,Tenis,Kec. Sambikerep,Kel. Sambikerep,Lapangan Tennis Sambiroto,504.000

In [ ]:
# MASTER VENUE
master_venue = kandidat_venue[
    [
        'nama_fasilitas_olahraga',
        'jenis_olahraga',
        'kecamatan',
        'kelurahan',
        'alamatlokasi',
        'luas'
    ]
].copy()

# Mapping nama fasilitas ke nama venue standar
mapping_venue = {
    'Gelanggang Remaja': 'Gelanggang Remaja',
    'Gelanggang Remaja Jl. Bogen I No.53-Q, Ploso, Tambaksari': 'Gelanggang Remaja',

    'Kolam Renang': 'Kolam Renang Jambangan',
    'Kolam Renang Jambangan': 'Kolam Renang Jambangan',

    'Gelora 10 Nopember': 'Gelora 10 Nopember',
    'Stadion Gelora 10 Nopember': 'Gelora 10 Nopember',

    'Gelora Bung Tomo': 'Gelora Bung Tomo',
    'Stadion Gelora Bung Tomo': 'Gelora Bung Tomo',

    'Lapangan Tenis Babatan Pratama': 'Lapangan Tenis Babatan Pratama',
    'Lapangan Tenis Babatan Pratama Wiyung': 'Lapangan Tenis Babatan Pratama'
}

master_venue['nama_venue'] = (
    master_venue['nama_fasilitas_olahraga']
    .replace(mapping_venue)
)

# Ambil satu baris untuk setiap venue standar
master_venue = (
    master_venue
    .drop_duplicates(subset=['nama_venue'])
    .reset_index(drop=True)
)

# Buat ID venue
master_venue.insert(
    0,
    'id_venue',
    ['V{:03d}'.format(i) for i in range(1, len(master_venue) + 1)]
)

print("Jumlah master venue:", len(master_venue))

display(master_venue)

Jumlah master venue: 28

,id_venue,nama_fasilitas_olahraga,jenis_olahraga,kecamatan,kelurahan,alamatlokasi,luas,nama_venue
0,V001,Gedung Koni Kodya Surabaya,Gedung Serbaguna,Kec. Tambaksari,Kel. Ploso,Jl. Bogen 1,11000.000,Gedung Koni Kodya Surabaya
1,V002,Gelanggang Remaja,Gedung Serbaguna,Kec. Tambaksari,Kel. Ploso,"Jl. Bogen I No.53-Q, Ploso, Tambaksari",4200.000,Gelanggang Remaja
2,V003,Gelora 10 Nopember,Sepak Bola,Kec. Tambaksari,Kel. Ploso,Jl. Tambaksari Surabaya,49400.000,Gelora 10 Nopember
3,V004,Gelora Bung Tomo,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1,60000.000,Gelora Bung Tomo
4,V005,Gelora Pancasila,Bola Basket,Kec. Wonokromo,Kel. Darmo,Jl. Indragiri No. 6,4432.000,Gelora Pancasila
5,V006,Kolam Renang,Renang,Kec. Jambangan,Kel. Karah,Jl. Ketintang madya VII,12280.000,Kolam Renang Jambangan
6,V007,Lapangan Hockey,Hockey,Kec. Gubeng,Kel. Airlangga,Jl. Dharmawangsa sd. Tahap V (2012-2016),6000.000,Lapangan Hockey
7,V008,Lapangan Hockey Dharmawangsa,Hockey,Kec. Gubeng,Kel. Airlangga,Jl. Dharmawangsa 2,6000.000,Lapangan Hockey Dharmawangsa
8,V009,Lapangan Latihan B Gelora Bung Tomo,Sepak Bola,Kec. Pakal,Kel. Benowo,GELORA BUNG TOMO B,6090.000,Lapangan Latihan B Gelora Bung Tomo
9,V010,Lapangan Latihan Sepak Bola Stadion A,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1 A,8925.000,Lapangan Latihan Sepak Bola Stadion A
10,V011,Lapangan Latihan Sepak Bola Stadion B,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1 B,8925.000,Lapangan Latihan Sepak Bola Stadion B
11,V012,Lapangan Latihan Sepak Bola Stadion C,Sepak Bola,Kec. Pakal,Kel. Benowo,Jl. Jawar No 1 C,8925.000,Lapangan Latihan Sepak Bola Stadion C
12,V013,Lapangan Olahraga Tenis Dharmawangsa,Tenis,Kec. Gubeng,Kel. Airlangga,Jl. Dharmawangsa 3,1106.000,Lapangan Olahraga Tenis Dharmawangsa
13,V014,Lapangan Olahraga Tennis Dharmawangsa,Tenis,Kec. Gubeng,Kel. Airlangga,Jl. Dharmawangsa No.4,1106.000,Lapangan Olahraga Tennis Dharmawangsa
14,V015,Lapangan Tenis Babatan Pratama,Tenis,Kec. Wiyung,Kel. Wiyung,JL. Perumahan Babatan Pratama Wiyung,420.000,Lapangan Tenis Babatan Pratama
15,V016,Lapangan Tenis Dharmawangsa,Tenis,Kec. Gubeng,Kel. Airlangga,Jl. Dharmawangsa Tenis,1200.000,Lapangan Tenis Dharmawangsa
16,V017,Lapangan Tenis Greges Timur,Tenis,Kec. Asemrowo,Kel. Genting Kalianak,Jl. Greges Timur,630.000,Lapangan Tenis Greges Timur
17,V018,Lapangan Tenis Griya Kencana Asri,Tenis,Kec. Rungkut,Kel. Wonorejo (Rungkut),Perum Griya Kencana Asri,420.000,Lapangan Tenis Griya Kencana Asri
18,V019,Lapangan Tenis JL. SIMOREJO TIMUR NO. 4 RT. 4,Tenis,Kec. Sukomanunggal,Kel. Sukomanunggal,JL. SIMOREJO TIMUR NO. 4 RT. 4,420.000,Lapangan Tenis JL. SIMOREJO TIMUR NO. 4 RT. 4
19,V020,Lapangan Tenis JL. WISMA TENGGER,Tenis,Kec. Benowo,Kel. Kandangan,JL. WISMA TENGGER,630.000,Lapangan Tenis JL. WISMA TENGGER
20,V021,Lapangan Tenis Jl. Nginden VI,Tenis,Kec. Sukolilo,Kel. Nginden Jangkungan,Jl. Nginden VI,630.000,Lapangan Tenis Jl. Nginden VI
21,V022,Lapangan Tenis Ketintang Permai,Tenis,Kec. Jambangan,Kel. Karah,Jl. Ketintang Selatan,630.000,Lapangan Tenis Ketintang Permai
22,V023,Lapangan Tenis PURI KENCANA JAMBANGAN,Tenis,Kec. Jambangan,Kel. Jambangan,PURI KENCANA JAMBANGAN,638.480,Lapangan Tenis PURI KENCANA JAMBANGAN
23,V024,Lapangan Tenis Pondok Maritim RW 6,Tenis,Kec. Wiyung,Kel. Balas Klumprik,JL. Pondok Maritim RW 6,420.000,Lapangan Tenis Pondok Maritim RW 6
24,V025,Lapangan Tennis Ketintang Selatan III,Tenis,Kec. Jambangan,Kel. Karah,Jl. Ketintang Selatan III,500.000,Lapangan Tennis Ketintang Selatan III
25,V026,Lapangan Tennis Puri Kencana Jambangan,Tenis,Kec. Jambangan,Kel. Jambangan,Puri Kencana Jambangan,63848.000,Lapangan Tennis Puri Kencana Jambangan
26,V027,Lapangan Tennis Sambiroto,Tenis,Kec. Sambikerep,Kel. Sambikerep,Lapangan Tennis Sambiroto,504.000,Lapangan Tennis Sambiroto
27,V028,Stadion Indoor Gelora Bung Tomo,Futsal,Kec. Pakal,Kel. Pakal,GELORA BUNG TOMO SURABAYA,31.826,Stadion Indoor Gelora Bung Tomo

untuk sementara belum menggabungkan fasilitas Dharmawangsa, lapangan latihan GBT, atau Puri Kencana yang datanya mencurigakan

target awal:
1. Gelora Bung Tomo
2. Gelora 10 Nopember
3. Lapangan Latihan B Gelora Bung Tomo
4. Lapangan Latihan Sepak Bola Stadion A
5. Lapangan Latihan Sepak Bola Stadion B
6. Lapangan Latihan Sepak Bola Stadion C

# 2. Menyiapkan Struktur Data Event

In [ ]:
# DATA EVENT OLAHRAGA
kolom_event = [
    'id_event',
    'nama_event',
    'jenis_olahraga',
    'tanggal_mulai',
    'tanggal_selesai',
    'nama_venue',
    'level_event',
    'peserta_tim',
    'hasil_skor',
    'sumber'
]

data_event = pd.DataFrame(columns=kolom_event)

data_event

Empty DataFrame
Columns: [id_event, nama_event, jenis_olahraga, tanggal_mulai, tanggal_selesai, nama_venue, level_event, peserta_tim, hasil_skor, sumber]
Index: []

# 3. Library dan Import

In [ ]:
!pip install requests beautifulsoup4 lxml -q

In [ ]:
import requests
import pandas as pd
import re
from bs4 import BeautifulSoup

# 4. Scraping Event Liga 1

# Gelora Bung Tomo

## Liga 1

### 4.1 URL dan pemeriksaan halaman Liga 1

In [ ]:
urls_persebaya = {
    'BRI Liga 1 2023-2024':
        'https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA',

    'BRI Liga 1 2024-2025':
        'https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA'
}

In [ ]:
url = urls_persebaya['BRI Liga 1 2023-2024']

response = requests.get(
    url,
    headers={
        'User-Agent': 'Mozilla/5.0'
    },
    timeout=30
)

print("Status code:", response.status_code)
print("Ukuran halaman:", len(response.text))

Status code: 200
Ukuran halaman: 272390

### 4.2 Fungsi scraping pertandingan Liga 1 musim 2023/2024

In [ ]:
def scrape_persebaya(url, musim):

    response = requests.get(
        url,
        headers={
            'User-Agent': 'Mozilla/5.0'
        },
        timeout=30
    )

    response.raise_for_status()

    soup = BeautifulSoup(response.text, 'html.parser')

    # Ambil seluruh teks halaman
    text = soup.get_text(" ", strip=True)

    # Pola tanggal Indonesia
    bulan = (
        r'Januari|Februari|Maret|April|Mei|Juni|'
        r'Juli|Agustus|September|Oktober|November|Desember'
    )

    pola = rf'(\d{{1,2}}\s+(?:{bulan})\s+\d{{4}})\s+'
    pola += r'(.+?)\s+FT\s+(\d+:\d+)\s+(.+?)\s+'
    pola += r'(GELORA BUNG TOMO)'

    hasil = re.findall(
        pola,
        text,
        flags=re.IGNORECASE
    )

    data = []

    for tanggal, tim_home, skor, tim_away, venue in hasil:

        data.append({
            'musim': musim,
            'tanggal': tanggal,
            'tim_home': tim_home.strip(),
            'skor': skor,
            'tim_away': tim_away.strip(),
            'nama_venue': 'Gelora Bung Tomo',
            'jenis_olahraga': 'Sepak Bola',
            'level_event': 'Nasional',
            'sumber': url
        })

    return pd.DataFrame(data)

In [ ]:
df_event_list = []

for musim, url in urls_persebaya.items():

    print("Scraping:", musim)

    df = scrape_persebaya(url, musim)

    print("Jumlah pertandingan GBT:", len(df))

    df_event_list.append(df)

data_event_gbt = pd.concat(
    df_event_list,
    ignore_index=True
)

display(data_event_gbt)

Scraping: BRI Liga 1 2023-2024
Jumlah pertandingan GBT: 17
Scraping: BRI Liga 1 2024-2025
Jumlah pertandingan GBT: 17

,musim,tanggal,tim_home,skor,tim_away,nama_venue,jenis_olahraga,level_event,sumber
0,BRI Liga 1 2023-2024,1 Juli 2023,PERSIS SOLO,2:3,PERSEBAYA SURABAYA MANAHAN 8 Juli 2023 PERSEBAYA SURABAYA FT 1:1 PS BARITO PUTERA,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
1,BRI Liga 1 2023-2024,16 Juli 2023,PSIS SEMARANG,2:0,PERSEBAYA SURABAYA JATIDIRI 23 Juli 2023 PERSEBAYA SURABAYA FT 2:2 RANS Nusantara FC,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
2,BRI Liga 1 2023-2024,30 Juli 2023,PERSIJA JAKARTA,1:0,PERSEBAYA SURABAYA GELORA BUNG KARNO 4 Agustus 2023 PERSEBAYA SURABAYA FT 1:2 PERSIKABO 1973,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
3,BRI Liga 1 2023-2024,8 Agustus 2023,BHAYANGKARA PRESISI LAMPUNG FC,1:2,PERSEBAYA SURABAYA PATRIOT CHANDRA BHAGA 12 Agustus 2023 PERSEBAYA SURABAYA FT 1:0 PERSITA,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
4,BRI Liga 1 2023-2024,18 Agustus 2023,PERSEBAYA SURABAYA,1:0,PSM MAKASSAR,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
5,BRI Liga 1 2023-2024,26 Agustus 2023,PSS SLEMAN,0:0,PERSEBAYA SURABAYA MAGUWOHARJO 3 September 2023 PERSEBAYA SURABAYA FT 2:1 BORNEO FC SAMARINDA,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
6,BRI Liga 1 2023-2024,17 September 2023,MADURA UNITED FC,3:0,PERSEBAYA SURABAYA GELORA BANGKALAN 23 September 2023 PERSEBAYA SURABAYA FT 3:1 AREMA FC,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
7,BRI Liga 1 2023-2024,30 September 2023,DEWA UNITED BANTEN FC,1:1,PERSEBAYA SURABAYA INDOMILK ARENA 7 Oktober 2023 PERSEBAYA SURABAYA FT 2:3 PERSIB BANDUNG,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
8,BRI Liga 1 2023-2024,20 Oktober 2023,BALI UNITED FC,3:1,PERSEBAYA SURABAYA KAPTEN I WAYAN DIPTA 27 Oktober 2023 PERSIK KEDIRI FT 4:0 PERSEBAYA SURABAYA ...,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
9,BRI Liga 1 2023-2024,13 Desember 2023,PERSEBAYA SURABAYA,1:1,PERSIS SOLO,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
10,BRI Liga 1 2023-2024,17 Desember 2023,PERSIKABO 1973,1:1,PERSEBAYA SURABAYA WIBAWA MUKTI 30 Januari 2024 PERSEBAYA SURABAYA FT 1:1 PSIS SEMARANG,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
11,BRI Liga 1 2023-2024,4 Februari 2024,PERSEBAYA SURABAYA,1:0,BHAYANGKARA PRESISI LAMPUNG FC,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
12,BRI Liga 1 2023-2024,23 Februari 2024,PERSITA,1:1,PERSEBAYA SURABAYA INDOMILK ARENA 28 Februari 2024 PSM MAKASSAR FT 0:0 PERSEBAYA SURABAYA BATAKA...,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
13,BRI Liga 1 2023-2024,7 Maret 2024,BORNEO FC SAMARINDA,2:1,PERSEBAYA SURABAYA BATAKAN 13 Maret 2024 PERSEBAYA SURABAYA FT 0:0 MADURA UNITED FC,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
14,BRI Liga 1 2023-2024,27 Maret 2024,AREMA FC,0:1,PERSEBAYA SURABAYA KAPTEN I WAYAN DIPTA 16 April 2024 PERSEBAYA SURABAYA FT 0:3 DEWA UNITED BANT...,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
15,BRI Liga 1 2023-2024,20 April 2024,PERSIB BANDUNG,3:1,PERSEBAYA SURABAYA SI JALAK HARUPAT 24 April 2024 PERSEBAYA SURABAYA FT 0:2 BALI UNITED FC,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
16,BRI Liga 1 2023-2024,28 April 2024,PERSEBAYA SURABAYA,2:1,PERSIK KEDIRI,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
17,BRI Liga 1 2024-2025,11 Agustus 2024,PERSEBAYA SURABAYA,1:0,PSS SLEMAN,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
18,BRI Liga 1 2024-2025,16 Agustus 2024,JAVA UNITED FC,0:0,PERSEBAYA SURABAYA MADYA GELORA BUNG KARNO 23 Agustus 2024 PERSEBAYA SURABAYA FT 2:1 PS BARITO P...,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
19,BRI Liga 1 2024-2025,14 September 2024,PERSITA,0:1,PERSEBAYA SURABAYA KAPTEN I WAYAN DIPTA 18 September 2024 PERSEBAYA SURABAYA FT 2:1 PERSIS SOLO,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
20,BRI Liga 1 2024-2025,22 September 2024,PSBS BIAK,0:1,PERSEBAYA SURABAYA KAPTEN I WAYAN DIPTA 27 September 2024 PERSEBAYA SURABAYA FT 0:0 DEWA UNITED ...,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
21,BRI Liga 1 2024-2025,18 Oktober 2024,PERSIB BANDUNG,2:0,PERSEBAYA SURABAYA SI JALAK HARUPAT 23 Oktober 2024 PERSEBAYA SURABAYA FT 1:1 PSM MAKASSAR,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
22,BRI Liga 1 2024-2025,2 November 2024,PSIS SEMARANG,0:1,PERSEBAYA SURABAYA KAPTEN I WAYAN DIPTA 22 November 2024 PERSEBAYA SURABAYA FT 2:1 PERSIJA JAKARTA,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
23,BRI Liga 1 2024-2025,2 Desember 2024,MADURA UNITED FC,1:2,PERSEBAYA SURABAYA GELORA BANGKALAN 7 Desember 2024 PERSEBAYA SURABAYA FT 3:2 AREMA FC,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
24,BRI Liga 1 2024-2025,11 Desember 2024,PERSEBAYA SURABAYA,4:1,PERSIK KEDIRI,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
25,BRI Liga 1 2024-2025,15 Desember 2024,SEMEN PADANG FC,0:0,PERSEBAYA SURABAYA H. AGUS SALIM 20 Desember 2024 PERSEBAYA SURABAYA FT 2:1 BORNEO FC SAMARINDA,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
26,BRI Liga 1 2024-2025,28 Desember 2024,BALI UNITED FC,2:0,PERSEBAYA SURABAYA KAPTEN I WAYAN DIPTA 11 Januari 2025 PSS SLEMAN FT 3:1 PERSEBAYA SURABAYA MAN...,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
27,BRI Liga 1 2024-2025,25 Januari 2025,PS BARITO PUTERA,3:0,PERSEBAYA SURABAYA KAPTEN I WAYAN DIPTA 31 Januari 2025 PERSEBAYA SURABAYA FT 1:1 PERSITA,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
28,BRI Liga 1 2024-2025,7 Februari 2025,PERSIS SOLO,2:1,PERSEBAYA SURABAYA MANAHAN 15 Februari 2025 PERSEBAYA SURABAYA FT 1:0 PSBS BIAK,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
29,BRI Liga 1 2024-2025,21 Februari 2025,DEWA UNITED BANTEN FC,2:0,PERSEBAYA SURABAYA PAKANSARI 1 Maret 2025 PERSEBAYA SURABAYA FT 4:1 PERSIB BANDUNG,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
30,BRI Liga 1 2024-2025,7 Maret 2025,PSM MAKASSAR,0:1,PERSEBAYA SURABAYA GELORA B. J. HABIBIE 12 Maret 2025 PERSEBAYA SURABAYA FT 1:1 PSIS SEMARANG,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
31,BRI Liga 1 2024-2025,12 April 2025,PERSIJA JAKARTA,1:1,PERSEBAYA SURABAYA GELORA BUNG KARNO 20 April 2025 PERSEBAYA SURABAYA FT 1:0 MADURA UNITED FC,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
32,BRI Liga 1 2024-2025,28 April 2025,AREMA FC,1:1,PERSEBAYA SURABAYA KAPTEN I WAYAN DIPTA 5 Mei 2025 PERSIK KEDIRI FT 3:3 PERSEBAYA SURABAYA BRAWI...,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
33,BRI Liga 1 2024-2025,18 Mei 2025,BORNEO FC SAMARINDA,1:1,PERSEBAYA SURABAYA SEGIRI 23 Mei 2025 PERSEBAYA SURABAYA FT 1:3 BALI UNITED FC,Gelora Bung Tomo,Sepak Bola,Nasional,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA

In [ ]:
print("Jumlah pertandingan:", len(data_event_gbt))

display(
    data_event_gbt[
        [
            'musim',
            'tanggal',
            'tim_home',
            'skor',
            'tim_away',
            'nama_venue'
        ]
    ]
)

Jumlah pertandingan: 34

,musim,tanggal,tim_home,skor,tim_away,nama_venue
0,BRI Liga 1 2023-2024,1 Juli 2023,PERSIS SOLO,2:3,PERSEBAYA SURABAYA MANAHAN 8 Juli 2023 PERSEBAYA SURABAYA FT 1:1 PS BARITO PUTERA,Gelora Bung Tomo
1,BRI Liga 1 2023-2024,16 Juli 2023,PSIS SEMARANG,2:0,PERSEBAYA SURABAYA JATIDIRI 23 Juli 2023 PERSEBAYA SURABAYA FT 2:2 RANS Nusantara FC,Gelora Bung Tomo
2,BRI Liga 1 2023-2024,30 Juli 2023,PERSIJA JAKARTA,1:0,PERSEBAYA SURABAYA GELORA BUNG KARNO 4 Agustus 2023 PERSEBAYA SURABAYA FT 1:2 PERSIKABO 1973,Gelora Bung Tomo
3,BRI Liga 1 2023-2024,8 Agustus 2023,BHAYANGKARA PRESISI LAMPUNG FC,1:2,PERSEBAYA SURABAYA PATRIOT CHANDRA BHAGA 12 Agustus 2023 PERSEBAYA SURABAYA FT 1:0 PERSITA,Gelora Bung Tomo
4,BRI Liga 1 2023-2024,18 Agustus 2023,PERSEBAYA SURABAYA,1:0,PSM MAKASSAR,Gelora Bung Tomo
5,BRI Liga 1 2023-2024,26 Agustus 2023,PSS SLEMAN,0:0,PERSEBAYA SURABAYA MAGUWOHARJO 3 September 2023 PERSEBAYA SURABAYA FT 2:1 BORNEO FC SAMARINDA,Gelora Bung Tomo
6,BRI Liga 1 2023-2024,17 September 2023,MADURA UNITED FC,3:0,PERSEBAYA SURABAYA GELORA BANGKALAN 23 September 2023 PERSEBAYA SURABAYA FT 3:1 AREMA FC,Gelora Bung Tomo
7,BRI Liga 1 2023-2024,30 September 2023,DEWA UNITED BANTEN FC,1:1,PERSEBAYA SURABAYA INDOMILK ARENA 7 Oktober 2023 PERSEBAYA SURABAYA FT 2:3 PERSIB BANDUNG,Gelora Bung Tomo
8,BRI Liga 1 2023-2024,20 Oktober 2023,BALI UNITED FC,3:1,PERSEBAYA SURABAYA KAPTEN I WAYAN DIPTA 27 Oktober 2023 PERSIK KEDIRI FT 4:0 PERSEBAYA SURABAYA ...,Gelora Bung Tomo
9,BRI Liga 1 2023-2024,13 Desember 2023,PERSEBAYA SURABAYA,1:1,PERSIS SOLO,Gelora Bung Tomo
10,BRI Liga 1 2023-2024,17 Desember 2023,PERSIKABO 1973,1:1,PERSEBAYA SURABAYA WIBAWA MUKTI 30 Januari 2024 PERSEBAYA SURABAYA FT 1:1 PSIS SEMARANG,Gelora Bung Tomo
11,BRI Liga 1 2023-2024,4 Februari 2024,PERSEBAYA SURABAYA,1:0,BHAYANGKARA PRESISI LAMPUNG FC,Gelora Bung Tomo
12,BRI Liga 1 2023-2024,23 Februari 2024,PERSITA,1:1,PERSEBAYA SURABAYA INDOMILK ARENA 28 Februari 2024 PSM MAKASSAR FT 0:0 PERSEBAYA SURABAYA BATAKA...,Gelora Bung Tomo
13,BRI Liga 1 2023-2024,7 Maret 2024,BORNEO FC SAMARINDA,2:1,PERSEBAYA SURABAYA BATAKAN 13 Maret 2024 PERSEBAYA SURABAYA FT 0:0 MADURA UNITED FC,Gelora Bung Tomo
14,BRI Liga 1 2023-2024,27 Maret 2024,AREMA FC,0:1,PERSEBAYA SURABAYA KAPTEN I WAYAN DIPTA 16 April 2024 PERSEBAYA SURABAYA FT 0:3 DEWA UNITED BANT...,Gelora Bung Tomo
15,BRI Liga 1 2023-2024,20 April 2024,PERSIB BANDUNG,3:1,PERSEBAYA SURABAYA SI JALAK HARUPAT 24 April 2024 PERSEBAYA SURABAYA FT 0:2 BALI UNITED FC,Gelora Bung Tomo
16,BRI Liga 1 2023-2024,28 April 2024,PERSEBAYA SURABAYA,2:1,PERSIK KEDIRI,Gelora Bung Tomo
17,BRI Liga 1 2024-2025,11 Agustus 2024,PERSEBAYA SURABAYA,1:0,PSS SLEMAN,Gelora Bung Tomo
18,BRI Liga 1 2024-2025,16 Agustus 2024,JAVA UNITED FC,0:0,PERSEBAYA SURABAYA MADYA GELORA BUNG KARNO 23 Agustus 2024 PERSEBAYA SURABAYA FT 2:1 PS BARITO P...,Gelora Bung Tomo
19,BRI Liga 1 2024-2025,14 September 2024,PERSITA,0:1,PERSEBAYA SURABAYA KAPTEN I WAYAN DIPTA 18 September 2024 PERSEBAYA SURABAYA FT 2:1 PERSIS SOLO,Gelora Bung Tomo
20,BRI Liga 1 2024-2025,22 September 2024,PSBS BIAK,0:1,PERSEBAYA SURABAYA KAPTEN I WAYAN DIPTA 27 September 2024 PERSEBAYA SURABAYA FT 0:0 DEWA UNITED ...,Gelora Bung Tomo
21,BRI Liga 1 2024-2025,18 Oktober 2024,PERSIB BANDUNG,2:0,PERSEBAYA SURABAYA SI JALAK HARUPAT 23 Oktober 2024 PERSEBAYA SURABAYA FT 1:1 PSM MAKASSAR,Gelora Bung Tomo
22,BRI Liga 1 2024-2025,2 November 2024,PSIS SEMARANG,0:1,PERSEBAYA SURABAYA KAPTEN I WAYAN DIPTA 22 November 2024 PERSEBAYA SURABAYA FT 2:1 PERSIJA JAKARTA,Gelora Bung Tomo
23,BRI Liga 1 2024-2025,2 Desember 2024,MADURA UNITED FC,1:2,PERSEBAYA SURABAYA GELORA BANGKALAN 7 Desember 2024 PERSEBAYA SURABAYA FT 3:2 AREMA FC,Gelora Bung Tomo
24,BRI Liga 1 2024-2025,11 Desember 2024,PERSEBAYA SURABAYA,4:1,PERSIK KEDIRI,Gelora Bung Tomo
25,BRI Liga 1 2024-2025,15 Desember 2024,SEMEN PADANG FC,0:0,PERSEBAYA SURABAYA H. AGUS SALIM 20 Desember 2024 PERSEBAYA SURABAYA FT 2:1 BORNEO FC SAMARINDA,Gelora Bung Tomo
26,BRI Liga 1 2024-2025,28 Desember 2024,BALI UNITED FC,2:0,PERSEBAYA SURABAYA KAPTEN I WAYAN DIPTA 11 Januari 2025 PSS SLEMAN FT 3:1 PERSEBAYA SURABAYA MAN...,Gelora Bung Tomo
27,BRI Liga 1 2024-2025,25 Januari 2025,PS BARITO PUTERA,3:0,PERSEBAYA SURABAYA KAPTEN I WAYAN DIPTA 31 Januari 2025 PERSEBAYA SURABAYA FT 1:1 PERSITA,Gelora Bung Tomo
28,BRI Liga 1 2024-2025,7 Februari 2025,PERSIS SOLO,2:1,PERSEBAYA SURABAYA MANAHAN 15 Februari 2025 PERSEBAYA SURABAYA FT 1:0 PSBS BIAK,Gelora Bung Tomo
29,BRI Liga 1 2024-2025,21 Februari 2025,DEWA UNITED BANTEN FC,2:0,PERSEBAYA SURABAYA PAKANSARI 1 Maret 2025 PERSEBAYA SURABAYA FT 4:1 PERSIB BANDUNG,Gelora Bung Tomo
30,BRI Liga 1 2024-2025,7 Maret 2025,PSM MAKASSAR,0:1,PERSEBAYA SURABAYA GELORA B. J. HABIBIE 12 Maret 2025 PERSEBAYA SURABAYA FT 1:1 PSIS SEMARANG,Gelora Bung Tomo
31,BRI Liga 1 2024-2025,12 April 2025,PERSIJA JAKARTA,1:1,PERSEBAYA SURABAYA GELORA BUNG KARNO 20 April 2025 PERSEBAYA SURABAYA FT 1:0 MADURA UNITED FC,Gelora Bung Tomo
32,BRI Liga 1 2024-2025,28 April 2025,AREMA FC,1:1,PERSEBAYA SURABAYA KAPTEN I WAYAN DIPTA 5 Mei 2025 PERSIK KEDIRI FT 3:3 PERSEBAYA SURABAYA BRAWI...,Gelora Bung Tomo
33,BRI Liga 1 2024-2025,18 Mei 2025,BORNEO FC SAMARINDA,1:1,PERSEBAYA SURABAYA SEGIRI 23 Mei 2025 PERSEBAYA SURABAYA FT 1:3 BALI UNITED FC,Gelora Bung Tomo

In [ ]:
# Cek struktur HTML halaman
url = urls_persebaya['BRI Liga 1 2023-2024']

response = requests.get(
    url,
    headers={'User-Agent': 'Mozilla/5.0'},
    timeout=30
)

soup = BeautifulSoup(response.text, 'html.parser')

# Cari semua elemen yang mengandung "GELORA BUNG TOMO"
elemen_gbt = soup.find_all(
    string=re.compile('GELORA BUNG TOMO', re.IGNORECASE)
)

print("Jumlah elemen ditemukan:", len(elemen_gbt))

for i, elemen in enumerate(elemen_gbt[:10]):
    print("\n---", i, "---")
    print(elemen.parent.parent.get_text(" ", strip=True)[:1000])

Jumlah elemen ditemukan: 19

--- 0 ---
Stadion: GELORA BUNG TOMO

--- 1 ---
PERSEBAYA SURABAYA FT 1:1 PS BARITO PUTERA GELORA BUNG TOMO

--- 2 ---
PERSEBAYA SURABAYA FT 2:2 RANS Nusantara FC GELORA BUNG TOMO

--- 3 ---
PERSEBAYA SURABAYA FT 1:2 PERSIKABO 1973 GELORA BUNG TOMO

--- 4 ---
PERSEBAYA SURABAYA FT 1:0 PERSITA GELORA BUNG TOMO

--- 5 ---
PERSEBAYA SURABAYA FT 1:0 PSM MAKASSAR GELORA BUNG TOMO

--- 6 ---
PERSEBAYA SURABAYA FT 2:1 BORNEO FC SAMARINDA GELORA BUNG TOMO

--- 7 ---
PERSEBAYA SURABAYA FT 3:1 AREMA FC GELORA BUNG TOMO

--- 8 ---
PERSEBAYA SURABAYA FT 2:3 PERSIB BANDUNG GELORA BUNG TOMO

--- 9 ---
PERSEBAYA SURABAYA FT 1:1 PERSIJA JAKARTA GELORA BUNG TOMO

In [ ]:
# Ambil salah satu elemen pertandingan dan tampilkan struktur HTML-nya

elemen = elemen_gbt[1]

print(elemen.parent.parent.prettify()[:5000])

<tr class="table-row" height="25" style="background-color: #17a2b8;font-size: 14px">
 <td align="right" style="border:0" width="24%">
  <b class="club-fixture-team">
   PERSEBAYA SURABAYA
  </b>
 </td>
 <td style="border:0;padding:0; margin:0;" width="3%">
  <img alt="" src="https://assets.ileague.id/uploads/images/logo/75/v/50/280.png" style="border: none;" width="30"/>
 </td>
 <td class="club-fixture-score" style="border:0">
  <span class="badge badge-secondary" style="background-color: #17a2b8;color: white;font-size: 15px">
   <span style="font-size:14px;color:#efff00;">
    FT
   </span>
   1:1
  </span>
 </td>
 <td style="border:0;padding:0; margin:0;" width="3%">
  <img alt="" src="https://assets.ileague.id/uploads/images/logo/75/v/50/133.png" style="border: none" width="30"/>
 </td>
 <td align="left" style="border:0" width="24%">
  <b class="club-fixture-team">
   PS BARITO PUTERA
  </b>
 </td>
 <td align="left" style="border:0" width="23%">
  GELORA BUNG TOMO
 </td>
 <td align="center" style="border:0" width="10%">
  <img alt="INDOSIAR" class="club-broadcast-logo" src="https://assets.ileague.id/assets/img/sponsors/INDOSIAR.png"/>
 </td>
 <td align="right" style="border:0" width="5%">
  <i class="fa fa-arrow-right" style="color:#007bff">
  </i>
 </td>
</tr>

In [ ]:
elemen = elemen_gbt[1]

parent = elemen.parent.parent

print("TAG:", parent.name)
print("CLASS:", parent.get("class"))
print("ID:", parent.get("id"))

print("\n--- TEKS ---")
print(parent.get_text(" | ", strip=True))

print("\n--- HTML ---")
print(parent.prettify()[:3000])

TAG: tr
CLASS: ['table-row']
ID: None

--- TEKS ---
PERSEBAYA SURABAYA | FT | 1:1 | PS BARITO PUTERA | GELORA BUNG TOMO

--- HTML ---
<tr class="table-row" height="25" style="background-color: #17a2b8;font-size: 14px">
 <td align="right" style="border:0" width="24%">
  <b class="club-fixture-team">
   PERSEBAYA SURABAYA
  </b>
 </td>
 <td style="border:0;padding:0; margin:0;" width="3%">
  <img alt="" src="https://assets.ileague.id/uploads/images/logo/75/v/50/280.png" style="border: none;" width="30"/>
 </td>
 <td class="club-fixture-score" style="border:0">
  <span class="badge badge-secondary" style="background-color: #17a2b8;color: white;font-size: 15px">
   <span style="font-size:14px;color:#efff00;">
    FT
   </span>
   1:1
  </span>
 </td>
 <td style="border:0;padding:0; margin:0;" width="3%">
  <img alt="" src="https://assets.ileague.id/uploads/images/logo/75/v/50/133.png" style="border: none" width="30"/>
 </td>
 <td align="left" style="border:0" width="24%">
  <b class="club-fixture-team">
   PS BARITO PUTERA
  </b>
 </td>
 <td align="left" style="border:0" width="23%">
  GELORA BUNG TOMO
 </td>
 <td align="center" style="border:0" width="10%">
  <img alt="INDOSIAR" class="club-broadcast-logo" src="https://assets.ileague.id/assets/img/sponsors/INDOSIAR.png"/>
 </td>
 <td align="right" style="border:0" width="5%">
  <i class="fa fa-arrow-right" style="color:#007bff">
  </i>
 </td>
</tr>

In [ ]:
elemen = elemen_gbt[1]
row = elemen.find_parent("tr")

print(row.parent.prettify()[:10000])

<table class="table-striped table-hover table-responsive" id="table-pertandingan" style="border:0;color: black;">
 <tr class="table-row" height="25" style="background-color: #17a2b8;font-size: 14px">
  <td align="right" style="border:0" width="24%">
   <b class="club-fixture-team">
    PERSEBAYA SURABAYA
   </b>
  </td>
  <td style="border:0;padding:0; margin:0;" width="3%">
   <img alt="" src="https://assets.ileague.id/uploads/images/logo/75/v/50/280.png" style="border: none;" width="30"/>
  </td>
  <td class="club-fixture-score" style="border:0">
   <span class="badge badge-secondary" style="background-color: #17a2b8;color: white;font-size: 15px">
    <span style="font-size:14px;color:#efff00;">
     FT
    </span>
    1:1
   </span>
  </td>
  <td style="border:0;padding:0; margin:0;" width="3%">
   <img alt="" src="https://assets.ileague.id/uploads/images/logo/75/v/50/133.png" style="border: none" width="30"/>
  </td>
  <td align="left" style="border:0" width="24%">
   <b class="club-fixture-team">
    PS BARITO PUTERA
   </b>
  </td>
  <td align="left" style="border:0" width="23%">
   GELORA BUNG TOMO
  </td>
  <td align="center" style="border:0" width="10%">
   <img alt="INDOSIAR" class="club-broadcast-logo" src="https://assets.ileague.id/assets/img/sponsors/INDOSIAR.png"/>
  </td>
  <td align="right" style="border:0" width="5%">
   <i class="fa fa-arrow-right" style="color:#007bff">
   </i>
  </td>
 </tr>
</table>

In [ ]:
parent = row.parent

teks_parent = parent.get_text(" | ", strip=True)

print(teks_parent)

PERSEBAYA SURABAYA | FT | 1:1 | PS BARITO PUTERA | GELORA BUNG TOMO

In [ ]:
pola_tanggal = re.compile(
    r'\b\d{1,2}\s+'
    r'(Januari|Februari|Maret|April|Mei|Juni|Juli|Agustus|September|Oktober|November|Desember)'
    r'\s+\d{4}\b',
    re.IGNORECASE
)

tanggal_ditemukan = parent.find_all(
    string=pola_tanggal
)

print("Jumlah tanggal:", len(tanggal_ditemukan))

for t in tanggal_ditemukan:
    print(repr(t.strip()))

Jumlah tanggal: 0

In [ ]:
table = soup.find("table", id="table-pertandingan")

print("Jumlah tabel pertandingan:", len(soup.find_all("table", id="table-pertandingan")))

# Lihat elemen-elemen sebelum tabel
prev_elements = []

current = table
for i in range(10):
    current = current.find_previous()
    if current is not None:
        prev_elements.append(current)

for i, el in enumerate(prev_elements):
    print(f"\n--- PREVIOUS {i} ---")
    print("TAG   :", el.name)
    print("CLASS :", el.get("class"))
    print("ID    :", el.get("id"))
    print("TEXT  :", el.get_text(" ", strip=True)[:500])

Jumlah tabel pertandingan: 34

--- PREVIOUS 0 ---
TAG   : div
CLASS : ['table-cell']
ID    : None
TEXT  : PERSIS SOLO FT 2:3 PERSEBAYA SURABAYA MANAHAN

--- PREVIOUS 1 ---
TAG   : a
CLASS : ['table-row']
ID    : None
TEXT  : PERSIS SOLO FT 2:3 PERSEBAYA SURABAYA MANAHAN

--- PREVIOUS 2 ---
TAG   : div
CLASS : ['col-md-12']
ID    : None
TEXT  : 1 Juli 2023

--- PREVIOUS 3 ---
TAG   : div
CLASS : ['table', 'table-hover', 'table-responsive', 'col-md-12']
ID    : None
TEXT  : 1 Juli 2023 PERSIS SOLO FT 2:3 PERSEBAYA SURABAYA MANAHAN 8 Juli 2023 PERSEBAYA SURABAYA FT 1:1 PS BARITO PUTERA GELORA BUNG TOMO 16 Juli 2023 PSIS SEMARANG FT 2:0 PERSEBAYA SURABAYA JATIDIRI 23 Juli 2023 PERSEBAYA SURABAYA FT 2:2 RANS Nusantara FC GELORA BUNG TOMO 30 Juli 2023 PERSIJA JAKARTA FT 1:0 PERSEBAYA SURABAYA GELORA BUNG KARNO 4 Agustus 2023 PERSEBAYA SURABAYA FT 1:2 PERSIKABO 1973 GELORA BUNG TOMO 8 Agustus 2023 BHAYANGKARA PRESISI LAMPUNG FC FT 1:2 PERSEBAYA SURABAYA PATRIOT CHANDRA

--- PREVIOUS 4 ---
TAG   : div
CLASS : ['tab-pane']
ID    : fixtures
TEXT  : 1 Juli 2023 PERSIS SOLO FT 2:3 PERSEBAYA SURABAYA MANAHAN 8 Juli 2023 PERSEBAYA SURABAYA FT 1:1 PS BARITO PUTERA GELORA BUNG TOMO 16 Juli 2023 PSIS SEMARANG FT 2:0 PERSEBAYA SURABAYA JATIDIRI 23 Juli 2023 PERSEBAYA SURABAYA FT 2:2 RANS Nusantara FC GELORA BUNG TOMO 30 Juli 2023 PERSIJA JAKARTA FT 1:0 PERSEBAYA SURABAYA GELORA BUNG KARNO 4 Agustus 2023 PERSEBAYA SURABAYA FT 1:2 PERSIKABO 1973 GELORA BUNG TOMO 8 Agustus 2023 BHAYANGKARA PRESISI LAMPUNG FC FT 1:2 PERSEBAYA SURABAYA PATRIOT CHANDRA

--- PREVIOUS 5 ---
TAG   : td
CLASS : ['noborder']
ID    : None
TEXT  :

--- PREVIOUS 6 ---
TAG   : tr
CLASS : None
ID    : None
TEXT  :

--- PREVIOUS 7 ---
TAG   : td
CLASS : ['noborder']
ID    : None
TEXT  : Masseur

--- PREVIOUS 8 ---
TAG   : tr
CLASS : None
ID    : None
TEXT  : Masseur

--- PREVIOUS 9 ---
TAG   : td
CLASS : None
ID    : None
TEXT  : YOK SEBASTIAN

In [ ]:
tables = soup.find_all("table", id="table-pertandingan")

print("Jumlah tabel:", len(tables))

for i, table in enumerate(tables[:10]):
    print(f"\n========== TABLE {i} ==========")

    # Isi pertandingan
    row = table.find("tr", class_="table-row")

    if row:
        print("Pertandingan:",
              row.get_text(" | ", strip=True))

    # Elemen sebelumnya
    previous = table.find_previous()

    if previous:
        print("Previous tag  :", previous.name)
        print("Previous class:", previous.get("class"))
        print("Previous text :", previous.get_text(" ", strip=True)[:300])

Jumlah tabel: 34

========== TABLE 0 ==========
Pertandingan: PERSIS SOLO | FT | 2:3 | PERSEBAYA SURABAYA | MANAHAN
Previous tag  : div
Previous class: ['table-cell']
Previous text : PERSIS SOLO FT 2:3 PERSEBAYA SURABAYA MANAHAN

========== TABLE 1 ==========
Pertandingan: PERSEBAYA SURABAYA | FT | 1:1 | PS BARITO PUTERA | GELORA BUNG TOMO
Previous tag  : div
Previous class: ['table-cell']
Previous text : PERSEBAYA SURABAYA FT 1:1 PS BARITO PUTERA GELORA BUNG TOMO

========== TABLE 2 ==========
Pertandingan: PSIS SEMARANG | FT | 2:0 | PERSEBAYA SURABAYA | JATIDIRI
Previous tag  : div
Previous class: ['table-cell']
Previous text : PSIS SEMARANG FT 2:0 PERSEBAYA SURABAYA JATIDIRI

========== TABLE 3 ==========
Pertandingan: PERSEBAYA SURABAYA | FT | 2:2 | RANS Nusantara FC | GELORA BUNG TOMO
Previous tag  : div
Previous class: ['table-cell']
Previous text : PERSEBAYA SURABAYA FT 2:2 RANS Nusantara FC GELORA BUNG TOMO

========== TABLE 4 ==========
Pertandingan: PERSIJA JAKARTA | FT | 1:0 | PERSEBAYA SURABAYA | GELORA BUNG KARNO
Previous tag  : div
Previous class: ['table-cell']
Previous text : PERSIJA JAKARTA FT 1:0 PERSEBAYA SURABAYA GELORA BUNG KARNO

========== TABLE 5 ==========
Pertandingan: PERSEBAYA SURABAYA | FT | 1:2 | PERSIKABO 1973 | GELORA BUNG TOMO
Previous tag  : div
Previous class: ['table-cell']
Previous text : PERSEBAYA SURABAYA FT 1:2 PERSIKABO 1973 GELORA BUNG TOMO

========== TABLE 6 ==========
Pertandingan: BHAYANGKARA PRESISI LAMPUNG FC | FT | 1:2 | PERSEBAYA SURABAYA | PATRIOT CHANDRA BHAGA
Previous tag  : div
Previous class: ['table-cell']
Previous text : BHAYANGKARA PRESISI LAMPUNG FC FT 1:2 PERSEBAYA SURABAYA PATRIOT CHANDRA BHAGA

========== TABLE 7 ==========
Pertandingan: PERSEBAYA SURABAYA | FT | 1:0 | PERSITA | GELORA BUNG TOMO
Previous tag  : div
Previous class: ['table-cell']
Previous text : PERSEBAYA SURABAYA FT 1:0 PERSITA GELORA BUNG TOMO

========== TABLE 8 ==========
Pertandingan: PERSEBAYA SURABAYA | FT | 1:0 | PSM MAKASSAR | GELORA BUNG TOMO
Previous tag  : div
Previous class: ['table-cell']
Previous text : PERSEBAYA SURABAYA FT 1:0 PSM MAKASSAR GELORA BUNG TOMO

========== TABLE 9 ==========
Pertandingan: PSS SLEMAN | FT | 0:0 | PERSEBAYA SURABAYA | MAGUWOHARJO
Previous tag  : div
Previous class: ['table-cell']
Previous text : PSS SLEMAN FT 0:0 PERSEBAYA SURABAYA MAGUWOHARJO

In [ ]:
table = tables[1]  # pertandingan 8 Juli 2023

container = table.find_parent("div", class_="col-md-12")

print(container.prettify()[:5000])

<div class="table table-hover table-responsive col-md-12">
 <div align="left" class="col-md-12" style="margin-top:10px">
  1 Juli 2023
 </div>
 <a class="table-row" href="https://www.ligaindonesiabaru.com/result/detail/BRI_LIGA_1_2023-2024/2023-07-01/PERSIS_SOLO/PERSEBAYA_SURABAYA" target="_blank">
  <div class="table-cell" style="border:0">
   <table class="table-striped table-hover table-responsive" id="table-pertandingan" style="border:0;color: black;">
    <tr class="table-row" height="25" style="background-color: #17a2b8;font-size: 14px">
     <td align="right" style="border:0" width="24%">
      <b class="club-fixture-team">
       PERSIS SOLO
      </b>
     </td>
     <td style="border:0;padding:0; margin:0;" width="3%">
      <img alt="" src="https://assets.ileague.id/uploads/images/logo/75/v/50/67.png" style="border: none;" width="30"/>
     </td>
     <td class="club-fixture-score" style="border:0">
      <span class="badge badge-secondary" style="background-color: #17a2b8;color: white;font-size: 15px">
       <span style="font-size:14px;color:#efff00;">
        FT
       </span>
       2:3
      </span>
     </td>
     <td style="border:0;padding:0; margin:0;" width="3%">
      <img alt="" src="https://assets.ileague.id/uploads/images/logo/75/v/50/280.png" style="border: none" width="30"/>
     </td>
     <td align="left" style="border:0" width="24%">
      <b class="club-fixture-team">
       PERSEBAYA SURABAYA
      </b>
     </td>
     <td align="left" style="border:0" width="23%">
      MANAHAN
     </td>
     <td align="center" style="border:0" width="10%">
      <img alt="INDOSIAR" class="club-broadcast-logo" src="https://assets.ileague.id/assets/img/sponsors/INDOSIAR.png"/>
     </td>
     <td align="right" style="border:0" width="5%">
      <i class="fa fa-arrow-right" style="color:#007bff">
      </i>
     </td>
    </tr>
   </table>
  </div>
 </a>
 <div align="left" class="col-md-12" style="margin-top:10px">
  8 Juli 2023
 </div>
 <a class="table-row" href="https://www.ligaindonesiabaru.com/result/detail/BRI_LIGA_1_2023-2024/2023-07-08/PERSEBAYA_SURABAYA/PS_BARITO_PUTERA" target="_blank">
  <div class="table-cell" style="border:0">
   <table class="table-striped table-hover table-responsive" id="table-pertandingan" style="border:0;color: black;">
    <tr class="table-row" height="25" style="background-color: #17a2b8;font-size: 14px">
     <td align="right" style="border:0" width="24%">
      <b class="club-fixture-team">
       PERSEBAYA SURABAYA
      </b>
     </td>
     <td style="border:0;padding:0; margin:0;" width="3%">
      <img alt="" src="https://assets.ileague.id/uploads/images/logo/75/v/50/280.png" style="border: none;" width="30"/>
     </td>
     <td class="club-fixture-score" style="border:0">
      <span class="badge badge-secondary" style="background-color: #17a2b8;color: white;font-size: 15px">
       <span style="font-size:14px;color:#efff00;">
        FT
       </span>
       1:1
      </span>
     </td>
     <td style="border:0;padding:0; margin:0;" width="3%">
      <img alt="" src="https://assets.ileague.id/uploads/images/logo/75/v/50/133.png" style="border: none" width="30"/>
     </td>
     <td align="left" style="border:0" width="24%">
      <b class="club-fixture-team">
       PS BARITO PUTERA
      </b>
     </td>
     <td align="left" style="border:0" width="23%">
      GELORA BUNG TOMO
     </td>
     <td align="center" style="border:0" width="10%">
      <img alt="INDOSIAR" class="club-broadcast-logo" src="https://assets.ileague.id/assets/img/sponsors/INDOSIAR.png"/>
     </td>
     <td align="right" style="border:0" width="5%">
      <i class="fa fa-arrow-right" style="color:#007bff">
      </i>
     </td>
    </tr>
   </table>
  </div>
 </a>
 <div align="left" class="col-md-12" style="margin-top:10px">
  16 Juli 2023
 </div>
 <a class="table-row" href="https://www.ligaindonesiabaru.com/result/detail/BRI_LIGA_1_2023-2024/2023-07-16/PSIS_SEMARANG/PERSEBAYA_SURABAYA" target="_blank">
  <div class="table-cell" style="border:0">
   <table class="table-striped table-hover table-responsive" id="table-pertandingan" style="border:0;color: black;">
    <tr class="table-row" height="25" style="background-color: #17a2b8;font-size: 14px">
     <td align="right" style="border:0" width="24%">
      <b class="club-fixture-team">
       PSIS SEMARANG
      </b>
     </td>
     <td style="border:0;padding:0; margin:0;" width="3%">
      <img alt="" src="https://assets.ileague.id/uploads/images/logo/75/v/50/20.png" style="border: none;" width="30"/>
     </td>
     <td class="club-fixture-score" style="border:0">
      <span class="badge badge-secondary" style="background-color: #17a2b8;color: white;font-size: 15px">
       <span style="font-size:14px;color:#efff00;">
        FT
       </span>
       2:0
      </span>
     </td>
     <td style="border:0;padding:0; margin:0;" width="3%">
      <img alt="" src="https://assets.ileague.id/uploads/images/logo/75/v/50/280.png"

In [ ]:
fixtures = soup.find("div", id="fixtures")

containers = fixtures.find_all("div", class_="col-md-12")

print("Jumlah container:", len(containers))

for i, container in enumerate(containers[:10]):
    print(f"\n========== {i} ==========")
    print(container.get_text(" | ", strip=True)[:500])

Jumlah container: 35

========== 0 ==========
1 Juli 2023 | PERSIS SOLO | FT | 2:3 | PERSEBAYA SURABAYA | MANAHAN | 8 Juli 2023 | PERSEBAYA SURABAYA | FT | 1:1 | PS BARITO PUTERA | GELORA BUNG TOMO | 16 Juli 2023 | PSIS SEMARANG | FT | 2:0 | PERSEBAYA SURABAYA | JATIDIRI | 23 Juli 2023 | PERSEBAYA SURABAYA | FT | 2:2 | RANS Nusantara FC | GELORA BUNG TOMO | 30 Juli 2023 | PERSIJA JAKARTA | FT | 1:0 | PERSEBAYA SURABAYA | GELORA BUNG KARNO | 4 Agustus 2023 | PERSEBAYA SURABAYA | FT | 1:2 | PERSIKABO 1973 | GELORA BUNG TOMO | 8 Agustus 2023 |

========== 1 ==========
1 Juli 2023

========== 2 ==========
8 Juli 2023

========== 3 ==========
16 Juli 2023

========== 4 ==========
23 Juli 2023

========== 5 ==========
30 Juli 2023

========== 6 ==========
4 Agustus 2023

========== 7 ==========
8 Agustus 2023

========== 8 ==========
12 Agustus 2023

========== 9 ==========
18 Agustus 2023

### 4.3 Ekstraksi tanggal, tim, skor, dan venue

In [ ]:
# Ambil bagian fixtures
fixtures = soup.find("div", id="fixtures")

# Semua tabel pertandingan
tables = fixtures.find_all("table", id="table-pertandingan")

# Container tanggal
containers = fixtures.find_all("div", class_="col-md-12")

# Container pertama adalah wrapper besar, jadi ambil mulai index 1
tanggal_containers = containers[1:]

print("Jumlah pertandingan :", len(tables))
print("Jumlah tanggal      :", len(tanggal_containers))

Jumlah pertandingan : 34
Jumlah tanggal      : 34

In [ ]:
bulan_id = {
    "Januari": 1,
    "Februari": 2,
    "Maret": 3,
    "April": 4,
    "Mei": 5,
    "Juni": 6,
    "Juli": 7,
    "Agustus": 8,
    "September": 9,
    "Oktober": 10,
    "November": 11,
    "Desember": 12
}

def parse_tanggal_id(tanggal):
    """
    Mengubah tanggal seperti:
    '8 Juli 2023'
    menjadi datetime.
    """
    match = re.search(
        r'(\d{1,2})\s+'
        r'(Januari|Februari|Maret|April|Mei|Juni|Juli|Agustus|September|Oktober|November|Desember)'
        r'\s+(\d{4})',
        tanggal,
        re.IGNORECASE
    )

    if not match:
        return pd.NaT

    hari = int(match.group(1))
    bulan = bulan_id[match.group(2).capitalize()]
    tahun = int(match.group(3))

    return pd.Timestamp(year=tahun, month=bulan, day=hari)

In [ ]:
data_liga = []

for i, (table, container) in enumerate(
    zip(tables, tanggal_containers),
    start=1
):

    # -------------------------
    # TANGGAL
    # -------------------------
    tanggal_text = container.get_text(" ", strip=True)
    tanggal = parse_tanggal_id(tanggal_text)

    # -------------------------
    # ROW PERTANDINGAN
    # -------------------------
    row = table.find("tr", class_="table-row")

    if row is None:
        continue

    # -------------------------
    # TIM
    # -------------------------
    tim = row.select("b.club-fixture-team")

    if len(tim) >= 2:
        tim_kandang = tim[0].get_text(" ", strip=True)
        tim_tandang = tim[1].get_text(" ", strip=True)
    else:
        tim_kandang = None
        tim_tandang = None

    # -------------------------
    # SKOR
    # -------------------------
    score_element = row.select_one(".club-fixture-score")

    if score_element:
        score_text = score_element.get_text(" ", strip=True)

        # Ambil skor seperti 1:1, 2:3, 0:0
        match_score = re.search(r'(\d+)\s*:\s*(\d+)', score_text)

        if match_score:
            skor = f"{match_score.group(1)}:{match_score.group(2)}"
        else:
            skor = None
    else:
        skor = None

    # -------------------------
    # VENUE
    # -------------------------
    td = row.find_all("td")

    if len(td) >= 6:
        venue = td[5].get_text(" ", strip=True)
    else:
        venue = None

    data_liga.append({
        "tanggal": tanggal,
        "tim_kandang": tim_kandang,
        "hasil_skor": skor,
        "tim_tandang": tim_tandang,
        "nama_venue": venue
    })

df_liga = pd.DataFrame(data_liga)

print("Ukuran:", df_liga.shape)
df_liga.head(35)

Ukuran: (34, 5)

,tanggal,tim_kandang,hasil_skor,tim_tandang,nama_venue
0,2023-07-01,PERSIS SOLO,2:3,PERSEBAYA SURABAYA,MANAHAN
1,2023-07-08,PERSEBAYA SURABAYA,1:1,PS BARITO PUTERA,GELORA BUNG TOMO
2,2023-07-16,PSIS SEMARANG,2:0,PERSEBAYA SURABAYA,JATIDIRI
3,2023-07-23,PERSEBAYA SURABAYA,2:2,RANS Nusantara FC,GELORA BUNG TOMO
4,2023-07-30,PERSIJA JAKARTA,1:0,PERSEBAYA SURABAYA,GELORA BUNG KARNO
5,2023-08-04,PERSEBAYA SURABAYA,1:2,PERSIKABO 1973,GELORA BUNG TOMO
6,2023-08-08,BHAYANGKARA PRESISI LAMPUNG FC,1:2,PERSEBAYA SURABAYA,PATRIOT CHANDRA BHAGA
7,2023-08-12,PERSEBAYA SURABAYA,1:0,PERSITA,GELORA BUNG TOMO
8,2023-08-18,PERSEBAYA SURABAYA,1:0,PSM MAKASSAR,GELORA BUNG TOMO
9,2023-08-26,PSS SLEMAN,0:0,PERSEBAYA SURABAYA,MAGUWOHARJO
10,2023-09-03,PERSEBAYA SURABAYA,2:1,BORNEO FC SAMARINDA,GELORA BUNG TOMO
11,2023-09-17,MADURA UNITED FC,3:0,PERSEBAYA SURABAYA,GELORA BANGKALAN
12,2023-09-23,PERSEBAYA SURABAYA,3:1,AREMA FC,GELORA BUNG TOMO
13,2023-09-30,DEWA UNITED BANTEN FC,1:1,PERSEBAYA SURABAYA,INDOMILK ARENA
14,2023-10-07,PERSEBAYA SURABAYA,2:3,PERSIB BANDUNG,GELORA BUNG TOMO
15,2023-10-20,BALI UNITED FC,3:1,PERSEBAYA SURABAYA,KAPTEN I WAYAN DIPTA
16,2023-10-27,PERSIK KEDIRI,4:0,PERSEBAYA SURABAYA,BRAWIJAYA
17,2023-11-09,PS BARITO PUTERA,2:0,PERSEBAYA SURABAYA,DEMANG LEHMAN
18,2023-12-01,RANS Nusantara FC,0:0,PERSEBAYA SURABAYA,MAGUWOHARJO
19,2023-12-09,PERSEBAYA SURABAYA,1:1,PERSIJA JAKARTA,GELORA BUNG TOMO
20,2023-12-13,PERSEBAYA SURABAYA,1:1,PERSIS SOLO,GELORA BUNG TOMO
21,2023-12-17,PERSIKABO 1973,1:1,PERSEBAYA SURABAYA,WIBAWA MUKTI
22,2024-01-30,PERSEBAYA SURABAYA,1:1,PSIS SEMARANG,GELORA BUNG TOMO
23,2024-02-04,PERSEBAYA SURABAYA,1:0,BHAYANGKARA PRESISI LAMPUNG FC,GELORA BUNG TOMO
24,2024-02-23,PERSITA,1:1,PERSEBAYA SURABAYA,INDOMILK ARENA
25,2024-02-28,PSM MAKASSAR,0:0,PERSEBAYA SURABAYA,BATAKAN
26,2024-03-03,PERSEBAYA SURABAYA,2:1,PSS SLEMAN,GELORA BUNG TOMO
27,2024-03-07,BORNEO FC SAMARINDA,2:1,PERSEBAYA SURABAYA,BATAKAN
28,2024-03-13,PERSEBAYA SURABAYA,0:0,MADURA UNITED FC,GELORA BUNG TOMO
29,2024-03-27,AREMA FC,0:1,PERSEBAYA SURABAYA,KAPTEN I WAYAN DIPTA
30,2024-04-16,PERSEBAYA SURABAYA,0:3,DEWA UNITED BANTEN FC,GELORA BUNG TOMO
31,2024-04-20,PERSIB BANDUNG,3:1,PERSEBAYA SURABAYA,SI JALAK HARUPAT
32,2024-04-24,PERSEBAYA SURABAYA,0:2,BALI UNITED FC,GELORA BUNG TOMO
33,2024-04-28,PERSEBAYA SURABAYA,2:1,PERSIK KEDIRI,GELORA BUNG TOMO

### 4.4 Membentuk dataset Liga 1 2023/2024

In [ ]:
df_gbt = df_liga[
    df_liga["nama_venue"].str.contains(
        "GELORA BUNG TOMO",
        case=False,
        na=False
    )
].copy()

print("Pertandingan di Gelora Bung Tomo:", len(df_gbt))

df_gbt

Pertandingan di Gelora Bung Tomo: 17

,tanggal,tim_kandang,hasil_skor,tim_tandang,nama_venue
1,2023-07-08,PERSEBAYA SURABAYA,1:1,PS BARITO PUTERA,GELORA BUNG TOMO
3,2023-07-23,PERSEBAYA SURABAYA,2:2,RANS Nusantara FC,GELORA BUNG TOMO
5,2023-08-04,PERSEBAYA SURABAYA,1:2,PERSIKABO 1973,GELORA BUNG TOMO
7,2023-08-12,PERSEBAYA SURABAYA,1:0,PERSITA,GELORA BUNG TOMO
8,2023-08-18,PERSEBAYA SURABAYA,1:0,PSM MAKASSAR,GELORA BUNG TOMO
10,2023-09-03,PERSEBAYA SURABAYA,2:1,BORNEO FC SAMARINDA,GELORA BUNG TOMO
12,2023-09-23,PERSEBAYA SURABAYA,3:1,AREMA FC,GELORA BUNG TOMO
14,2023-10-07,PERSEBAYA SURABAYA,2:3,PERSIB BANDUNG,GELORA BUNG TOMO
19,2023-12-09,PERSEBAYA SURABAYA,1:1,PERSIJA JAKARTA,GELORA BUNG TOMO
20,2023-12-13,PERSEBAYA SURABAYA,1:1,PERSIS SOLO,GELORA BUNG TOMO
22,2024-01-30,PERSEBAYA SURABAYA,1:1,PSIS SEMARANG,GELORA BUNG TOMO
23,2024-02-04,PERSEBAYA SURABAYA,1:0,BHAYANGKARA PRESISI LAMPUNG FC,GELORA BUNG TOMO
26,2024-03-03,PERSEBAYA SURABAYA,2:1,PSS SLEMAN,GELORA BUNG TOMO
28,2024-03-13,PERSEBAYA SURABAYA,0:0,MADURA UNITED FC,GELORA BUNG TOMO
30,2024-04-16,PERSEBAYA SURABAYA,0:3,DEWA UNITED BANTEN FC,GELORA BUNG TOMO
32,2024-04-24,PERSEBAYA SURABAYA,0:2,BALI UNITED FC,GELORA BUNG TOMO
33,2024-04-28,PERSEBAYA SURABAYA,2:1,PERSIK KEDIRI,GELORA BUNG TOMO

In [ ]:
df_event_gbt = df_gbt.copy()

df_event_gbt.insert(
    0,
    "id_event",
    [f"LIGA1-2023-{i:03d}" for i in range(1, len(df_event_gbt) + 1)]
)

df_event_gbt["nama_event"] = "Liga 1 2023/2024"
df_event_gbt["jenis_olahraga"] = "Sepak Bola"
df_event_gbt["tanggal_mulai"] = df_event_gbt["tanggal"]
df_event_gbt["tanggal_selesai"] = df_event_gbt["tanggal"]
df_event_gbt["level_event"] = "Nasional"
df_event_gbt["peserta_tim"] = (
    df_event_gbt["tim_kandang"] + " vs " +
    df_event_gbt["tim_tandang"]
)
df_event_gbt["sumber"] = url

df_event_gbt = df_event_gbt[
    [
        "id_event",
        "nama_event",
        "jenis_olahraga",
        "tanggal_mulai",
        "tanggal_selesai",
        "nama_venue",
        "level_event",
        "peserta_tim",
        "hasil_skor",
        "sumber"
    ]
]

df_event_gbt

,id_event,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
1,LIGA1-2023-001,Liga 1 2023/2024,Sepak Bola,2023-07-08,2023-07-08,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PS BARITO PUTERA,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
3,LIGA1-2023-002,Liga 1 2023/2024,Sepak Bola,2023-07-23,2023-07-23,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs RANS Nusantara FC,2:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
5,LIGA1-2023-003,Liga 1 2023/2024,Sepak Bola,2023-08-04,2023-08-04,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIKABO 1973,1:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
7,LIGA1-2023-004,Liga 1 2023/2024,Sepak Bola,2023-08-12,2023-08-12,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSITA,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
8,LIGA1-2023-005,Liga 1 2023/2024,Sepak Bola,2023-08-18,2023-08-18,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSM MAKASSAR,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
10,LIGA1-2023-006,Liga 1 2023/2024,Sepak Bola,2023-09-03,2023-09-03,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs BORNEO FC SAMARINDA,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
12,LIGA1-2023-007,Liga 1 2023/2024,Sepak Bola,2023-09-23,2023-09-23,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs AREMA FC,3:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
14,LIGA1-2023-008,Liga 1 2023/2024,Sepak Bola,2023-10-07,2023-10-07,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIB BANDUNG,2:3,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
19,LIGA1-2023-009,Liga 1 2023/2024,Sepak Bola,2023-12-09,2023-12-09,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIJA JAKARTA,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
20,LIGA1-2023-010,Liga 1 2023/2024,Sepak Bola,2023-12-13,2023-12-13,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIS SOLO,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
22,LIGA1-2023-011,Liga 1 2023/2024,Sepak Bola,2024-01-30,2024-01-30,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSIS SEMARANG,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
23,LIGA1-2023-012,Liga 1 2023/2024,Sepak Bola,2024-02-04,2024-02-04,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs BHAYANGKARA PRESISI LAMPUNG FC,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
26,LIGA1-2023-013,Liga 1 2023/2024,Sepak Bola,2024-03-03,2024-03-03,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSS SLEMAN,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
28,LIGA1-2023-014,Liga 1 2023/2024,Sepak Bola,2024-03-13,2024-03-13,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs MADURA UNITED FC,0:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
30,LIGA1-2023-015,Liga 1 2023/2024,Sepak Bola,2024-04-16,2024-04-16,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs DEWA UNITED BANTEN FC,0:3,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
32,LIGA1-2023-016,Liga 1 2023/2024,Sepak Bola,2024-04-24,2024-04-24,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs BALI UNITED FC,0:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
33,LIGA1-2023-017,Liga 1 2023/2024,Sepak Bola,2024-04-28,2024-04-28,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIK KEDIRI,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA

In [ ]:
df_event_gbt_2023 = df_event_gbt.copy()

# Rapikan index
df_event_gbt_2023 = df_event_gbt_2023.reset_index(drop=True)

# Pastikan ID event berurutan
df_event_gbt_2023["id_event"] = [
    f"LIGA1-2023-{i:03d}"
    for i in range(1, len(df_event_gbt_2023) + 1)
]

df_event_gbt_2023

,id_event,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
0,LIGA1-2023-001,Liga 1 2023/2024,Sepak Bola,2023-07-08,2023-07-08,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PS BARITO PUTERA,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
1,LIGA1-2023-002,Liga 1 2023/2024,Sepak Bola,2023-07-23,2023-07-23,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs RANS Nusantara FC,2:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
2,LIGA1-2023-003,Liga 1 2023/2024,Sepak Bola,2023-08-04,2023-08-04,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIKABO 1973,1:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
3,LIGA1-2023-004,Liga 1 2023/2024,Sepak Bola,2023-08-12,2023-08-12,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSITA,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
4,LIGA1-2023-005,Liga 1 2023/2024,Sepak Bola,2023-08-18,2023-08-18,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSM MAKASSAR,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
5,LIGA1-2023-006,Liga 1 2023/2024,Sepak Bola,2023-09-03,2023-09-03,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs BORNEO FC SAMARINDA,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
6,LIGA1-2023-007,Liga 1 2023/2024,Sepak Bola,2023-09-23,2023-09-23,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs AREMA FC,3:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
7,LIGA1-2023-008,Liga 1 2023/2024,Sepak Bola,2023-10-07,2023-10-07,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIB BANDUNG,2:3,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
8,LIGA1-2023-009,Liga 1 2023/2024,Sepak Bola,2023-12-09,2023-12-09,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIJA JAKARTA,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
9,LIGA1-2023-010,Liga 1 2023/2024,Sepak Bola,2023-12-13,2023-12-13,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIS SOLO,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
10,LIGA1-2023-011,Liga 1 2023/2024,Sepak Bola,2024-01-30,2024-01-30,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSIS SEMARANG,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
11,LIGA1-2023-012,Liga 1 2023/2024,Sepak Bola,2024-02-04,2024-02-04,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs BHAYANGKARA PRESISI LAMPUNG FC,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
12,LIGA1-2023-013,Liga 1 2023/2024,Sepak Bola,2024-03-03,2024-03-03,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSS SLEMAN,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
13,LIGA1-2023-014,Liga 1 2023/2024,Sepak Bola,2024-03-13,2024-03-13,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs MADURA UNITED FC,0:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
14,LIGA1-2023-015,Liga 1 2023/2024,Sepak Bola,2024-04-16,2024-04-16,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs DEWA UNITED BANTEN FC,0:3,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
15,LIGA1-2023-016,Liga 1 2023/2024,Sepak Bola,2024-04-24,2024-04-24,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs BALI UNITED FC,0:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
16,LIGA1-2023-017,Liga 1 2023/2024,Sepak Bola,2024-04-28,2024-04-28,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIK KEDIRI,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA

In [ ]:
print("Jumlah event :", len(df_event_gbt_2023))
print("Tanggal awal :", df_event_gbt_2023["tanggal_mulai"].min())
print("Tanggal akhir:", df_event_gbt_2023["tanggal_mulai"].max())
print(
    "Venue:",
    df_event_gbt_2023["nama_venue"].unique()
)

Jumlah event : 17
Tanggal awal : 2023-07-08 00:00:00
Tanggal akhir: 2024-04-28 00:00:00
Venue: ['GELORA BUNG TOMO']

### 4.5 Scraping Liga 1 musim 2024/2025

In [ ]:
def scrape_liga1_persebaya(url, nama_event, id_prefix):

    response = requests.get(
        url,
        headers={'User-Agent': 'Mozilla/5.0'},
        timeout=30
    )

    response.raise_for_status()

    soup = BeautifulSoup(response.text, 'html.parser')

    # Bagian fixtures
    fixtures = soup.find("div", id="fixtures")

    if fixtures is None:
        print("Bagian fixtures tidak ditemukan.")
        return pd.DataFrame()

    # Semua tabel pertandingan
    tables = fixtures.find_all(
        "table",
        id="table-pertandingan"
    )

    # Semua container tanggal
    containers = fixtures.find_all(
        "div",
        class_="col-md-12"
    )

    # Container pertama = wrapper seluruh fixtures
    tanggal_containers = containers[1:]

    print("Jumlah pertandingan :", len(tables))
    print("Jumlah tanggal      :", len(tanggal_containers))

    # Cek kesesuaian
    if len(tables) != len(tanggal_containers):
        print("PERINGATAN: jumlah tabel dan tanggal berbeda.")

    # Nama bulan Indonesia
    bulan_id = {
        "Januari": 1,
        "Februari": 2,
        "Maret": 3,
        "April": 4,
        "Mei": 5,
        "Juni": 6,
        "Juli": 7,
        "Agustus": 8,
        "September": 9,
        "Oktober": 10,
        "November": 11,
        "Desember": 12
    }

    def parse_tanggal_id(tanggal):

        match = re.search(
            r'(\d{1,2})\s+'
            r'(Januari|Februari|Maret|April|Mei|Juni|Juli|'
            r'Agustus|September|Oktober|November|Desember)'
            r'\s+(\d{4})',
            tanggal,
            re.IGNORECASE
        )

        if not match:
            return pd.NaT

        hari = int(match.group(1))
        bulan = bulan_id[match.group(2).capitalize()]
        tahun = int(match.group(3))

        return pd.Timestamp(
            year=tahun,
            month=bulan,
            day=hari
        )

    data = []

    # Gunakan pasangan berdasarkan urutan
    for i, (table, container) in enumerate(
        zip(tables, tanggal_containers),
        start=1
    ):

        # -------------------------
        # TANGGAL
        # -------------------------
        tanggal_text = container.get_text(
            " ",
            strip=True
        )

        tanggal = parse_tanggal_id(tanggal_text)

        # -------------------------
        # BARIS PERTANDINGAN
        # -------------------------
        row = table.find(
            "tr",
            class_="table-row"
        )

        if row is None:
            continue

        # -------------------------
        # TIM
        # -------------------------
        tim = row.select(
            "b.club-fixture-team"
        )

        if len(tim) < 2:
            continue

        tim_kandang = tim[0].get_text(
            " ",
            strip=True
        )

        tim_tandang = tim[1].get_text(
            " ",
            strip=True
        )

        # -------------------------
        # SKOR
        # -------------------------
        score_element = row.select_one(
            ".club-fixture-score"
        )

        skor = None

        if score_element:

            score_text = score_element.get_text(
                " ",
                strip=True
            )

            match_score = re.search(
                r'(\d+)\s*:\s*(\d+)',
                score_text
            )

            if match_score:
                skor = (
                    f"{match_score.group(1)}:"
                    f"{match_score.group(2)}"
                )

        # -------------------------
        # VENUE
        # -------------------------
        td = row.find_all("td")

        venue = None

        if len(td) >= 6:
            venue = td[5].get_text(
                " ",
                strip=True
            )

        # -------------------------
        # SIMPAN
        # -------------------------
        data.append({
            "id_event": f"{id_prefix}-{i:03d}",
            "nama_event": nama_event,
            "jenis_olahraga": "Sepak Bola",
            "tanggal_mulai": tanggal,
            "tanggal_selesai": tanggal,
            "nama_venue": venue,
            "level_event": "Nasional",
            "peserta_tim": (
                f"{tim_kandang} vs "
                f"{tim_tandang}"
            ),
            "hasil_skor": skor,
            "sumber": url
        })

    df = pd.DataFrame(data)

    # Hanya pertandingan di Gelora Bung Tomo
    df = df[
        df["nama_venue"].str.contains(
            "GELORA BUNG TOMO",
            case=False,
            na=False
        )
    ].copy()

    # Reset index
    df = df.reset_index(drop=True)

    # ID ulang khusus event GBT
    df["id_event"] = [
        f"{id_prefix}-{i:03d}"
        for i in range(1, len(df) + 1)
    ]

    return df

In [ ]:
url_2024 = (
    "https://www.ligaindonesiabaru.com/"
    "clubs/single/BRI_LIGA_1_2024-25/"
    "PERSEBAYA_SURABAYA"
)

df_2024 = scrape_liga1_persebaya(
    url_2024,
    "Liga 1 2024/2025",
    "LIGA1-2024"
)

print("Jumlah event GBT:", len(df_2024))

df_2024

Jumlah pertandingan : 34
Jumlah tanggal      : 34
Jumlah event GBT: 17

,id_event,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
0,LIGA1-2024-001,Liga 1 2024/2025,Sepak Bola,2024-08-11,2024-08-11,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSS SLEMAN,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
1,LIGA1-2024-002,Liga 1 2024/2025,Sepak Bola,2024-08-23,2024-08-23,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PS BARITO PUTERA,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
2,LIGA1-2024-003,Liga 1 2024/2025,Sepak Bola,2024-09-18,2024-09-18,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIS SOLO,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
3,LIGA1-2024-004,Liga 1 2024/2025,Sepak Bola,2024-09-27,2024-09-27,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs DEWA UNITED BANTEN FC,0:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
4,LIGA1-2024-005,Liga 1 2024/2025,Sepak Bola,2024-10-23,2024-10-23,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSM MAKASSAR,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
5,LIGA1-2024-006,Liga 1 2024/2025,Sepak Bola,2024-11-22,2024-11-22,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIJA JAKARTA,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
6,LIGA1-2024-007,Liga 1 2024/2025,Sepak Bola,2024-12-07,2024-12-07,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs AREMA FC,3:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
7,LIGA1-2024-008,Liga 1 2024/2025,Sepak Bola,2024-12-11,2024-12-11,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIK KEDIRI,4:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
8,LIGA1-2024-009,Liga 1 2024/2025,Sepak Bola,2024-12-20,2024-12-20,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs BORNEO FC SAMARINDA,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
9,LIGA1-2024-010,Liga 1 2024/2025,Sepak Bola,2025-01-17,2025-01-17,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs JAVA UNITED FC,0:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
10,LIGA1-2024-011,Liga 1 2024/2025,Sepak Bola,2025-01-31,2025-01-31,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSITA,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
11,LIGA1-2024-012,Liga 1 2024/2025,Sepak Bola,2025-02-15,2025-02-15,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSBS BIAK,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
12,LIGA1-2024-013,Liga 1 2024/2025,Sepak Bola,2025-03-01,2025-03-01,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIB BANDUNG,4:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
13,LIGA1-2024-014,Liga 1 2024/2025,Sepak Bola,2025-03-12,2025-03-12,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSIS SEMARANG,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
14,LIGA1-2024-015,Liga 1 2024/2025,Sepak Bola,2025-04-20,2025-04-20,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs MADURA UNITED FC,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
15,LIGA1-2024-016,Liga 1 2024/2025,Sepak Bola,2025-05-11,2025-05-11,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs SEMEN PADANG FC,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
16,LIGA1-2024-017,Liga 1 2024/2025,Sepak Bola,2025-05-23,2025-05-23,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs BALI UNITED FC,1:3,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA

### 4.6 Menggabungkan data Liga 1

In [ ]:
df_event_liga1 = pd.concat(
    [df_event_gbt_2023, df_2024],
    ignore_index=True
)

df_event_liga1

,id_event,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
0,LIGA1-2023-001,Liga 1 2023/2024,Sepak Bola,2023-07-08,2023-07-08,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PS BARITO PUTERA,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
1,LIGA1-2023-002,Liga 1 2023/2024,Sepak Bola,2023-07-23,2023-07-23,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs RANS Nusantara FC,2:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
2,LIGA1-2023-003,Liga 1 2023/2024,Sepak Bola,2023-08-04,2023-08-04,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIKABO 1973,1:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
3,LIGA1-2023-004,Liga 1 2023/2024,Sepak Bola,2023-08-12,2023-08-12,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSITA,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
4,LIGA1-2023-005,Liga 1 2023/2024,Sepak Bola,2023-08-18,2023-08-18,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSM MAKASSAR,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
5,LIGA1-2023-006,Liga 1 2023/2024,Sepak Bola,2023-09-03,2023-09-03,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs BORNEO FC SAMARINDA,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
6,LIGA1-2023-007,Liga 1 2023/2024,Sepak Bola,2023-09-23,2023-09-23,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs AREMA FC,3:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
7,LIGA1-2023-008,Liga 1 2023/2024,Sepak Bola,2023-10-07,2023-10-07,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIB BANDUNG,2:3,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
8,LIGA1-2023-009,Liga 1 2023/2024,Sepak Bola,2023-12-09,2023-12-09,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIJA JAKARTA,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
9,LIGA1-2023-010,Liga 1 2023/2024,Sepak Bola,2023-12-13,2023-12-13,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIS SOLO,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
10,LIGA1-2023-011,Liga 1 2023/2024,Sepak Bola,2024-01-30,2024-01-30,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSIS SEMARANG,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
11,LIGA1-2023-012,Liga 1 2023/2024,Sepak Bola,2024-02-04,2024-02-04,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs BHAYANGKARA PRESISI LAMPUNG FC,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
12,LIGA1-2023-013,Liga 1 2023/2024,Sepak Bola,2024-03-03,2024-03-03,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSS SLEMAN,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
13,LIGA1-2023-014,Liga 1 2023/2024,Sepak Bola,2024-03-13,2024-03-13,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs MADURA UNITED FC,0:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
14,LIGA1-2023-015,Liga 1 2023/2024,Sepak Bola,2024-04-16,2024-04-16,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs DEWA UNITED BANTEN FC,0:3,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
15,LIGA1-2023-016,Liga 1 2023/2024,Sepak Bola,2024-04-24,2024-04-24,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs BALI UNITED FC,0:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
16,LIGA1-2023-017,Liga 1 2023/2024,Sepak Bola,2024-04-28,2024-04-28,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIK KEDIRI,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
17,LIGA1-2024-001,Liga 1 2024/2025,Sepak Bola,2024-08-11,2024-08-11,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSS SLEMAN,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
18,LIGA1-2024-002,Liga 1 2024/2025,Sepak Bola,2024-08-23,2024-08-23,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PS BARITO PUTERA,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
19,LIGA1-2024-003,Liga 1 2024/2025,Sepak Bola,2024-09-18,2024-09-18,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIS SOLO,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
20,LIGA1-2024-004,Liga 1 2024/2025,Sepak Bola,2024-09-27,2024-09-27,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs DEWA UNITED BANTEN FC,0:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
21,LIGA1-2024-005,Liga 1 2024/2025,Sepak Bola,2024-10-23,2024-10-23,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSM MAKASSAR,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
22,LIGA1-2024-006,Liga 1 2024/2025,Sepak Bola,2024-11-22,2024-11-22,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIJA JAKARTA,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
23,LIGA1-2024-007,Liga 1 2024/2025,Sepak Bola,2024-12-07,2024-12-07,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs AREMA FC,3:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
24,LIGA1-2024-008,Liga 1 2024/2025,Sepak Bola,2024-12-11,2024-12-11,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIK KEDIRI,4:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
25,LIGA1-2024-009,Liga 1 2024/2025,Sepak Bola,2024-12-20,2024-12-20,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs BORNEO FC SAMARINDA,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
26,LIGA1-2024-010,Liga 1 2024/2025,Sepak Bola,2025-01-17,2025-01-17,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs JAVA UNITED FC,0:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
27,LIGA1-2024-011,Liga 1 2024/2025,Sepak Bola,2025-01-31,2025-01-31,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSITA,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
28,LIGA1-2024-012,Liga 1 2024/2025,Sepak Bola,2025-02-15,2025-02-15,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSBS BIAK,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
29,LIGA1-2024-013,Liga 1 2024/2025,Sepak Bola,2025-03-01,2025-03-01,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PERSIB BANDUNG,4:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
30,LIGA1-2024-014,Liga 1 2024/2025,Sepak Bola,2025-03-12,2025-03-12,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs PSIS SEMARANG,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
31,LIGA1-2024-015,Liga 1 2024/2025,Sepak Bola,2025-04-20,2025-04-20,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs MADURA UNITED FC,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
32,LIGA1-2024-016,Liga 1 2024/2025,Sepak Bola,2025-05-11,2025-05-11,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs SEMEN PADANG FC,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
33,LIGA1-2024-017,Liga 1 2024/2025,Sepak Bola,2025-05-23,2025-05-23,GELORA BUNG TOMO,Nasional,PERSEBAYA SURABAYA vs BALI UNITED FC,1:3,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA

In [ ]:
print("Total event Liga 1 GBT:", len(df_event_liga1))

print("\nPer musim:")
print(
    df_event_liga1["nama_event"].value_counts()
)

print("\nPer venue:")
print(
    df_event_liga1["nama_venue"].value_counts()
)

print("\nPer tahun:")
print(
    df_event_liga1["tanggal_mulai"]
    .dt.year
    .value_counts()
    .sort_index()
)

Total event Liga 1 GBT: 34

Per musim:
nama_event
Liga 1 2023/2024    17
Liga 1 2024/2025    17
Name: count, dtype: int64

Per venue:
nama_venue
GELORA BUNG TOMO    34
Name: count, dtype: int64

Per tahun:
tanggal_mulai
2023    10
2024    16
2025     8
Name: count, dtype: int64

# 5. Scraping Event Piala AFF U-19

## AFF U-19

In [ ]:
import urllib3

urllib3.disable_warnings(
    urllib3.exceptions.InsecureRequestWarning
)

### 5.1 Mengambil halaman sumber AFF U-19

In [ ]:
url_aff = "https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indonesia-767c10.html"

response = requests.get(
    url_aff,
    headers={'User-Agent': 'Mozilla/5.0'},
    timeout=30,
    verify=False
)

response.raise_for_status()

soup = BeautifulSoup(response.text, 'html.parser')

print("Status:", response.status_code)
print("Judul:", soup.title.get_text(strip=True))

Status: 200
Judul: Hasil Lengkap, Klasemen, dan Top Skor Piala AFF U-19 2024 Indonesia

In [ ]:
teks = soup.get_text(" ", strip=True)

print(teks[:5000])

Hasil Lengkap, Klasemen, dan Top Skor Piala AFF U-19 2024 Indonesia HOME TRENDING EROPA LIGA INGGRIS LIGA ITALIA LIGA SPANYOL BUNDESLIGA LIGA CHAMPIONS LIGA EROPA LAINNYA DUNIA PIALA DUNIA PIALA EROPA AMERIKA LATIN ASIA LAINNYA INDONESIA BRI SUPER LEAGUE TIM NASIONAL BOLATAINMENT JADWAL & SKOR SKOR TERKINI JADWAL PERTANDINGAN JADWAL TV KLASEMEN TOPSKOR RAGAM EDITORIAL VIDEO GALERI SPORT BASKET BULU TANGKIS TENIS OTOMOTIF VOLI LAINNYA Advertisement Bola.net > Tim Nasional Hasil Lengkap, Klasemen, dan Top Skor Piala AFF U-19 2024 Indonesia Editor Dimas Ardi Prasetya Diperbarui: 29 Juli 2024, 21:50 WIB Diterbitkan: 29 Juli 2024, 21:50 WIB Jens Raven sukses membobol gawang Timnas Thailand U-19 di final Piala AFF u-19 2024 (c) Bola.net/Bagaskara Lazuardi Bola.net - Berikut hasil lengkap Piala AFF U-19 , klasemen, dan top skor Piala AFF U-19 2024 yang digelar di Surabaya, Indonesia. Turnamen 2024 ASEAN U-19 Boys Championship ini digelar mulai 17 - 29 Juli 2024 dan disiarkan live di SCTV dan live streaming di Vidio . Timnas Indonesia U-19 juara! Skuad asuhan Indra Sjafri sukses menjadi juara Piala AFF U-19 setelah di laga final lawan Thailand U-19 di Stadion Gelora Bung Tomo, Senin (29/07/2024), mereka menang dengan skor 1-0. Satu-satunya gol di laga itu dihasilkan oleh Jens Raven. Dengan demikian, Timnas Indonesia U-19 mengulang kesuksesan pada tahun 2013 silam. Sementara itu Thailand U-19 menduduki peringkat kedua. Peringkat ketiga diduduki oleh Timnas Australia U-19. Berikut hasil lengkap Piala AFF U-19, klasemen, dan top skor Piala AFF U-19 2024 Bolaneters. Hasil, Jadwal, Klasemen, dan Top Skor Piala Dunia 2026 Jadwal Lengkap, Hasil, Klasemen, dan Top Skor Piala AFF 2026 Daftar Tim Peserta Piala AFF U-19 2024 Skuad Timnas Indonesia U-19 untuk Piala AFF U-19 2024 (c) Bola.net/Ari Prayoga Turnamen Piala AFF U-19 2024 akan digelar di Surabaya. Dua stadion megah, yaitu Stadion Gelora Bung Tomo dan Stadion Gelora 10 November, telah disiapkan untuk menjadi saksi kemeriahan turnamen ini. Sebanyak 12 negara akan bertanding dalam turnamen ini, di mana mereka akan dibagi menjadi tiga grup yang masing-masing terdiri dari empat tim. Australia Brunei Darussalam Filipina Indonesia Kamboja Laos Malaysia Myanmar Singapura Thailand Timor Leste Vietnam Pertarungan sengit akan berlangsung untuk memperebutkan dua tempat di babak semifinal, di mana hanya juara grup dan satu runner-up terbaik yang akan melaju ke babak selanjutnya. Jadwal, Hasil Lengkap, Top Skor, & Klasemen Piala Dunia U-17 2025 Jadwal Lengkap, Hasil, Klasemen, dan Top Skor BRI Super League 2025/2026 Pertandingan Selanjutnya Pembagian Grup Piala AFF U-19 Piala AFF U-19 - Hasil Undian AFF ASEAN Championship U-19. (c) Bola.com/Adreanus Titus Sebagai tuan rumah, Indonesia berada di Grup A. Pasukan Indra Sjafri itu akan bersaing dengan Timor Leste, Kamboja, dan Filipina. Berikut adalah daftar negara, pembagian grup, dan jadwal lengkap Piala AFF U-19 selengkapnya. Grup A : Timnas Indonesia, Timor Leste, Kamboja, Filipina Grup B : Laos, Vietnam, Myanmar, Australia Grup C : Malaysia, Thailand, Singapura, Brunei Darussalam Jadwal, Hasil Lengkap, Klasemen, dan Top Skor Kualifikasi Piala Asia U-23 2026 Hasil Lengkap, Klasemen, dan Top Skor Piala AFF U-23 2025 Hasil dan Klasemen Grup A Piala AFF U-19 2024 Iqbal Gwijangge merayakan golnya ke gawang Timnas Filipina U-19, Rabu (17/7/2024) (c) Bola.com/Aditya Wani Klasemen Grup A Piala AFF U-19 2024. (c) Wikipedia 17 Juli 2024 Timor Leste 3-2 Kamboja (Vabio Cannavaro 33', Alexandro Bahkito 36', Luis Ribeiro 38'; Sorm Borith 54', Chheang Kimsong 60') Indonesia 6-0 Filipina (Arlyansyah Abdulmanan 12', 50', Iqbal Gwijangge 21', 43', Kadek Arel 29', Jens Raven 87') 20 Juli 2024 Filipina 2-0 Timor Leste (Otu Bisong 11', 60') Kamboja 0-2 Indonesia (Kadek Arel 71', Iqbal 86') 23 Juli 2024 19:30 WIB - Indonesia 6-2 Timor Leste, Gelora Bung Tomo (Jens Raven 18', 26', Figo Dennis 45+1', Kadek Arel 51', Arkhan Kaka 53', Kafiatur Risky 56'; Ricardo Bianco 23', Alexandro Bahkito 86') 19:30 WIB - Kamboja 1-0 Filipina, Gelora 10 November (Eav Sovannara 11') Daftar Top Skor Piala AFF U-23 2025, Siapa Terdepan? Daftar Lengkap Penghargaan Piala Presiden 2025: Bordin Phala Pemain Terbaik, Oxford United Borong Dua Penghargaan Hasil dan Klasemen Grup B Piala AFF U-19 2024 Laga Australia U-19 vs Vietnam U-19 di Piala AFF U-19 2024 (c) Bola/Richard Andreas Klasemen akhir Grup B Piala AFF U-19 2024. (c) Wikipedia 18 Juli 2024 15:00 WIB - Laos 0-6 Australia, Gelora 10 November (Ario Sulemani 16', 25', Marcus Younis 45+4', 73', Jake Najdovski 89', 90+4') 19:30 WIB - Vietnam 1-1 Myanmar, Gelora 10 November (Hoang Quang Dung 69'; Phyo Pyae Sone 60') 21 Juli 2024 15:00 WIB - Australia 6-2 Vietnam, Gelora 10 November (Jaje Najdovski 19', 40', 66'; Arion Sulemani 49', Zane Helweh 74', Luke Vickery 90+7'; Hoang Quang Dung 57', Nguyen Bao Long 86' -pen) 19:30 WIB - Myanmar 1-1 Laos, Gelora 10 November (Shine Wanna Aung 17'; Phanthavong 82') 24 Juli 2024 19:30 WI

In [ ]:
# Cari semua elemen yang mengandung venue target
elemen_venue = soup.find_all(
    string=re.compile(
        r'Gelora Bung Tomo|Gelora 10 November',
        re.IGNORECASE
    )
)

print("Jumlah elemen:", len(elemen_venue))

for i, elemen in enumerate(elemen_venue):
    print(i, "=>", elemen.strip())

Jumlah elemen: 18
0 => juara! Skuad asuhan Indra Sjafri sukses menjadi juara Piala AFF U-19 setelah di laga final lawan Thailand U-19 di Stadion Gelora Bung Tomo, Senin (29/07/2024), mereka menang dengan skor 1-0.
1 => Turnamen Piala AFF U-19 2024 akan digelar di Surabaya. Dua stadion megah, yaitu Stadion Gelora Bung Tomo dan Stadion Gelora 10 November, telah disiapkan untuk menjadi saksi kemeriahan turnamen ini.
2 => 19:30 WIB - Indonesia 6-2 Timor Leste, Gelora Bung Tomo
3 => 19:30 WIB - Kamboja 1-0 Filipina, Gelora 10 November
4 => 15:00 WIB - Laos 0-6 Australia, Gelora 10 November
5 => 19:30 WIB - Vietnam 1-1 Myanmar, Gelora 10 November
6 => 15:00 WIB - Australia 6-2 Vietnam, Gelora 10 November
7 => 19:30 WIB - Myanmar 1-1 Laos, Gelora 10 November
8 => 19:30 WIB - Laos 1-4 Vietnam, Gelora Bung Tomo
9 => 19:30 WIB - Myanmar 0-1 Australia, Gelora 10 November
10 => 15:00 WIB - Malaysia 11-0 Brunei, Gelora 10 November
11 => 19:30 WIB - Thailand 2-1 Singapura, Gelora 10 November
12 => 15:00 WIB - Brunei 0-6 Thailand, Gelora 10 November
13 => 19:30 WIB - Singapura 0-5 Malaysia, Gelora 10 November
14 => 19:30 WIB - Malaysia 1-1 Thailand, Gelora Bung Tomo
15 => 19:30 WIB - Singapura vs Brunei, Gelora 10 November
16 => 15.00 WIB Australia 0-1 Thailand, Gelora Bung Tomo
17 => 19.30 WIB Indonesia 1-0 Malaysia, Gelora Bung Tomo

In [ ]:
print(elemen_venue[0].parent.prettify()[:5000])

<p>
 <a href="https://www.bola.net/tag/timnas-indonesia-u-19/">
  Timnas Indonesia U-19
 </a>
 juara! Skuad asuhan Indra Sjafri sukses menjadi juara Piala AFF U-19 setelah di laga final lawan Thailand U-19 di Stadion Gelora Bung Tomo, Senin (29/07/2024), mereka menang dengan skor 1-0.
</p>

In [ ]:
teks_artikel = soup.get_text(
    "\n",
    strip=True
)

print(teks_artikel[:10000])

Hasil Lengkap, Klasemen, dan Top Skor Piala AFF U-19 2024 Indonesia
HOME
TRENDING
EROPA
LIGA INGGRIS
LIGA ITALIA
LIGA SPANYOL
BUNDESLIGA
LIGA CHAMPIONS
LIGA EROPA
LAINNYA
DUNIA
PIALA DUNIA
PIALA EROPA
AMERIKA LATIN
ASIA
LAINNYA
INDONESIA
BRI SUPER LEAGUE
TIM NASIONAL
BOLATAINMENT
JADWAL & SKOR
SKOR TERKINI
JADWAL PERTANDINGAN
JADWAL TV
KLASEMEN
TOPSKOR
RAGAM
EDITORIAL
VIDEO
GALERI
SPORT
BASKET
BULU TANGKIS
TENIS
OTOMOTIF
VOLI
LAINNYA
Advertisement
Bola.net
>
Tim Nasional
Hasil Lengkap, Klasemen, dan Top Skor Piala AFF U-19 2024 Indonesia
Editor
Dimas Ardi Prasetya
Diperbarui:
29 Juli 2024, 21:50 WIB
Diterbitkan:
29 Juli 2024, 21:50 WIB
Jens Raven sukses membobol gawang Timnas Thailand U-19 di final Piala AFF u-19 2024 (c) Bola.net/Bagaskara Lazuardi
Bola.net -
Berikut hasil lengkap
Piala AFF U-19
, klasemen, dan
top skor
Piala AFF U-19 2024
yang digelar di Surabaya, Indonesia. Turnamen 2024 ASEAN U-19 Boys Championship ini digelar mulai 17 - 29 Juli 2024 dan disiarkan live di
SCTV
dan live streaming di
Vidio
.
Timnas Indonesia U-19
juara! Skuad asuhan Indra Sjafri sukses menjadi juara Piala AFF U-19 setelah di laga final lawan Thailand U-19 di Stadion Gelora Bung Tomo, Senin (29/07/2024), mereka menang dengan skor 1-0.
Satu-satunya gol di laga itu dihasilkan oleh Jens Raven. Dengan demikian, Timnas Indonesia U-19 mengulang kesuksesan pada tahun 2013 silam.
Sementara itu Thailand U-19 menduduki peringkat kedua. Peringkat ketiga diduduki oleh Timnas Australia U-19.
Berikut hasil lengkap Piala AFF U-19, klasemen, dan top skor Piala AFF U-19 2024 Bolaneters.
Hasil, Jadwal, Klasemen, dan Top Skor Piala Dunia 2026
Jadwal Lengkap, Hasil, Klasemen, dan Top Skor Piala AFF 2026
Daftar Tim Peserta Piala AFF U-19 2024
Skuad Timnas Indonesia U-19 untuk Piala AFF U-19 2024 (c) Bola.net/Ari Prayoga
Turnamen Piala AFF U-19 2024 akan digelar di Surabaya. Dua stadion megah, yaitu Stadion Gelora Bung Tomo dan Stadion Gelora 10 November, telah disiapkan untuk menjadi saksi kemeriahan turnamen ini.
Sebanyak 12 negara akan bertanding dalam turnamen ini, di mana mereka akan dibagi menjadi tiga grup yang masing-masing terdiri dari empat tim.
Australia
Brunei Darussalam
Filipina
Indonesia
Kamboja
Laos
Malaysia
Myanmar
Singapura
Thailand
Timor Leste
Vietnam
Pertarungan sengit akan berlangsung untuk memperebutkan dua tempat di babak semifinal, di mana hanya juara grup dan satu runner-up terbaik yang akan melaju ke babak selanjutnya.
Jadwal, Hasil Lengkap, Top Skor, & Klasemen Piala Dunia U-17 2025
Jadwal Lengkap, Hasil, Klasemen, dan Top Skor BRI Super League 2025/2026
Pertandingan Selanjutnya
Pembagian Grup Piala AFF U-19
Piala AFF U-19 - Hasil Undian AFF ASEAN Championship U-19. (c) Bola.com/Adreanus Titus
Sebagai tuan rumah, Indonesia berada di Grup A. Pasukan Indra Sjafri itu akan bersaing dengan Timor Leste, Kamboja, dan Filipina. Berikut adalah daftar negara, pembagian grup, dan jadwal lengkap Piala AFF U-19 selengkapnya.
Grup A
: Timnas Indonesia, Timor Leste, Kamboja, Filipina
Grup B
: Laos, Vietnam, Myanmar, Australia
Grup C
: Malaysia, Thailand, Singapura, Brunei Darussalam
Jadwal, Hasil Lengkap, Klasemen, dan Top Skor Kualifikasi Piala Asia U-23 2026
Hasil Lengkap, Klasemen, dan Top Skor Piala AFF U-23 2025
Hasil dan Klasemen Grup A Piala AFF U-19 2024
Iqbal Gwijangge merayakan golnya ke gawang Timnas Filipina U-19, Rabu (17/7/2024) (c) Bola.com/Aditya Wani
Klasemen Grup A Piala AFF U-19 2024. (c) Wikipedia
17 Juli 2024
Timor Leste 3-2 Kamboja
(Vabio Cannavaro 33', Alexandro Bahkito 36', Luis Ribeiro 38'; Sorm Borith 54', Chheang Kimsong 60')
Indonesia 6-0 Filipina
(Arlyansyah Abdulmanan 12', 50', Iqbal Gwijangge 21', 43', Kadek Arel 29', Jens Raven 87')
20 Juli 2024
Filipina 2-0 Timor Leste
(Otu Bisong 11', 60')
Kamboja 0-2 Indonesia
(Kadek Arel 71', Iqbal 86')
23 Juli 2024
19:30 WIB - Indonesia 6-2 Timor Leste, Gelora Bung Tomo
(Jens Raven 18', 26', Figo Dennis 45+1', Kadek Arel 51', Arkhan Kaka 53', Kafiatur Risky 56'; Ricardo Bianco 23', Alexandro Bahkito 86')
19:30 WIB - Kamboja 1-0 Filipina, Gelora 10 November
(Eav Sovannara 11')
Daftar Top Skor Piala AFF U-23 2025, Siapa Terdepan?
Daftar Lengkap Penghargaan Piala Presiden 2025: Bordin Phala Pemain Terbaik, Oxford United Borong Dua Penghargaan
Hasil dan Klasemen Grup B Piala AFF U-19 2024
Laga Australia U-19 vs Vietnam U-19 di Piala AFF U-19 2024 (c) Bola/Richard Andreas
Klasemen akhir Grup B Piala AFF U-19 2024. (c) Wikipedia
18 Juli 2024
15:00 WIB - Laos 0-6 Australia, Gelora 10 November
(Ario Sulemani 16', 25', Marcus Younis 45+4', 73', Jake Najdovski 89', 90+4')
19:30 WIB - Vietnam 1-1 Myanmar, Gelora 10 November
(Hoang Quang Dung 69'; Phyo Pyae Sone 60')
21 Juli 2024
15:00 WIB - Australia 6-2 Vietnam, Gelora 10 November
(Jaje Najdovski 19', 40', 66'; Arion Sulemani 49', Zane Helweh 74', Luke Vickery 90+7'; Hoang Quang Dung 57', Nguyen Bao Long 86' -pen)
19:30 WIB - Myanmar 1-1 Laos, Gelora 10 November
(Shine Wanna Aung 17'; Phanthavong 82')
24 Juli 2024
19:30 WIB - Laos 1-4 Vietnam, Gelora Bung Tomo
(Peter Phanthavong 27'; Nguyen Hoanh Anh 3', Hoang Quang Dung 22', Nguyen Cong Phurong 77', Phung Van Nam 83')
19:30 WIB - Myanmar 0-1 Australia, Gelora 10 November
(Medin Memeti 34')
Hasil Lengkap, Klasemen, dan Top Skor BRI Liga 1 2024/2025
Striker Brasil jadi Spesialisasi Top Skor BRI Liga 1: Alex Martins di Atas Angin Perkuat Dominasi
Hasil dan Klasemen Grup C Piala AFF U-19 2024
Timnas Malaysia U-19 ketika bermain di Piala AFF U-19 2024 (c) FAM Malaysia
Klasemen Grup C Piala AFF U-19 2024. (c) Wikipedia
19 Juli 2024
15:00 WIB - Malaysia 11-0 Brunei, Gelora 10 November
(G. Pavithran 2', 43', Abid Safaraz 14', 16', 81', Danish Hakimi 25', Haykal Danish 42', Izzat Syahir 53' -pen, Amir Farhan 67', Zamirul Hakim 75', Shafizan Arshad 83')
19:30 WIB - Thailand 2-1 Singapura, Gelora 10 November
(Pongsakorn Sangkhasopa 79', Pikanet Loahawiat 85'; Sahu Gharf 26')
22 Juli 2024
15:00 WIB - Brunei 0-6 Thailand, Gelora 10 November
(Pakawat Taengoakson 8', Paripan Wongsa 27', Caelan Ryan 45', Pikanet Laohawiwat 45+4', Pitipong Wongbut 79', Rattapoom Pankejohn 90')
19:30 WIB - Singapura 0-5 Malaysia, Gelora 10 November
(Ridzwan Rosli 7', Naim Zainudin 12', Pavihtran Gunalan 45+1', Faris Danish Asrul 73', Izzat Syahir 82', Abid Safaraz Bin Rozaidi 84' -KM)
25 Juli 2024
19:30 WIB - Malaysia 1-1 Thailand, Gelora Bung Tomo
(Pavithran Gunalan 48' -pen; Caelan Ryan 4')
19:30 WIB - Singapura vs Brunei, Gelora 10 November
(Sahoo Garv 19', 40' -pen)
Jadwal Knock Out Piala AFF U-19 2024
Bracket fase knock out Piala AFF U-19 2024. (c)
Semifinal Piala AFF U-19 2024
27 Juli 2024
15.00 WIB Australia 0-1 Thailand, Gelora Bung Tomo
(Dylan Leonard 13' -BD)
19.30 WIB Indonesia 1-0 Malaysia, Gelora Bung Tomo
(Alfharezzi Buffon 78')
Perebutan Peringkat Tiga Piala AFF U-19 2024
29 Juli 2024
15.00 Australia 1-1 Malaysia
(5-3 pen)
(Marcus Younis 28'; Jake Najdovski 73' -BD)
Final Piala AFF U-19 2024
29 Juli 2024
19.30 WIB Thailand 0-1 Indonesia
(Jens Raven 17')
Top Skor Piala AFF U-19 2024
Berikut adalah daftar pencetak gol terbanyak Piala AFF U-19 selengkapnya:
5 Gol: Jake Najdovski (Australia)
4 Gol: Pavithran Gunalan (Malaysia), Jens Raven (Indonesia)
3 Gol: Abid Safaraz (Malaysia), Iqbal Gwijangge (Indonesia), Kadek Arel (Indonesia), Hoang Quang Dung (Vietnam), Sahoo Garv (Singapura), Arion Sulemani (Australia), Marcus Younis (Australia)
2 Gol: Arlyansyah Abdulmanan (Indonesia), Otu Bisong (Filipina), Pikanet Laohawiwat (Thailand), Izzat Syahir (Malaysia), Alexandro Bahkito (Timor Leste), Peter Phanthavong (Laos), Caelan Ryan (Thailand)
1 Gol: Vabio Cannavaro (Timor Leste), Luis Ribeiro (Timor Leste), Sorm Borith (Kamboja), Chheang Kimsong (Kamboja), Phyo Pyae Sone (Myanmar), Danish Hakimi (Malaysia), Haykal Danish (Malaysia), Amir Farhan (Malaysia), Zamirul Hakim (Malaysia), Shafizan Arshad (Malaysia), Pongsakorn Sangkhasopa (Thailand), Arion Sulemani (Australia), Zane Helweh (Australia), Luke Vickery (Australia), Nguyen Bao Long (Vietnam), Shine Wanna Aung (Myanmar), Pakawat Taengoakson (Thailand), Paripan Wongsa (Thailand), Pitipong Wongbut (Thailand), Rattapoom Pankejohn (Thailand), Ridzwan Rosli (Malaysia), Naim Zainudin (Malaysia), Faris Danish Asrul (Malaysia), Figo Dennis (Indonesia), Arkhan Kaka (Indonesia), Kafiatur Risky (Indonesia), Ricardo Bianco (Timor Leste), Eav Sovannara (Kamboja), Nguyen Hoanh Anh (Vietnam), Nguyen Cong Phurong (Vietnam), Phung Van Nam (Vietnam), Medin Memeti (Australia), Alfharezzi Buffon (Indonesia)
*Hak siar Piala AFF U-19 2024 dipegang oleh Emtek Group. Laga-laga Piala AFF U-19, termasuk Timnas Indonesia, akan disiarkan di SCTV dan live streming Vidio.
Top Skor
Timnas Indonesia U-19
Piala Aff U-19
Sctv
Klasemen Piala Aff U-19
Sportybase
Vidio
Piala Aff U-19 2024
Jadwal Piala Aff U-19 2024
Hasil Piala Aff U-19
Klasemen Piala Aff U-19 2024
Advertisement
Berita Terkait
Tim Nasional
6 Oktober 2026 15:53
Janji John Herdman usai Juara FIFA ASEAN Cup 2026: Cari Lebih Banyak Pemain Berbakat di BRI Super League!
Tim Nasional
6 Oktober 2026 15:15
Kalah dari Timnas Indoensia, Thailand Siap Buat Perhitungan di Piala Asia 2027
Liga Inggris
6 Oktober 2026 15:00
Real Madrid Bakal Lepas Endrick, MU Siaga Satu!
Tim Nasional
6 Oktober 2026 14:45
Cara John Herdman Memotivasi Timnas Indonesia Jelang Final FIFA ASEAN Cup: Korek Lagi Luka Lama!
Tim Nasional
6 Oktober 2026 14:30
Juara FIFA ASEAN Cup, Timnas Indonesia Berhutang Budi pada John Herdman
LATEST UPDATE
Liga Inggris
6 Oktober 2026 18:16
10 Pemain Manchester United dalam Sorotan Jelang Lawan Tottenham: Michael Carrick Hadapi Krisis Kebugaran
Liga Inggris
6 Oktober 2026 18:08
Barcelona dan Real Madrid Siapkan Tawaran Gaji 'XXL' untuk JJ Gabriel
Bola Indonesia
6 Oktober 2026 17:42
Jadwal Maut Menanti Persija Jakarta di Oktober 2026
Bola Indonesia
6 Oktober 2026 17:39
Persik Kediri Punya Misi Besar: Jadi Tim Pertama yang Menodai Kesempurnaan Madura United
Bola Indonesia
6 Oktober 2026 17:31
Luka Menalo Siap Bawa Persib Bandun

### 5.2 Mengekstrak jadwal dan pertandingan AFF

In [ ]:
bulan_id = {
    "Januari": 1,
    "Februari": 2,
    "Maret": 3,
    "April": 4,
    "Mei": 5,
    "Juni": 6,
    "Juli": 7,
    "Agustus": 8,
    "September": 9,
    "Oktober": 10,
    "November": 11,
    "Desember": 12
}

# Pola tanggal
pola_tanggal = re.compile(
    r'(\d{1,2})\s+'
    r'(Januari|Februari|Maret|April|Mei|Juni|Juli|Agustus|'
    r'September|Oktober|November|Desember)'
    r'\s+(\d{4})',
    re.IGNORECASE
)

tanggal_ditemukan = list(
    pola_tanggal.finditer(teks_artikel)
)

print("Jumlah tanggal ditemukan:", len(tanggal_ditemukan))

for x in tanggal_ditemukan:
    print(x.group(0))

Jumlah tanggal ditemukan: 40
29 Juli 2024
29 Juli 2024
29 Juli 2024
17 Juli 2024
20 Juli 2024
23 Juli 2024
18 Juli 2024
21 Juli 2024
24 Juli 2024
19 Juli 2024
22 Juli 2024
25 Juli 2024
27 Juli 2024
29 Juli 2024
29 Juli 2024
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
6 Oktober 2026
5 Oktober 2026
5 Oktober 2026

In [ ]:
data_aff = []

# Hanya tanggal pertandingan AFF U-19 2024
for i, match_tanggal in enumerate(tanggal_ditemukan):

    tanggal_text = match_tanggal.group(0)

    # Ambil bagian teks sampai sebelum tanggal berikutnya
    posisi_awal = match_tanggal.end()

    if i + 1 < len(tanggal_ditemukan):
        posisi_akhir = tanggal_ditemukan[i + 1].start()
    else:
        posisi_akhir = len(teks_artikel)

    blok = teks_artikel[posisi_awal:posisi_akhir]

    # Cari baris pertandingan yang menggunakan GBT / G10N
    pertandingan = re.findall(
        r'(\d{1,2}:\d{2})\s*WIB\s*-\s*'
        r'([^,\n]+?),\s*'
        r'(Gelora Bung Tomo|Gelora 10 November)',
        blok,
        re.IGNORECASE
    )

    for jam, pertandingan_text, venue in pertandingan:

        # Pisahkan nama tim dan skor
        skor_match = re.search(
            r'^(.+?)\s+(\d+)\s*[-:]\s*(\d+)\s+(.+)$',
            pertandingan_text.strip()
        )

        if not skor_match:
            continue

        tim_home = skor_match.group(1).strip()
        skor_home = skor_match.group(2)
        skor_away = skor_match.group(3)
        tim_away = skor_match.group(4).strip()

        # Konversi tanggal
        d, m, y = re.match(
            r'(\d{1,2})\s+(\w+)\s+(\d{4})',
            tanggal_text
        ).groups()

        tanggal = pd.Timestamp(
            year=int(y),
            month=bulan_id[m.capitalize()],
            day=int(d)
        )

        # Standarisasi nama venue
        if "Bung Tomo" in venue:
            venue_standar = "Gelora Bung Tomo"
        else:
            venue_standar = "Gelora 10 Nopember"

        data_aff.append({
            "nama_event": "Piala AFF U-19 2024",
            "jenis_olahraga": "Sepak Bola",
            "tanggal_mulai": tanggal,
            "tanggal_selesai": tanggal,
            "nama_venue": venue_standar,
            "level_event": "Internasional",
            "peserta_tim": f"{tim_home} vs {tim_away}",
            "hasil_skor": f"{skor_home}:{skor_away}",
            "sumber": url_aff
        })

df_aff = pd.DataFrame(data_aff)

display(df_aff)

,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
0,Piala AFF U-19 2024,Sepak Bola,2024-07-23,2024-07-23,Gelora Bung Tomo,Internasional,Indonesia vs Timor Leste,6:2,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
1,Piala AFF U-19 2024,Sepak Bola,2024-07-23,2024-07-23,Gelora 10 Nopember,Internasional,Kamboja vs Filipina,1:0,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
2,Piala AFF U-19 2024,Sepak Bola,2024-07-18,2024-07-18,Gelora 10 Nopember,Internasional,Laos vs Australia,0:6,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
3,Piala AFF U-19 2024,Sepak Bola,2024-07-18,2024-07-18,Gelora 10 Nopember,Internasional,Vietnam vs Myanmar,1:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
4,Piala AFF U-19 2024,Sepak Bola,2024-07-21,2024-07-21,Gelora 10 Nopember,Internasional,Australia vs Vietnam,6:2,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
5,Piala AFF U-19 2024,Sepak Bola,2024-07-21,2024-07-21,Gelora 10 Nopember,Internasional,Myanmar vs Laos,1:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
6,Piala AFF U-19 2024,Sepak Bola,2024-07-24,2024-07-24,Gelora Bung Tomo,Internasional,Laos vs Vietnam,1:4,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
7,Piala AFF U-19 2024,Sepak Bola,2024-07-24,2024-07-24,Gelora 10 Nopember,Internasional,Myanmar vs Australia,0:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
8,Piala AFF U-19 2024,Sepak Bola,2024-07-19,2024-07-19,Gelora 10 Nopember,Internasional,Malaysia vs Brunei,11:0,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
9,Piala AFF U-19 2024,Sepak Bola,2024-07-19,2024-07-19,Gelora 10 Nopember,Internasional,Thailand vs Singapura,2:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
10,Piala AFF U-19 2024,Sepak Bola,2024-07-22,2024-07-22,Gelora 10 Nopember,Internasional,Brunei vs Thailand,0:6,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
11,Piala AFF U-19 2024,Sepak Bola,2024-07-22,2024-07-22,Gelora 10 Nopember,Internasional,Singapura vs Malaysia,0:5,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
12,Piala AFF U-19 2024,Sepak Bola,2024-07-25,2024-07-25,Gelora Bung Tomo,Internasional,Malaysia vs Thailand,1:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...

In [ ]:
df_aff.insert(
    0,
    "id_event",
    [
        f"AFF19-{i:03d}"
        for i in range(1, len(df_aff) + 1)
    ]
)

df_aff

,id_event,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
0,AFF19-001,Piala AFF U-19 2024,Sepak Bola,2024-07-23,2024-07-23,Gelora Bung Tomo,Internasional,Indonesia vs Timor Leste,6:2,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
1,AFF19-002,Piala AFF U-19 2024,Sepak Bola,2024-07-23,2024-07-23,Gelora 10 Nopember,Internasional,Kamboja vs Filipina,1:0,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
2,AFF19-003,Piala AFF U-19 2024,Sepak Bola,2024-07-18,2024-07-18,Gelora 10 Nopember,Internasional,Laos vs Australia,0:6,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
3,AFF19-004,Piala AFF U-19 2024,Sepak Bola,2024-07-18,2024-07-18,Gelora 10 Nopember,Internasional,Vietnam vs Myanmar,1:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
4,AFF19-005,Piala AFF U-19 2024,Sepak Bola,2024-07-21,2024-07-21,Gelora 10 Nopember,Internasional,Australia vs Vietnam,6:2,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
5,AFF19-006,Piala AFF U-19 2024,Sepak Bola,2024-07-21,2024-07-21,Gelora 10 Nopember,Internasional,Myanmar vs Laos,1:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
6,AFF19-007,Piala AFF U-19 2024,Sepak Bola,2024-07-24,2024-07-24,Gelora Bung Tomo,Internasional,Laos vs Vietnam,1:4,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
7,AFF19-008,Piala AFF U-19 2024,Sepak Bola,2024-07-24,2024-07-24,Gelora 10 Nopember,Internasional,Myanmar vs Australia,0:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
8,AFF19-009,Piala AFF U-19 2024,Sepak Bola,2024-07-19,2024-07-19,Gelora 10 Nopember,Internasional,Malaysia vs Brunei,11:0,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
9,AFF19-010,Piala AFF U-19 2024,Sepak Bola,2024-07-19,2024-07-19,Gelora 10 Nopember,Internasional,Thailand vs Singapura,2:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
10,AFF19-011,Piala AFF U-19 2024,Sepak Bola,2024-07-22,2024-07-22,Gelora 10 Nopember,Internasional,Brunei vs Thailand,0:6,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
11,AFF19-012,Piala AFF U-19 2024,Sepak Bola,2024-07-22,2024-07-22,Gelora 10 Nopember,Internasional,Singapura vs Malaysia,0:5,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
12,AFF19-013,Piala AFF U-19 2024,Sepak Bola,2024-07-25,2024-07-25,Gelora Bung Tomo,Internasional,Malaysia vs Thailand,1:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...

In [ ]:
print("Jumlah pertandingan:", len(df_aff))

print("\nPer venue:")
display(
    df_aff["nama_venue"]
    .value_counts()
    .reset_index()
    .rename(columns={
        "nama_venue": "venue",
        "count": "jumlah_event"
    })
)

Jumlah pertandingan: 13

Per venue:

                venue  jumlah_event
0  Gelora 10 Nopember            10
1    Gelora Bung Tomo             3

### 5.3 Merapikan dan memvalidasi dataset AFF

In [ ]:
# Urutkan berdasarkan tanggal dan venue
df_aff = df_aff.sort_values(
    ['tanggal_mulai', 'nama_venue', 'peserta_tim']
).reset_index(drop=True)

# Buat ulang ID setelah sorting
df_aff['id_event'] = [
    f"AFF19-{i:03d}"
    for i in range(1, len(df_aff) + 1)
]

# Susun kolom sesuai data_event
df_aff = df_aff[
    [
        'id_event',
        'nama_event',
        'jenis_olahraga',
        'tanggal_mulai',
        'tanggal_selesai',
        'nama_venue',
        'level_event',
        'peserta_tim',
        'hasil_skor',
        'sumber'
    ]
]

display(df_aff)

,id_event,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
0,AFF19-001,Piala AFF U-19 2024,Sepak Bola,2024-07-18,2024-07-18,Gelora 10 Nopember,Internasional,Laos vs Australia,0:6,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
1,AFF19-002,Piala AFF U-19 2024,Sepak Bola,2024-07-18,2024-07-18,Gelora 10 Nopember,Internasional,Vietnam vs Myanmar,1:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
2,AFF19-003,Piala AFF U-19 2024,Sepak Bola,2024-07-19,2024-07-19,Gelora 10 Nopember,Internasional,Malaysia vs Brunei,11:0,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
3,AFF19-004,Piala AFF U-19 2024,Sepak Bola,2024-07-19,2024-07-19,Gelora 10 Nopember,Internasional,Thailand vs Singapura,2:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
4,AFF19-005,Piala AFF U-19 2024,Sepak Bola,2024-07-21,2024-07-21,Gelora 10 Nopember,Internasional,Australia vs Vietnam,6:2,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
5,AFF19-006,Piala AFF U-19 2024,Sepak Bola,2024-07-21,2024-07-21,Gelora 10 Nopember,Internasional,Myanmar vs Laos,1:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
6,AFF19-007,Piala AFF U-19 2024,Sepak Bola,2024-07-22,2024-07-22,Gelora 10 Nopember,Internasional,Brunei vs Thailand,0:6,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
7,AFF19-008,Piala AFF U-19 2024,Sepak Bola,2024-07-22,2024-07-22,Gelora 10 Nopember,Internasional,Singapura vs Malaysia,0:5,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
8,AFF19-009,Piala AFF U-19 2024,Sepak Bola,2024-07-23,2024-07-23,Gelora 10 Nopember,Internasional,Kamboja vs Filipina,1:0,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
9,AFF19-010,Piala AFF U-19 2024,Sepak Bola,2024-07-23,2024-07-23,Gelora Bung Tomo,Internasional,Indonesia vs Timor Leste,6:2,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
10,AFF19-011,Piala AFF U-19 2024,Sepak Bola,2024-07-24,2024-07-24,Gelora 10 Nopember,Internasional,Myanmar vs Australia,0:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
11,AFF19-012,Piala AFF U-19 2024,Sepak Bola,2024-07-24,2024-07-24,Gelora Bung Tomo,Internasional,Laos vs Vietnam,1:4,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
12,AFF19-013,Piala AFF U-19 2024,Sepak Bola,2024-07-25,2024-07-25,Gelora Bung Tomo,Internasional,Malaysia vs Thailand,1:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...

In [ ]:
df_event = pd.concat(
    [
        df_event_liga1,
        df_aff
    ],
    ignore_index=True
)

print("Total event:", len(df_event))

display(
    df_event[
        [
            'nama_event',
            'tanggal_mulai',
            'nama_venue',
            'peserta_tim',
            'hasil_skor'
        ]
    ]
)

Total event: 47

,nama_event,tanggal_mulai,nama_venue,peserta_tim,hasil_skor
0,Liga 1 2023/2024,2023-07-08,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PS BARITO PUTERA,1:1
1,Liga 1 2023/2024,2023-07-23,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs RANS Nusantara FC,2:2
2,Liga 1 2023/2024,2023-08-04,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PERSIKABO 1973,1:2
3,Liga 1 2023/2024,2023-08-12,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PERSITA,1:0
4,Liga 1 2023/2024,2023-08-18,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PSM MAKASSAR,1:0
5,Liga 1 2023/2024,2023-09-03,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs BORNEO FC SAMARINDA,2:1
6,Liga 1 2023/2024,2023-09-23,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs AREMA FC,3:1
7,Liga 1 2023/2024,2023-10-07,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PERSIB BANDUNG,2:3
8,Liga 1 2023/2024,2023-12-09,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PERSIJA JAKARTA,1:1
9,Liga 1 2023/2024,2023-12-13,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PERSIS SOLO,1:1
10,Liga 1 2023/2024,2024-01-30,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PSIS SEMARANG,1:1
11,Liga 1 2023/2024,2024-02-04,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs BHAYANGKARA PRESISI LAMPUNG FC,1:0
12,Liga 1 2023/2024,2024-03-03,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PSS SLEMAN,2:1
13,Liga 1 2023/2024,2024-03-13,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs MADURA UNITED FC,0:0
14,Liga 1 2023/2024,2024-04-16,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs DEWA UNITED BANTEN FC,0:3
15,Liga 1 2023/2024,2024-04-24,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs BALI UNITED FC,0:2
16,Liga 1 2023/2024,2024-04-28,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PERSIK KEDIRI,2:1
17,Liga 1 2024/2025,2024-08-11,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PSS SLEMAN,1:0
18,Liga 1 2024/2025,2024-08-23,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PS BARITO PUTERA,2:1
19,Liga 1 2024/2025,2024-09-18,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PERSIS SOLO,2:1
20,Liga 1 2024/2025,2024-09-27,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs DEWA UNITED BANTEN FC,0:0
21,Liga 1 2024/2025,2024-10-23,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PSM MAKASSAR,1:1
22,Liga 1 2024/2025,2024-11-22,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PERSIJA JAKARTA,2:1
23,Liga 1 2024/2025,2024-12-07,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs AREMA FC,3:2
24,Liga 1 2024/2025,2024-12-11,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PERSIK KEDIRI,4:1
25,Liga 1 2024/2025,2024-12-20,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs BORNEO FC SAMARINDA,2:1
26,Liga 1 2024/2025,2025-01-17,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs JAVA UNITED FC,0:2
27,Liga 1 2024/2025,2025-01-31,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PERSITA,1:1
28,Liga 1 2024/2025,2025-02-15,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PSBS BIAK,1:0
29,Liga 1 2024/2025,2025-03-01,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PERSIB BANDUNG,4:1
30,Liga 1 2024/2025,2025-03-12,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs PSIS SEMARANG,1:1
31,Liga 1 2024/2025,2025-04-20,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs MADURA UNITED FC,1:0
32,Liga 1 2024/2025,2025-05-11,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs SEMEN PADANG FC,1:1
33,Liga 1 2024/2025,2025-05-23,GELORA BUNG TOMO,PERSEBAYA SURABAYA vs BALI UNITED FC,1:3
34,Piala AFF U-19 2024,2024-07-18,Gelora 10 Nopember,Laos vs Australia,0:6
35,Piala AFF U-19 2024,2024-07-18,Gelora 10 Nopember,Vietnam vs Myanmar,1:1
36,Piala AFF U-19 2024,2024-07-19,Gelora 10 Nopember,Malaysia vs Brunei,11:0
37,Piala AFF U-19 2024,2024-07-19,Gelora 10 Nopember,Thailand vs Singapura,2:1
38,Piala AFF U-19 2024,2024-07-21,Gelora 10 Nopember,Australia vs Vietnam,6:2
39,Piala AFF U-19 2024,2024-07-21,Gelora 10 Nopember,Myanmar vs Laos,1:1
40,Piala AFF U-19 2024,2024-07-22,Gelora 10 Nopember,Brunei vs Thailand,0:6
41,Piala AFF U-19 2024,2024-07-22,Gelora 10 Nopember,Singapura vs Malaysia,0:5
42,Piala AFF U-19 2024,2024-07-23,Gelora 10 Nopember,Kamboja vs Filipina,1:0
43,Piala AFF U-19 2024,2024-07-23,Gelora Bung Tomo,Indonesia vs Timor Leste,6:2
44,Piala AFF U-19 2024,2024-07-24,Gelora 10 Nopember,Myanmar vs Australia,0:1
45,Piala AFF U-19 2024,2024-07-24,Gelora Bung Tomo,Laos vs Vietnam,1:4
46,Piala AFF U-19 2024,2024-07-25,Gelora Bung Tomo,Malaysia vs Thailand,1:1

In [ ]:
print("Event per kompetisi:")
display(
    df_event['nama_event']
    .value_counts()
    .reset_index()
    .rename(columns={
        'nama_event': 'event',
        'count': 'jumlah_event'
    })
)

print("\nEvent per venue:")
display(
    df_event['nama_venue']
    .value_counts()
    .reset_index()
    .rename(columns={
        'nama_venue': 'venue',
        'count': 'jumlah_event'
    })
)

Event per kompetisi:

                 event  jumlah_event
0     Liga 1 2023/2024            17
1     Liga 1 2024/2025            17
2  Piala AFF U-19 2024            13

Event per venue:

                venue  jumlah_event
0    GELORA BUNG TOMO            34
1  Gelora 10 Nopember            10
2    Gelora Bung Tomo             3

In [ ]:
# Standardisasi nama venue
mapping_nama_venue = {
    'GELORA BUNG TOMO': 'Gelora Bung Tomo',
    'Gelora Bung Tomo': 'Gelora Bung Tomo',
    'Gelora 10 Nopember': 'Gelora 10 Nopember',
    'Gelora 10 November': 'Gelora 10 Nopember'
}

df_event['nama_venue'] = (
    df_event['nama_venue']
    .str.strip()
    .replace(mapping_nama_venue)
)

# Cek event per kompetisi
event_per_kompetisi = (
    df_event
    .groupby('nama_event')
    .size()
    .reset_index(name='jumlah_event')
    .sort_values('jumlah_event', ascending=False)
    .reset_index(drop=True)
)

display(event_per_kompetisi)

# Cek event per venue
event_per_venue = (
    df_event
    .groupby('nama_venue')
    .size()
    .reset_index(name='jumlah_event')
    .sort_values('jumlah_event', ascending=False)
    .reset_index(drop=True)
)

display(event_per_venue)

            nama_event  jumlah_event
0     Liga 1 2023/2024            17
1     Liga 1 2024/2025            17
2  Piala AFF U-19 2024            13

           nama_venue  jumlah_event
0    Gelora Bung Tomo            37
1  Gelora 10 Nopember            10

### 5.4 Pemeriksaan lanjutan dan standardisasi data AFF

## AFF U-19

In [ ]:
url_aff = (
    "https://www.bola.net/tim_nasional/"
    "hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indonesia-767c10.html"
)

response = requests.get(
    url_aff,
    headers={'User-Agent': 'Mozilla/5.0'},
    timeout=30,
    verify=False
)

response.raise_for_status()

soup = BeautifulSoup(response.text, 'html.parser')

# Ambil seluruh teks halaman
lines = [
    x.strip()
    for x in soup.get_text("\n", strip=True).splitlines()
    if x.strip()
]

print("Jumlah baris teks:", len(lines))

Jumlah baris teks: 282

In [ ]:
# Tampilkan semua baris yang mengandung nama venue
for i, line in enumerate(lines):
    if re.search(
        r'Gelora Bung Tomo|Gelora 10 November',
        line,
        re.IGNORECASE
    ):
        print(f"{i}: {line}")

62: juara! Skuad asuhan Indra Sjafri sukses menjadi juara Piala AFF U-19 setelah di laga final lawan Thailand U-19 di Stadion Gelora Bung Tomo, Senin (29/07/2024), mereka menang dengan skor 1-0.
70: Turnamen Piala AFF U-19 2024 akan digelar di Surabaya. Dua stadion megah, yaitu Stadion Gelora Bung Tomo dan Stadion Gelora 10 November, telah disiapkan untuk menjadi saksi kemeriahan turnamen ini.
113: 19:30 WIB - Indonesia 6-2 Timor Leste, Gelora Bung Tomo
115: 19:30 WIB - Kamboja 1-0 Filipina, Gelora 10 November
123: 15:00 WIB - Laos 0-6 Australia, Gelora 10 November
125: 19:30 WIB - Vietnam 1-1 Myanmar, Gelora 10 November
128: 15:00 WIB - Australia 6-2 Vietnam, Gelora 10 November
130: 19:30 WIB - Myanmar 1-1 Laos, Gelora 10 November
133: 19:30 WIB - Laos 1-4 Vietnam, Gelora Bung Tomo
135: 19:30 WIB - Myanmar 0-1 Australia, Gelora 10 November
143: 15:00 WIB - Malaysia 11-0 Brunei, Gelora 10 November
145: 19:30 WIB - Thailand 2-1 Singapura, Gelora 10 November
148: 15:00 WIB - Brunei 0-6 Thailand, Gelora 10 November
150: 19:30 WIB - Singapura 0-5 Malaysia, Gelora 10 November
153: 19:30 WIB - Malaysia 1-1 Thailand, Gelora Bung Tomo
155: 19:30 WIB - Singapura vs Brunei, Gelora 10 November
161: 15.00 WIB Australia 0-1 Thailand, Gelora Bung Tomo
163: 19.30 WIB Indonesia 1-0 Malaysia, Gelora Bung Tomo

In [ ]:
bulan_id = {
    "Januari": 1,
    "Februari": 2,
    "Maret": 3,
    "April": 4,
    "Mei": 5,
    "Juni": 6,
    "Juli": 7,
    "Agustus": 8,
    "September": 9,
    "Oktober": 10,
    "November": 11,
    "Desember": 12
}

# Format:
# 19:30 WIB - Indonesia 6-2 Timor Leste, Gelora Bung Tomo
# 15.00 WIB Australia 0-1 Thailand, Gelora Bung Tomo
# 19.30 WIB Indonesia 1-0 Malaysia, Gelora Bung Tomo
# 19:30 WIB - Singapura vs Brunei, Gelora 10 November

pola_match = re.compile(
    r'^(?:'
    r'\d{1,2}[:.]\d{2}\s*WIB\s*-?\s*'
    r')?'
    r'(.+?)'
    r'(?:\s+(\d+)\s*[-:]\s*(\d+))?'
    r',\s*'
    r'(Gelora Bung Tomo|Gelora 10 November)'
    r'\s*$',
    re.IGNORECASE
)

data_aff = []

for i, line in enumerate(lines):

    match = pola_match.match(line)

    if not match:
        continue

    peserta = match.group(1).strip()

    skor_home = match.group(2)
    skor_away = match.group(3)

    if skor_home and skor_away:
        hasil_skor = f"{skor_home}:{skor_away}"

        # Buang skor dari peserta
        peserta = re.sub(
            r'\s+\d+\s*[-:]\s*\d+\s*$',
            '',
            peserta
        ).strip()
    else:
        hasil_skor = None

    venue = match.group(4).strip()

    # Cari tanggal terdekat sebelum pertandingan
    tanggal = None

    for j in range(i - 1, -1, -1):

        match_tanggal = re.search(
            r'^(\d{1,2})\s+'
            r'(Januari|Februari|Maret|April|Mei|Juni|Juli|Agustus|'
            r'September|Oktober|November|Desember)'
            r'\s+(\d{4})$',
            lines[j],
            re.IGNORECASE
        )

        if match_tanggal:

            hari = int(match_tanggal.group(1))

            bulan = bulan_id[
                match_tanggal.group(2).capitalize()
            ]

            tahun = int(match_tanggal.group(3))

            tanggal = pd.Timestamp(
                year=tahun,
                month=bulan,
                day=hari
            )

            break

    data_aff.append({
        'nama_event': 'Piala AFF U-19 2024',
        'jenis_olahraga': 'Sepak Bola',
        'tanggal_mulai': tanggal,
        'tanggal_selesai': tanggal,
        'nama_venue': venue,
        'level_event': 'Internasional',
        'peserta_tim': peserta,
        'hasil_skor': hasil_skor,
        'sumber': url_aff
    })

df_aff = pd.DataFrame(data_aff)

print("Jumlah pertandingan hasil scraping:", len(df_aff))

display(df_aff)

Jumlah pertandingan hasil scraping: 16

,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
0,Piala AFF U-19 2024,Sepak Bola,2024-07-23,2024-07-23,Gelora Bung Tomo,Internasional,Indonesia 6-2 Timor Leste,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
1,Piala AFF U-19 2024,Sepak Bola,2024-07-23,2024-07-23,Gelora 10 November,Internasional,Kamboja 1-0 Filipina,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
2,Piala AFF U-19 2024,Sepak Bola,2024-07-18,2024-07-18,Gelora 10 November,Internasional,Laos 0-6 Australia,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
3,Piala AFF U-19 2024,Sepak Bola,2024-07-18,2024-07-18,Gelora 10 November,Internasional,Vietnam 1-1 Myanmar,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
4,Piala AFF U-19 2024,Sepak Bola,2024-07-21,2024-07-21,Gelora 10 November,Internasional,Australia 6-2 Vietnam,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
5,Piala AFF U-19 2024,Sepak Bola,2024-07-21,2024-07-21,Gelora 10 November,Internasional,Myanmar 1-1 Laos,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
6,Piala AFF U-19 2024,Sepak Bola,2024-07-24,2024-07-24,Gelora Bung Tomo,Internasional,Laos 1-4 Vietnam,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
7,Piala AFF U-19 2024,Sepak Bola,2024-07-24,2024-07-24,Gelora 10 November,Internasional,Myanmar 0-1 Australia,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
8,Piala AFF U-19 2024,Sepak Bola,2024-07-19,2024-07-19,Gelora 10 November,Internasional,Malaysia 11-0 Brunei,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
9,Piala AFF U-19 2024,Sepak Bola,2024-07-19,2024-07-19,Gelora 10 November,Internasional,Thailand 2-1 Singapura,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
10,Piala AFF U-19 2024,Sepak Bola,2024-07-22,2024-07-22,Gelora 10 November,Internasional,Brunei 0-6 Thailand,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
11,Piala AFF U-19 2024,Sepak Bola,2024-07-22,2024-07-22,Gelora 10 November,Internasional,Singapura 0-5 Malaysia,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
12,Piala AFF U-19 2024,Sepak Bola,2024-07-25,2024-07-25,Gelora Bung Tomo,Internasional,Malaysia 1-1 Thailand,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
13,Piala AFF U-19 2024,Sepak Bola,2024-07-25,2024-07-25,Gelora 10 November,Internasional,Singapura vs Brunei,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
14,Piala AFF U-19 2024,Sepak Bola,2024-07-27,2024-07-27,Gelora Bung Tomo,Internasional,Australia 0-1 Thailand,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
15,Piala AFF U-19 2024,Sepak Bola,2024-07-27,2024-07-27,Gelora Bung Tomo,Internasional,Indonesia 1-0 Malaysia,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...

In [ ]:
pola_final = re.compile(
    r'final.*?lawan\s+Thailand\s+U-19.*?'
    r'(?:Stadion\s+)?Gelora Bung Tomo.*?'
    r'(\d+)-(\d+)',
    re.IGNORECASE | re.DOTALL
)

match_final = pola_final.search(teks_artikel)

if match_final:

    skor_final = (
        f"{match_final.group(1)}:"
        f"{match_final.group(2)}"
    )

    data_final = {
        'nama_event': 'Piala AFF U-19 2024',
        'jenis_olahraga': 'Sepak Bola',
        'tanggal_mulai': pd.Timestamp('2024-07-29'),
        'tanggal_selesai': pd.Timestamp('2024-07-29'),
        'nama_venue': 'Gelora Bung Tomo',
        'level_event': 'Internasional',
        'peserta_tim': 'Indonesia U-19 vs Thailand U-19',
        'hasil_skor': skor_final,
        'sumber': url_aff
    }

    df_aff = pd.concat(
        [
            df_aff,
            pd.DataFrame([data_final])
        ],
        ignore_index=True
    )

print("Jumlah event AFF setelah final:", len(df_aff))

display(df_aff)

Jumlah event AFF setelah final: 17

,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
0,Piala AFF U-19 2024,Sepak Bola,2024-07-23,2024-07-23,Gelora Bung Tomo,Internasional,Indonesia 6-2 Timor Leste,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
1,Piala AFF U-19 2024,Sepak Bola,2024-07-23,2024-07-23,Gelora 10 November,Internasional,Kamboja 1-0 Filipina,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
2,Piala AFF U-19 2024,Sepak Bola,2024-07-18,2024-07-18,Gelora 10 November,Internasional,Laos 0-6 Australia,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
3,Piala AFF U-19 2024,Sepak Bola,2024-07-18,2024-07-18,Gelora 10 November,Internasional,Vietnam 1-1 Myanmar,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
4,Piala AFF U-19 2024,Sepak Bola,2024-07-21,2024-07-21,Gelora 10 November,Internasional,Australia 6-2 Vietnam,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
5,Piala AFF U-19 2024,Sepak Bola,2024-07-21,2024-07-21,Gelora 10 November,Internasional,Myanmar 1-1 Laos,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
6,Piala AFF U-19 2024,Sepak Bola,2024-07-24,2024-07-24,Gelora Bung Tomo,Internasional,Laos 1-4 Vietnam,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
7,Piala AFF U-19 2024,Sepak Bola,2024-07-24,2024-07-24,Gelora 10 November,Internasional,Myanmar 0-1 Australia,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
8,Piala AFF U-19 2024,Sepak Bola,2024-07-19,2024-07-19,Gelora 10 November,Internasional,Malaysia 11-0 Brunei,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
9,Piala AFF U-19 2024,Sepak Bola,2024-07-19,2024-07-19,Gelora 10 November,Internasional,Thailand 2-1 Singapura,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
10,Piala AFF U-19 2024,Sepak Bola,2024-07-22,2024-07-22,Gelora 10 November,Internasional,Brunei 0-6 Thailand,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
11,Piala AFF U-19 2024,Sepak Bola,2024-07-22,2024-07-22,Gelora 10 November,Internasional,Singapura 0-5 Malaysia,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
12,Piala AFF U-19 2024,Sepak Bola,2024-07-25,2024-07-25,Gelora Bung Tomo,Internasional,Malaysia 1-1 Thailand,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
13,Piala AFF U-19 2024,Sepak Bola,2024-07-25,2024-07-25,Gelora 10 November,Internasional,Singapura vs Brunei,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
14,Piala AFF U-19 2024,Sepak Bola,2024-07-27,2024-07-27,Gelora Bung Tomo,Internasional,Australia 0-1 Thailand,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
15,Piala AFF U-19 2024,Sepak Bola,2024-07-27,2024-07-27,Gelora Bung Tomo,Internasional,Indonesia 1-0 Malaysia,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
16,Piala AFF U-19 2024,Sepak Bola,2024-07-29,2024-07-29,Gelora Bung Tomo,Internasional,Indonesia U-19 vs Thailand U-19,1:0,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...

In [ ]:
df_aff['nama_venue'] = (
    df_aff['nama_venue']
    .str.strip()
    .replace({
        'Gelora 10 November': 'Gelora 10 Nopember',
        'Gelora Bung Tomo': 'Gelora Bung Tomo'
    })
)

# Hapus duplikat jika ada
df_aff = (
    df_aff
    .drop_duplicates(
        subset=[
            'nama_event',
            'tanggal_mulai',
            'nama_venue',
            'peserta_tim'
        ]
    )
    .reset_index(drop=True)
)

# Urutkan berdasarkan tanggal
df_aff = df_aff.sort_values(
    ['tanggal_mulai', 'nama_venue']
).reset_index(drop=True)

# Buat ID
df_aff.insert(
    0,
    'id_event',
    [
        f'AFF19-{i:03d}'
        for i in range(1, len(df_aff) + 1)
    ]
)

display(df_aff)

,id_event,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
0,AFF19-001,Piala AFF U-19 2024,Sepak Bola,2024-07-18,2024-07-18,Gelora 10 Nopember,Internasional,Laos 0-6 Australia,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
1,AFF19-002,Piala AFF U-19 2024,Sepak Bola,2024-07-18,2024-07-18,Gelora 10 Nopember,Internasional,Vietnam 1-1 Myanmar,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
2,AFF19-003,Piala AFF U-19 2024,Sepak Bola,2024-07-19,2024-07-19,Gelora 10 Nopember,Internasional,Malaysia 11-0 Brunei,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
3,AFF19-004,Piala AFF U-19 2024,Sepak Bola,2024-07-19,2024-07-19,Gelora 10 Nopember,Internasional,Thailand 2-1 Singapura,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
4,AFF19-005,Piala AFF U-19 2024,Sepak Bola,2024-07-21,2024-07-21,Gelora 10 Nopember,Internasional,Australia 6-2 Vietnam,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
5,AFF19-006,Piala AFF U-19 2024,Sepak Bola,2024-07-21,2024-07-21,Gelora 10 Nopember,Internasional,Myanmar 1-1 Laos,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
6,AFF19-007,Piala AFF U-19 2024,Sepak Bola,2024-07-22,2024-07-22,Gelora 10 Nopember,Internasional,Brunei 0-6 Thailand,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
7,AFF19-008,Piala AFF U-19 2024,Sepak Bola,2024-07-22,2024-07-22,Gelora 10 Nopember,Internasional,Singapura 0-5 Malaysia,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
8,AFF19-009,Piala AFF U-19 2024,Sepak Bola,2024-07-23,2024-07-23,Gelora 10 Nopember,Internasional,Kamboja 1-0 Filipina,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
9,AFF19-010,Piala AFF U-19 2024,Sepak Bola,2024-07-23,2024-07-23,Gelora Bung Tomo,Internasional,Indonesia 6-2 Timor Leste,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
10,AFF19-011,Piala AFF U-19 2024,Sepak Bola,2024-07-24,2024-07-24,Gelora 10 Nopember,Internasional,Myanmar 0-1 Australia,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
11,AFF19-012,Piala AFF U-19 2024,Sepak Bola,2024-07-24,2024-07-24,Gelora Bung Tomo,Internasional,Laos 1-4 Vietnam,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
12,AFF19-013,Piala AFF U-19 2024,Sepak Bola,2024-07-25,2024-07-25,Gelora 10 Nopember,Internasional,Singapura vs Brunei,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
13,AFF19-014,Piala AFF U-19 2024,Sepak Bola,2024-07-25,2024-07-25,Gelora Bung Tomo,Internasional,Malaysia 1-1 Thailand,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
14,AFF19-015,Piala AFF U-19 2024,Sepak Bola,2024-07-27,2024-07-27,Gelora Bung Tomo,Internasional,Australia 0-1 Thailand,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
15,AFF19-016,Piala AFF U-19 2024,Sepak Bola,2024-07-27,2024-07-27,Gelora Bung Tomo,Internasional,Indonesia 1-0 Malaysia,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
16,AFF19-017,Piala AFF U-19 2024,Sepak Bola,2024-07-29,2024-07-29,Gelora Bung Tomo,Internasional,Indonesia U-19 vs Thailand U-19,1:0,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...

In [ ]:
print("=== EVENT PER KOMPETISI ===")

display(
    df_aff
    .groupby('nama_event')
    .size()
    .reset_index(name='jumlah_event')
)

print("\n=== EVENT PER VENUE ===")

display(
    df_aff
    .groupby('nama_venue')
    .size()
    .reset_index(name='jumlah_event')
    .sort_values('jumlah_event', ascending=False)
)

print("\n=== DETAIL EVENT ===")

display(
    df_aff[
        [
            'id_event',
            'tanggal_mulai',
            'nama_venue',
            'peserta_tim',
            'hasil_skor'
        ]
    ]
)

=== EVENT PER KOMPETISI ===

            nama_event  jumlah_event
0  Piala AFF U-19 2024            17

=== EVENT PER VENUE ===

           nama_venue  jumlah_event
0  Gelora 10 Nopember            11
1    Gelora Bung Tomo             6

=== DETAIL EVENT ===

,id_event,tanggal_mulai,nama_venue,peserta_tim,hasil_skor
0,AFF19-001,2024-07-18,Gelora 10 Nopember,Laos 0-6 Australia,None
1,AFF19-002,2024-07-18,Gelora 10 Nopember,Vietnam 1-1 Myanmar,None
2,AFF19-003,2024-07-19,Gelora 10 Nopember,Malaysia 11-0 Brunei,None
3,AFF19-004,2024-07-19,Gelora 10 Nopember,Thailand 2-1 Singapura,None
4,AFF19-005,2024-07-21,Gelora 10 Nopember,Australia 6-2 Vietnam,None
5,AFF19-006,2024-07-21,Gelora 10 Nopember,Myanmar 1-1 Laos,None
6,AFF19-007,2024-07-22,Gelora 10 Nopember,Brunei 0-6 Thailand,None
7,AFF19-008,2024-07-22,Gelora 10 Nopember,Singapura 0-5 Malaysia,None
8,AFF19-009,2024-07-23,Gelora 10 Nopember,Kamboja 1-0 Filipina,None
9,AFF19-010,2024-07-23,Gelora Bung Tomo,Indonesia 6-2 Timor Leste,None
10,AFF19-011,2024-07-24,Gelora 10 Nopember,Myanmar 0-1 Australia,None
11,AFF19-012,2024-07-24,Gelora Bung Tomo,Laos 1-4 Vietnam,None
12,AFF19-013,2024-07-25,Gelora 10 Nopember,Singapura vs Brunei,None
13,AFF19-014,2024-07-25,Gelora Bung Tomo,Malaysia 1-1 Thailand,None
14,AFF19-015,2024-07-27,Gelora Bung Tomo,Australia 0-1 Thailand,None
15,AFF19-016,2024-07-27,Gelora Bung Tomo,Indonesia 1-0 Malaysia,None
16,AFF19-017,2024-07-29,Gelora Bung Tomo,Indonesia U-19 vs Thailand U-19,1:0

### 5.5 Memisahkan nama peserta dan skor

In [ ]:
def pisahkan_skor(teks):
    """
    Mengubah:
    'Laos 0-6 Australia'
    menjadi:
    peserta = 'Laos vs Australia'
    skor = '0:6'
    """

    match = re.match(
        r'^(.+?)\s+(\d+)\s*[-:]\s*(\d+)\s+(.+)$',
        str(teks).strip()
    )

    if match:
        tim_home = match.group(1).strip()
        skor_home = match.group(2)
        skor_away = match.group(3)
        tim_away = match.group(4).strip()

        peserta = f"{tim_home} vs {tim_away}"
        skor = f"{skor_home}:{skor_away}"

        return peserta, skor

    return str(teks).strip(), None


hasil_pisah = df_aff['peserta_tim'].apply(pisahkan_skor)

df_aff['peserta_tim'] = hasil_pisah.apply(lambda x: x[0])

# Hanya isi skor kalau sebelumnya belum ada
df_aff['hasil_skor'] = df_aff.apply(
    lambda row: row['hasil_skor']
    if pd.notna(row['hasil_skor'])
    else hasil_pisah.loc[row.name][1],
    axis=1
)

display(
    df_aff[
        [
            'id_event',
            'tanggal_mulai',
            'nama_venue',
            'peserta_tim',
            'hasil_skor'
        ]
    ]
)

,id_event,tanggal_mulai,nama_venue,peserta_tim,hasil_skor
0,AFF19-001,2024-07-18,Gelora 10 Nopember,Laos vs Australia,0:6
1,AFF19-002,2024-07-18,Gelora 10 Nopember,Vietnam vs Myanmar,1:1
2,AFF19-003,2024-07-19,Gelora 10 Nopember,Malaysia vs Brunei,11:0
3,AFF19-004,2024-07-19,Gelora 10 Nopember,Thailand vs Singapura,2:1
4,AFF19-005,2024-07-21,Gelora 10 Nopember,Australia vs Vietnam,6:2
5,AFF19-006,2024-07-21,Gelora 10 Nopember,Myanmar vs Laos,1:1
6,AFF19-007,2024-07-22,Gelora 10 Nopember,Brunei vs Thailand,0:6
7,AFF19-008,2024-07-22,Gelora 10 Nopember,Singapura vs Malaysia,0:5
8,AFF19-009,2024-07-23,Gelora 10 Nopember,Kamboja vs Filipina,1:0
9,AFF19-010,2024-07-23,Gelora Bung Tomo,Indonesia vs Timor Leste,6:2
10,AFF19-011,2024-07-24,Gelora 10 Nopember,Myanmar vs Australia,0:1
11,AFF19-012,2024-07-24,Gelora Bung Tomo,Laos vs Vietnam,1:4
12,AFF19-013,2024-07-25,Gelora 10 Nopember,Singapura vs Brunei,None
13,AFF19-014,2024-07-25,Gelora Bung Tomo,Malaysia vs Thailand,1:1
14,AFF19-015,2024-07-27,Gelora Bung Tomo,Australia vs Thailand,0:1
15,AFF19-016,2024-07-27,Gelora Bung Tomo,Indonesia vs Malaysia,1:0
16,AFF19-017,2024-07-29,Gelora Bung Tomo,Indonesia U-19 vs Thailand U-19,1:0

### 5.6 Standardisasi data event Liga 1 dan AFF

In [ ]:
# Buat ulang df_event dari sumber aslinya
# sehingga tidak terjadi penambahan/duplikasi event

df_event = pd.concat(
    [
        df_event_liga1,
        df_aff
    ],
    ignore_index=True
)

print("Total event:", len(df_event))

Total event: 51

In [ ]:
df_event['nama_venue'] = (
    df_event['nama_venue']
    .str.strip()
    .replace({
        'GELORA BUNG TOMO': 'Gelora Bung Tomo',
        'Gelora Bung Tomo': 'Gelora Bung Tomo',
        'Gelora 10 November': 'Gelora 10 Nopember',
        'Gelora 10 Nopember': 'Gelora 10 Nopember'
    })
)

In [ ]:
display(
    df_event
    .groupby('nama_event')
    .size()
    .reset_index(name='jumlah_event')
)

            nama_event  jumlah_event
0     Liga 1 2023/2024            17
1     Liga 1 2024/2025            17
2  Piala AFF U-19 2024            17

In [ ]:
display(
    df_event
    .groupby('nama_venue')
    .size()
    .reset_index(name='jumlah_event')
    .sort_values('jumlah_event', ascending=False)
)

           nama_venue  jumlah_event
1    Gelora Bung Tomo            40
0  Gelora 10 Nopember            11

In [ ]:
df_event

,id_event,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
0,LIGA1-2023-001,Liga 1 2023/2024,Sepak Bola,2023-07-08,2023-07-08,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PS BARITO PUTERA,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
1,LIGA1-2023-002,Liga 1 2023/2024,Sepak Bola,2023-07-23,2023-07-23,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs RANS Nusantara FC,2:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
2,LIGA1-2023-003,Liga 1 2023/2024,Sepak Bola,2023-08-04,2023-08-04,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PERSIKABO 1973,1:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
3,LIGA1-2023-004,Liga 1 2023/2024,Sepak Bola,2023-08-12,2023-08-12,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PERSITA,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
4,LIGA1-2023-005,Liga 1 2023/2024,Sepak Bola,2023-08-18,2023-08-18,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PSM MAKASSAR,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
5,LIGA1-2023-006,Liga 1 2023/2024,Sepak Bola,2023-09-03,2023-09-03,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs BORNEO FC SAMARINDA,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
6,LIGA1-2023-007,Liga 1 2023/2024,Sepak Bola,2023-09-23,2023-09-23,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs AREMA FC,3:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
7,LIGA1-2023-008,Liga 1 2023/2024,Sepak Bola,2023-10-07,2023-10-07,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PERSIB BANDUNG,2:3,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
8,LIGA1-2023-009,Liga 1 2023/2024,Sepak Bola,2023-12-09,2023-12-09,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PERSIJA JAKARTA,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
9,LIGA1-2023-010,Liga 1 2023/2024,Sepak Bola,2023-12-13,2023-12-13,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PERSIS SOLO,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
10,LIGA1-2023-011,Liga 1 2023/2024,Sepak Bola,2024-01-30,2024-01-30,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PSIS SEMARANG,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
11,LIGA1-2023-012,Liga 1 2023/2024,Sepak Bola,2024-02-04,2024-02-04,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs BHAYANGKARA PRESISI LAMPUNG FC,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
12,LIGA1-2023-013,Liga 1 2023/2024,Sepak Bola,2024-03-03,2024-03-03,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PSS SLEMAN,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
13,LIGA1-2023-014,Liga 1 2023/2024,Sepak Bola,2024-03-13,2024-03-13,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs MADURA UNITED FC,0:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
14,LIGA1-2023-015,Liga 1 2023/2024,Sepak Bola,2024-04-16,2024-04-16,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs DEWA UNITED BANTEN FC,0:3,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
15,LIGA1-2023-016,Liga 1 2023/2024,Sepak Bola,2024-04-24,2024-04-24,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs BALI UNITED FC,0:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
16,LIGA1-2023-017,Liga 1 2023/2024,Sepak Bola,2024-04-28,2024-04-28,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PERSIK KEDIRI,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2023-2024/PERSEBAYA_SURABAYA
17,LIGA1-2024-001,Liga 1 2024/2025,Sepak Bola,2024-08-11,2024-08-11,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PSS SLEMAN,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
18,LIGA1-2024-002,Liga 1 2024/2025,Sepak Bola,2024-08-23,2024-08-23,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PS BARITO PUTERA,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
19,LIGA1-2024-003,Liga 1 2024/2025,Sepak Bola,2024-09-18,2024-09-18,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PERSIS SOLO,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
20,LIGA1-2024-004,Liga 1 2024/2025,Sepak Bola,2024-09-27,2024-09-27,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs DEWA UNITED BANTEN FC,0:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
21,LIGA1-2024-005,Liga 1 2024/2025,Sepak Bola,2024-10-23,2024-10-23,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PSM MAKASSAR,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
22,LIGA1-2024-006,Liga 1 2024/2025,Sepak Bola,2024-11-22,2024-11-22,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PERSIJA JAKARTA,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
23,LIGA1-2024-007,Liga 1 2024/2025,Sepak Bola,2024-12-07,2024-12-07,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs AREMA FC,3:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
24,LIGA1-2024-008,Liga 1 2024/2025,Sepak Bola,2024-12-11,2024-12-11,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PERSIK KEDIRI,4:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
25,LIGA1-2024-009,Liga 1 2024/2025,Sepak Bola,2024-12-20,2024-12-20,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs BORNEO FC SAMARINDA,2:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
26,LIGA1-2024-010,Liga 1 2024/2025,Sepak Bola,2025-01-17,2025-01-17,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs JAVA UNITED FC,0:2,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
27,LIGA1-2024-011,Liga 1 2024/2025,Sepak Bola,2025-01-31,2025-01-31,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PERSITA,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
28,LIGA1-2024-012,Liga 1 2024/2025,Sepak Bola,2025-02-15,2025-02-15,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PSBS BIAK,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
29,LIGA1-2024-013,Liga 1 2024/2025,Sepak Bola,2025-03-01,2025-03-01,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PERSIB BANDUNG,4:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
30,LIGA1-2024-014,Liga 1 2024/2025,Sepak Bola,2025-03-12,2025-03-12,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs PSIS SEMARANG,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
31,LIGA1-2024-015,Liga 1 2024/2025,Sepak Bola,2025-04-20,2025-04-20,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs MADURA UNITED FC,1:0,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
32,LIGA1-2024-016,Liga 1 2024/2025,Sepak Bola,2025-05-11,2025-05-11,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs SEMEN PADANG FC,1:1,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
33,LIGA1-2024-017,Liga 1 2024/2025,Sepak Bola,2025-05-23,2025-05-23,Gelora Bung Tomo,Nasional,PERSEBAYA SURABAYA vs BALI UNITED FC,1:3,https://www.ligaindonesiabaru.com/clubs/single/BRI_LIGA_1_2024-25/PERSEBAYA_SURABAYA
34,AFF19-001,Piala AFF U-19 2024,Sepak Bola,2024-07-18,2024-07-18,Gelora 10 Nopember,Internasional,Laos vs Australia,0:6,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
35,AFF19-002,Piala AFF U-19 2024,Sepak Bola,2024-07-18,2024-07-18,Gelora 10 Nopember,Internasional,Vietnam vs Myanmar,1:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
36,AFF19-003,Piala AFF U-19 2024,Sepak Bola,2024-07-19,2024-07-19,Gelora 10 Nopember,Internasional,Malaysia vs Brunei,11:0,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
37,AFF19-004,Piala AFF U-19 2024,Sepak Bola,2024-07-19,2024-07-19,Gelora 10 Nopember,Internasional,Thailand vs Singapura,2:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
38,AFF19-005,Piala AFF U-19 2024,Sepak Bola,2024-07-21,2024-07-21,Gelora 10 Nopember,Internasional,Australia vs Vietnam,6:2,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
39,AFF19-006,Piala AFF U-19 2024,Sepak Bola,2024-07-21,2024-07-21,Gelora 10 Nopember,Internasional,Myanmar vs Laos,1:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
40,AFF19-007,Piala AFF U-19 2024,Sepak Bola,2024-07-22,2024-07-22,Gelora 10 Nopember,Internasional,Brunei vs Thailand,0:6,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
41,AFF19-008,Piala AFF U-19 2024,Sepak Bola,2024-07-22,2024-07-22,Gelora 10 Nopember,Internasional,Singapura vs Malaysia,0:5,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
42,AFF19-009,Piala AFF U-19 2024,Sepak Bola,2024-07-23,2024-07-23,Gelora 10 Nopember,Internasional,Kamboja vs Filipina,1:0,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
43,AFF19-010,Piala AFF U-19 2024,Sepak Bola,2024-07-23,2024-07-23,Gelora Bung Tomo,Internasional,Indonesia vs Timor Leste,6:2,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
44,AFF19-011,Piala AFF U-19 2024,Sepak Bola,2024-07-24,2024-07-24,Gelora 10 Nopember,Internasional,Myanmar vs Australia,0:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
45,AFF19-012,Piala AFF U-19 2024,Sepak Bola,2024-07-24,2024-07-24,Gelora Bung Tomo,Internasional,Laos vs Vietnam,1:4,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
46,AFF19-013,Piala AFF U-19 2024,Sepak Bola,2024-07-25,2024-07-25,Gelora 10 Nopember,Internasional,Singapura vs Brunei,None,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
47,AFF19-014,Piala AFF U-19 2024,Sepak Bola,2024-07-25,2024-07-25,Gelora Bung Tomo,Internasional,Malaysia vs Thailand,1:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
48,AFF19-015,Piala AFF U-19 2024,Sepak Bola,2024-07-27,2024-07-27,Gelora Bung Tomo,Internasional,Australia vs Thailand,0:1,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
49,AFF19-016,Piala AFF U-19 2024,Sepak Bola,2024-07-27,2024-07-27,Gelora Bung Tomo,Internasional,Indonesia vs Malaysia,1:0,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...
50,AFF19-017,Piala AFF U-19 2024,Sepak Bola,2024-07-29,2024-07-29,Gelora Bung Tomo,Internasional,Indonesia U-19 vs Thailand U-19,1:0,https://www.bola.net/tim_nasional/hasil-lengkap-klasemen-dan-top-skor-piala-aff-u-19-2024-indone...

# 6. Scraping Event Piala Soeratin

## Piala Soeratin U-17

### 6.1 Pemeriksaan halaman kalender PSSI Jawa Timur

In [ ]:
url_pssi = "https://www.pssijatim.com/calendar/semua-pertandingan"

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/154.0.0.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7"
}

try:
    response = requests.get(
        url_pssi,
        headers=headers,
        timeout=(20, 120)
    )

    print("Status:", response.status_code)
    print("Ukuran:", len(response.content), "bytes")

except requests.exceptions.Timeout:
    print("Request masih timeout.")

Status: 200
Ukuran: 22102326 bytes

In [ ]:
soup = BeautifulSoup(
    response.text,
    "html.parser"
)

print(soup.get_text(" ", strip=True)[:3000])

Semua Pertandingan - PSSI Jawa Timur Selasa, 6 Oktober 2026 Live Home Tentang PSSI Jatim Anggota KLUB LIGA 1 KLUB LIGA 2 KLUB LIGA 3 KLUB LIGA 4 ASKAB/ASKOT SSB TERAFILIASI Kompetisi Liga 3 Liga 3 Jatim 2021 Liga 3 Jatim 2023/2024 Liga 3 Nasional 2021/2022 Liga 4 Liga 4 “Kapal Api” PSSI Jawa Timur 2024/2025 Liga 4 “Kapal Api” PSSI Jawa Timur 2025/2026 Piala Pertiwi Piala Soeratin U-13 U-15 U-17 Festival Grassroot Live stream Admin Update skor Login No Result View All Result Home Tentang PSSI Jatim Anggota KLUB LIGA 1 KLUB LIGA 2 KLUB LIGA 3 KLUB LIGA 4 ASKAB/ASKOT SSB TERAFILIASI Kompetisi Liga 3 Liga 3 Jatim 2021 Liga 3 Jatim 2023/2024 Liga 3 Nasional 2021/2022 Liga 4 Liga 4 “Kapal Api” PSSI Jawa Timur 2024/2025 Liga 4 “Kapal Api” PSSI Jawa Timur 2025/2026 Piala Pertiwi Piala Soeratin U-13 U-15 U-17 Festival Grassroot Live stream Admin Update skor Login No Result View All Result Home Nasional Internasional Youth Development Agenda Liga 3 Dokumen Resmi Semua Pertandingan Senin, 31 Januari 2022 - 11:04 WIB Minggu, 13 September 2026 Selesai 2 - 0 Final Juara 1 Piala Soeratin U-15 Jember Sport Garden N/A Persebaya Surabaya VS Deltras Sidoarjo Minggu, 13 September 2026 Selesai 1 - 0 Final Juara 1 Piala Soeratin U-13 Jember Sport Garden N/A Persebaya Surabaya VS Persida Sidoarjo Minggu, 13 September 2026 Selesai 2 - 0 Final Juara 3 Piala Soeratin U-15 Jember Sport Garden N/A Arunda Malang VS Pordes FC Jember Minggu, 13 September 2026 Selesai 2 - 2 adu penalti : [ 3 - 1 ] Final Juara 3 Piala Soeratin U-13 Jember Sport Garden N/A Malang United VS Pordes FC Jember Sabtu, 12 September 2026 Selesai 2 - 3 Semifinal Piala Soeratin U-15 Jember Sport Garden N/A Pordes FC Jember VS Deltras Sidoarjo Sabtu, 12 September 2026 Selesai 3 - 1 Final 1st Pl. Piala Soeratin U-17 Stadion Brawijaya Kediri N/A Persebaya Surabaya VS Inter Pemuda Kediri Sabtu, 12 September 2026 Selesai 2 - 0 Final 3rd Pl. Piala Soeratin U-17 Stadion Brawijaya Kediri N/A Persida Sidoarjo VS PSBR Kota Blitar Sabtu, 12 September 2026 Selesai 0 - 6 Semifinal Piala Soeratin U-15 Jember Sport Garden N/A Arunda Malang VS Persebaya Surabaya Sabtu, 12 September 2026 Selesai 3 - 0 Semifinal Piala Soeratin U-13 Jember Sport Garden N/A Persida Sidoarjo VS Pordes FC Jember Sabtu, 12 September 2026 Selesai 0 - 3 Semifinal Piala Soeratin U-13 Jember Sport Garden N/A Malang United VS Persebaya Surabaya Kamis, 10 September 2026 Selesai 2 - 0 Semifinal Piala Soeratin U-17 Stadion Jenggolo Sidoarjo N/A Persebaya Surabaya VS Persida Sidoarjo Kamis, 10 September 2026 Selesai 1 - 0 Semifinal Piala Soeratin U-17 Stadion Soeprijadi Blitar N/A Inter Pemuda Kediri VS PSBR Kota Blitar Kamis, 10 September 2026 Selesai 3 - 0 8 Besar Piala Soeratin U-13 Stadion Notohadinegoro Jember N/A Pordes FC Jember VS PS Karya Muda Kamis, 10 September 2026 Selesai 0 - 1 8 Besar Piala Soeratin U-15 Lapangan Glagahwero, Jember N/A Arema FC VS Deltras Sidoarjo Kamis, 10 September 2026 Selesai 0 - 2 8 Besar Piala Soeratin U-13 Stadion N

In [ ]:
# Cari semua link yang mengandung Soeratin
links_soeratin = []

for a in soup.find_all('a', href=True):
    teks = a.get_text(" ", strip=True)
    href = a['href']

    if 'soeratin' in (teks + ' ' + href).lower():
        links_soeratin.append({
            'teks': teks,
            'url': href
        })

pd.DataFrame(links_soeratin).drop_duplicates()

             teks                                             url
0  Piala Soeratin                                               #
1            U-13  https://pssijatim.com/page-piala-soeratin-u-13
2            U-15  https://pssijatim.com/page-piala-soeratin-u-15
3            U-17  https://pssijatim.com/page-piala-soeratin-u-17

### 6.2 Scraping Piala Soeratin U-17

In [ ]:
url_u17 = "https://pssijatim.com/page-piala-soeratin-u-17"

response_u17 = requests.get(
    url_u17,
    headers=headers,
    timeout=(20, 120)
)

print("Status:", response_u17.status_code)
print("Ukuran:", len(response_u17.content), "bytes")

Status: 200
Ukuran: 8351959 bytes

In [ ]:
soup_u17 = BeautifulSoup(
    response_u17.text,
    'html.parser'
)

text_u17 = soup_u17.get_text(
    " ",
    strip=True
)

print(text_u17[:5000])

Piala Soeratin U-17 - PSSI Jawa Timur Minggu, 4 Oktober 2026 Live Home Tentang PSSI Jatim Anggota KLUB LIGA 1 KLUB LIGA 2 KLUB LIGA 3 KLUB LIGA 4 ASKAB/ASKOT SSB TERAFILIASI Kompetisi Liga 3 Liga 3 Jatim 2021 Liga 3 Jatim 2023/2024 Liga 3 Nasional 2021/2022 Liga 4 Liga 4 “Kapal Api” PSSI Jawa Timur 2024/2025 Liga 4 “Kapal Api” PSSI Jawa Timur 2025/2026 Piala Pertiwi Piala Soeratin U-13 U-15 U-17 Festival Grassroot Live stream Admin Update skor Login No Result View All Result Home Tentang PSSI Jatim Anggota KLUB LIGA 1 KLUB LIGA 2 KLUB LIGA 3 KLUB LIGA 4 ASKAB/ASKOT SSB TERAFILIASI Kompetisi Liga 3 Liga 3 Jatim 2021 Liga 3 Jatim 2023/2024 Liga 3 Nasional 2021/2022 Liga 4 Liga 4 “Kapal Api” PSSI Jawa Timur 2024/2025 Liga 4 “Kapal Api” PSSI Jawa Timur 2025/2026 Piala Pertiwi Piala Soeratin U-13 U-15 U-17 Festival Grassroot Live stream Admin Update skor Login No Result View All Result Home Nasional Internasional Youth Development Agenda Liga 3 Dokumen Resmi Home Piala Soeratin U-17 Piala Soeratin U-17 2023 Winner Persedikab Kediri U-17 1st Place Piala Soeratin U-17 Jatim 2023 Jadwal Data habis/selesai Skor Minggu, 3 Desember 2023 Selesai 0 - 4 Final 1st Pl. Piala Soeratin U-17 Stadion Canda Bhirawa N/A Deltras Sidoarjo U-17 VS Persedikab Kediri U-17 Minggu, 3 Desember 2023 Selesai 3 - 2 Final 3rd Pl. Piala Soeratin U-17 Stadion Canda Bhirawa N/A Sinar Harapan U-17 VS Perseta Tulungagung U-17 Jumat, 1 Desember 2023 Selesai 1 - 3 Semifinal Piala Soeratin U-17 Stadion Canda Bhirawa N/A Perseta Tulungagung U-17 VS Persedikab Kediri U-17 Jumat, 1 Desember 2023 Selesai 1 - 0 Semifinal Piala Soeratin U-17 Stadion Canda Bhirawa N/A Deltras Sidoarjo U-17 VS Sinar Harapan U-17 Senin, 27 November 2023 Selesai 2 - 1 Grup J Piala Soeratin U-17 Stadion Soeprijadi Blitar N/A PSBR Kota Blitar U-17 VS NZR Sumbersari U-17 Senin, 27 November 2023 Selesai 1 - 2 Grup I Piala Soeratin U-17 Stadion Jenggolo Sidoarjo N/A Sinar Harapan U-17 VS PSMP Mojokerto U-17 Senin, 27 November 2023 Selesai 1 - 2 Grup H Piala Soeratin U-17 Stadion Soeprijadi Blitar N/A Arema FC U-17 VS Perseta Tulungagung U-17 Senin, 27 November 2023 Selesai 1 - 2 Grup G Piala Soeratin U-17 Stadion Jenggolo Sidoarjo N/A Persebaya Surabaya U-17 VS Deltras Sidoarjo U-17 Sabtu, 25 November 2023 Selesai 4 - 2 Grup G Piala Soeratin U-17 Stadion Jenggolo Sidoarjo N/A Deltras Sidoarjo U-17 VS Persikoba Batu U-17 Sabtu, 25 November 2023 Selesai 2 - 1 Grup H Piala Soeratin U-17 Stadion Soeprijadi Blitar N/A Perseta Tulungagung U-17 VS Persipro 1954 U-17 Sabtu, 25 November 2023 Selesai 0 - 1 Grup J Piala Soeratin U-17 Stadion Soeprijadi Blitar N/A NZR Sumbersari U-17 VS Persedikab Kediri U-17 Sabtu, 25 November 2023 Selesai 0 - 1 Grup I Piala Soeratin U-17 Stadion Jenggolo Sidoarjo N/A PSMP Mojokerto U-17 VS Persegres Putra U-17 Jumat, 24 November 2023 Selesai 2 - 4 Grup I Piala Soeratin U-17 Stadion Jenggolo Sidoarjo N/A Persegres Putra U-17 VS Sinar Harapan U-17 Jumat, 24 November 2023 Selesai 2 - 0 Grup J Piala Soeratin U-17 Stadion Soeprijadi Blitar N/A Persedikab Kediri U-17 VS PSBR Kota Blitar U-17 Jumat, 24 November 2023 Selesai 3 - 0 Grup H Piala Soeratin U-17 Stadion Soeprijadi Blitar N/A Persipro 1954 U-17 VS Arema FC U-17 Jumat, 24 November 2023 Selesai 1 - 3 Grup G Piala Soeratin U-17 Stadion Jenggolo Sidoarjo N/A Persikoba Batu U-17 VS Persebaya Surabaya U-17 Senin, 20 November 2023 Selesai 3 - 1 Grup B Piala Soeratin U-17 Lapangan Brigif 2 Marinir SDA N/A Arema FC U-17 VS Inter Kediri U-17 Senin, 20 November 2023 Selesai 0 - 2 Grup B Piala Soeratin U-17 Lapangan Brigif 2 Marinir SDA N/A Persebo Muda 1964 U-17 VS Deltras Sidoarjo U-17 Minggu, 19 November 2023 Selesai 3 - 0 Grup B Piala Soeratin U-17 Lapangan Brigif 2 Marinir SDA N/A Arema FC U-17 VS Persebo Muda 1964 U-17 Minggu, 19 November 2023 Selesai 0 - 2 Grup B Piala Soeratin U-17 Lapangan Brigif 2 Marinir SDA N/A Inter Kediri U-17 VS Deltras Sidoarjo U-17 Sabtu, 18 November 2023 Selesai 0 - 1 Grup D Piala Soeratin U-17 Stadion Soeprijadi Blitar N/A Bojonegoro FC U-17 VS PSMP Mojokerto U-17 Sabtu, 18 November 2023 Selesai 2 - 0 Grup A Piala Soeratin U-17 Lapangan Brigif Marinir SDA N/A Naga Emas Asri U-17 VS Persiga Trenggalek U-17 Sabtu, 18 November 2023 Selesai 1 - 0 Grup E Piala Soeratin U-17 Lapangan Agro Kota Batu N/A PSPK Jember U-17 VS Bajul Ijo U-17 Sabtu, 18 November 2023 Selesai 0 - 1 Grup F Piala Soeratin U-17 Stadion Canda Bhirawa N/A Persid Jember U-17 VS Persegres Putra U-17 Sabtu, 18 November 2023 Selesai 2 - 0 Grup F Piala Soeratin U-17 Stadion Canda Bhirawa N/A Persedikab Kediri U-17 VS Madiun Putra U-17 Sabtu, 18 November 2023 Selesai 0 - 1 Grup A Piala Soeratin U-17 Lapangan Brigif Marinir SDA N/A Persipro 1954 U-17 VS Persebaya Surabaya U-17 Sabtu, 18 November 2023 Selesai 1 - 1 Grup E Piala Soeratin U-17 Lapangan Agro Kota Batu N/A Persikoba Batu U-17 VS NZR Sumbersari U-17 Sabtu, 18 November 2023 Selesai 1 - 2 Grup D Piala Soeratin U-17 Stadion Soeprijadi Blitar N/A PSBR Kota Blitar U

In [ ]:
for tahun in ['2023', '2024', '2025']:
    print(
        tahun,
        "->",
        tahun in text_u17
    )

2023 -> True
2024 -> True
2025 -> True

In [ ]:
elemen_pertandingan = soup_u17.find_all(
    string=re.compile(
        r'Piala Soeratin U-17',
        re.I
    )
)

print(
    "Jumlah elemen:",
    len(elemen_pertandingan)
)

Jumlah elemen: 555

In [ ]:
for x in elemen_pertandingan[:5]:

    print("=" * 100)

    parent = x.parent

    print(
        parent.parent.get_text(
            " ",
            strip=True
        )[:1500]
    )

====================================================================================================
Piala Soeratin U-17 - PSSI Jawa Timur
====================================================================================================

====================================================================================================
Piala Soeratin U-17
====================================================================================================
Piala Soeratin U-17
====================================================================================================
Persedikab Kediri U-17 1st Place Piala Soeratin U-17 Jatim 2023

In [ ]:
elemen_vs = soup_u17.find_all(
    string=re.compile(r'\bVS\b', re.IGNORECASE)
)

print("Jumlah elemen VS:", len(elemen_vs))

for x in elemen_vs[:5]:
    print("=" * 100)
    print("TEXT:", x.strip())
    print("TAG :", x.parent.name)
    print("CLASS:", x.parent.get("class"))

Jumlah elemen VS: 546
====================================================================================================
TEXT: /* Add your CSS code here.

For example:
.example {
    color: red;
}

For brushing up on your CSS knowledge, check out http://www.w3schools.com/css/css_syntax.asp

End of comment */
/* ===============================

   BASE CONTAINER

================================ */

.sp-event-logos-2 {

    position: relative;

    display: grid;

    grid-template-columns: 1fr auto 1fr;

    align-items: center;

    text-align: center;

    font-size: 0;

}

/* ===============================

   TEAM COLUMN (FIX & STABIL)

================================ */

.sp-event-logos-2 .sp-team-logo {

    font-size: 14px;

}

/* Paksa home kiri & away kanan */

.sp-event-logos-2 .sp-team-logo:first-child {

    grid-column: 1;

}

.sp-event-logos-2 .sp-team-logo:last-child {

    grid-column: 3;

}

/* Logo image sama besar */

.sp-event-logos-2 .sp-team-logo img {

    width: 100px;

    height: auto;

    display: block;

    margin: 0 auto;

}

/* ===============================

   VS ICON (TENGAH ABSOLUT)

================================ */

.sp-event-logos-2::after {

    content: "";

    position: absolute;

    width: 34px;

    height: 34px;

    left: 50%;

    top: 50%;

    transform: translate(-50%, -50%);

    background: url("https://www.pssijatim.com/wp-content/uploads/2026/01/1000346005.png")

        no-repeat center / contain;

    pointer-events: none;

}

/* ===============================

   MOBILE (3 TINGKAT PASTI)

================================ */

@media (max-width: 767px) {

    .sp-event-logos-2 {

        display: flex;

        flex-direction: column;

        gap: 18px;

        padding-bottom: 12px; /* ruang napas bawah */

    }

    .sp-event-logos-2 .sp-team-logo img {

        width: 90px;

    }

    /* Paksa VS tetap di tengah */

    .sp-event-logos-2::after {

        top: 50%;

    }

    /* Turunkan away secara konsisten */

    .sp-event-logos-2 .sp-team-logo:last-child {

        margin-top: 10px;

    }

}
/* =================================

   STABILISASI KOLOM TIM

   (TAMBAHAN, BUKAN PENGGANTI)

================================= */
@media (max-width: 767px) {
    /* Home ke kanan */
    .sp-event-logos-2 .sp-team-logo:first-child {
        align-self: flex-end;
        text-align: right;
    }

    /* Away ke kiri */
    .sp-event-logos-2 .sp-team-logo:last-child {
        align-self: flex-start;
        text-align: left;
    }

    /* VS tetap center */
    .sp-event-logos-2::after {
        left: 50%;
        transform: translateX(-50%);
    }
}
@media (max-width: 767px) {
    .sp-team-logo {margin-top:-30px; margin-bottom:-30px;}
    .sp-event-logos-2 {

        padding-top: 50px;
		margin-bottom:50px;

    }

}
/*Desktop*/

.sp-event-logos-2 {

    isolation: isolate;

}
TAG : style
CLASS: None
====================================================================================================
TEXT: Deltras Sidoarjo U-17 VS Persedikab Kediri U-17
TAG : a
CLASS: None
====================================================================================================
TEXT: Sinar Harapan U-17 VS Perseta Tulungagung U-17
TAG : a
CLASS: None
====================================================================================================
TEXT: Perseta Tulungagung U-17 VS Persedikab Kediri U-17
TAG : a
CLASS: None
====================================================================================================
TEXT: Deltras Sidoarjo U-17 VS Sinar Harapan U-17
TAG : a
CLASS: None

In [ ]:
for x in elemen_vs[:3]:
    print("=" * 100)

    parent = x.parent

    for i in range(1, 6):
        if parent is not None:
            print(
                f"\nLEVEL {i}:",
                parent.name,
                parent.get("class")
            )
            print(
                parent.get_text(
                    " ",
                    strip=True
                )[:1000]
            )
            parent = parent.parent

====================================================================================================

LEVEL 1: style None
/* Add your CSS code here.

For example:
.example {
    color: red;
}

For brushing up on your CSS knowledge, check out http://www.w3schools.com/css/css_syntax.asp

End of comment */
/* ===============================

   BASE CONTAINER

================================ */

.sp-event-logos-2 {

    position: relative;

    display: grid;

    grid-template-columns: 1fr auto 1fr;

    align-items: center;

    text-align: center;

    font-size: 0;

}

/* ===============================

   TEAM COLUMN (FIX & STABIL)

================================ */

.sp-event-logos-2 .sp-team-logo {

    font-size: 14px;

}

/* Paksa home kiri & away kanan */

.sp-event-logos-2 .sp-team-logo:first-child {

    grid-column: 1;

}

.sp-event-logos-2 .sp-team-logo:last-child {

    grid-column: 3;

}

/* Logo image sama besar */

.sp-event-logos-2 .sp-team-logo img {

    width: 100px;

    height: auto;

    display: block;

    margin: 0 auto;

}

/* ===============================

   VS ICON (TEN

LEVEL 2: link None


LEVEL 3: meta None


LEVEL 4: meta None


LEVEL 5: link None

====================================================================================================

LEVEL 1: a None
Deltras Sidoarjo U-17 VS Persedikab Kediri U-17

LEVEL 2: h4 ['sp-event-title']
Deltras Sidoarjo U-17 VS Persedikab Kediri U-17

LEVEL 3: td None
Minggu, 3 Desember 2023 Selesai 0 - 4 Final 1st Pl. Piala Soeratin U-17 Stadion Canda Bhirawa N/A Deltras Sidoarjo U-17 VS Persedikab Kediri U-17

LEVEL 4: tr ['sp-row', 'sp-post', 'alternate']
Minggu, 3 Desember 2023 Selesai 0 - 4 Final 1st Pl. Piala Soeratin U-17 Stadion Canda Bhirawa N/A Deltras Sidoarjo U-17 VS Persedikab Kediri U-17

LEVEL 5: tbody None
Minggu, 3 Desember 2023 Selesai 0 - 4 Final 1st Pl. Piala Soeratin U-17 Stadion Canda Bhirawa N/A Deltras Sidoarjo U-17 VS Persedikab Kediri U-17 Minggu, 3 Desember 2023 Selesai 3 - 2 Final 3rd Pl. Piala Soeratin U-17 Stadion Canda Bhirawa N/A Sinar Harapan U-17 VS Perseta Tulungagung U-17 Jumat, 1 Desember 2023 Selesai 1 - 3 Semifinal Piala Soeratin U-17 Stadion Canda Bhirawa N/A Perseta Tulungagung U-17 VS Persedikab Kediri U-17 Jumat, 1 Desember 2023 Selesai 1 - 0 Semifinal Piala Soeratin U-17 Stadion Canda Bhirawa N/A Deltras Sidoarjo U-17 VS Sinar Harapan U-17 Senin, 27 November 2023 Selesai 2 - 1 Grup J Piala Soeratin U-17 Stadion Soeprijadi Blitar N/A PSBR Kota Blitar U-17 VS NZR Sumbersari U-17 Senin, 27 November 2023 Selesai 1 - 2 Grup I Piala Soeratin U-17 Stadion Jenggolo Sidoarjo N/A Sinar Harapan U-17 VS PSMP Mojokerto U-17 Senin, 27 November 2023 Selesai 1 - 2 Grup H Piala Soeratin U-17 Stadion Soeprijadi Blitar N/A Arema FC U-17 VS Perseta Tulungagung U-17 Senin, 27 Nove
====================================================================================================

LEVEL 1: a None
Sinar Harapan U-17 VS Perseta Tulungagung U-17

LEVEL 2: h4 ['sp-event-title']
Sinar Harapan U-17 VS Perseta Tulungagung U-17

LEVEL 3: td None
Minggu, 3 Desember 2023 Selesai 3 - 2 Final 3rd Pl. Piala Soeratin U-17 Stadion Canda Bhirawa N/A Sinar Harapan U-17 VS Perseta Tulungagung U-17

LEVEL 4: tr ['sp-row', 'sp-post']
Minggu, 3 Desember 2023 Selesai 3 - 2 Final 3rd Pl. Piala Soeratin U-17 Stadion Canda Bhirawa N/A Sinar Harapan U-17 VS Perseta Tulungagung U-17

LEVEL 5: tbody None
Minggu, 3 Desember 2023 Selesai 0 - 4 Final 1st Pl. Piala Soeratin U-17 Stadion Canda Bhirawa N/A Deltras Sidoarjo U-17 VS Persedikab Kediri U-17 Minggu, 3 Desember 2023 Selesai 3 - 2 Final 3rd Pl. Piala Soeratin U-17 Stadion Canda Bhirawa N/A Sinar Harapan U-17 VS Perseta Tulungagung U-17 Jumat, 1 Desember 2023 Selesai 1 - 3 Semifinal Piala Soeratin U-17 Stadion Canda Bhirawa N/A Perseta Tulungagung U-17 VS Persedikab Kediri U-17 Jumat, 1 Desember 2023 Selesai 1 - 0 Semifinal Piala Soeratin U-17 Stadion Canda Bhirawa N/A Deltras Sidoarjo U-17 VS Sinar Harapan U-17 Senin, 27 November 2023 Selesai 2 - 1 Grup J Piala Soeratin U-17 Stadion Soeprijadi Blitar N/A PSBR Kota Blitar U-17 VS NZR Sumbersari U-17 Senin, 27 November 2023 Selesai 1 - 2 Grup I Piala Soeratin U-17 Stadion Jenggolo Sidoarjo N/A Sinar Harapan U-17 VS PSMP Mojokerto U-17 Senin, 27 November 2023 Selesai 1 - 2 Grup H Piala Soeratin U-17 Stadion Soeprijadi Blitar N/A Arema FC U-17 VS Perseta Tulungagung U-17 Senin, 27 Nove

In [ ]:
rows_u17 = soup_u17.select('tr.sp-row.sp-post')

print("Jumlah pertandingan:", len(rows_u17))

Jumlah pertandingan: 545

In [ ]:
for row in rows_u17[:5]:
    print("=" * 100)
    print(row.get_text(" ", strip=True))

====================================================================================================
Minggu, 3 Desember 2023 Selesai 0 - 4 Final 1st Pl. Piala Soeratin U-17 Stadion Canda Bhirawa N/A Deltras Sidoarjo U-17 VS Persedikab Kediri U-17
====================================================================================================
Minggu, 3 Desember 2023 Selesai 3 - 2 Final 3rd Pl. Piala Soeratin U-17 Stadion Canda Bhirawa N/A Sinar Harapan U-17 VS Perseta Tulungagung U-17
====================================================================================================
Jumat, 1 Desember 2023 Selesai 1 - 3 Semifinal Piala Soeratin U-17 Stadion Canda Bhirawa N/A Perseta Tulungagung U-17 VS Persedikab Kediri U-17
====================================================================================================
Jumat, 1 Desember 2023 Selesai 1 - 0 Semifinal Piala Soeratin U-17 Stadion Canda Bhirawa N/A Deltras Sidoarjo U-17 VS Sinar Harapan U-17
====================================================================================================
Senin, 27 November 2023 Selesai 2 - 1 Grup J Piala Soeratin U-17 Stadion Soeprijadi Blitar N/A PSBR Kota Blitar U-17 VS NZR Sumbersari U-17

### 6.3 Membentuk dataset Soeratin U-17

In [ ]:
bulan_id = {
    "Januari": 1,
    "Februari": 2,
    "Maret": 3,
    "April": 4,
    "Mei": 5,
    "Juni": 6,
    "Juli": 7,
    "Agustus": 8,
    "September": 9,
    "Oktober": 10,
    "November": 11,
    "Desember": 12
}


def parse_tanggal_u17(text):
    pola = (
        r'(\d{1,2})\s+'
        r'(Januari|Februari|Maret|April|Mei|Juni|Juli|'
        r'Agustus|September|Oktober|November|Desember)'
        r'\s+(\d{4})'
    )

    match = re.search(
        pola,
        text,
        re.IGNORECASE
    )

    if not match:
        return pd.NaT

    hari = int(match.group(1))
    bulan = bulan_id[match.group(2).capitalize()]
    tahun = int(match.group(3))

    return pd.Timestamp(
        year=tahun,
        month=bulan,
        day=hari
    )


data_soeratin = []

for i, row in enumerate(rows_u17, start=1):

    text = row.get_text(
        " ",
        strip=True
    )

    # -----------------------------
    # TANGGAL
    # -----------------------------
    tanggal = parse_tanggal_u17(text)

    # -----------------------------
    # PESERTA TIM
    # -----------------------------
    title = row.select_one(
        "h4.sp-event-title"
    )

    peserta_tim = (
        title.get_text(" ", strip=True)
        if title
        else None
    )

    # -----------------------------
    # SKOR
    # -----------------------------
    skor = None

    pola_skor = re.search(
        r'\b(\d+)\s*-\s*(\d+)\b',
        text
    )

    if pola_skor:
        skor = (
            f"{pola_skor.group(1)}:"
            f"{pola_skor.group(2)}"
        )

    # -----------------------------
    # VENUE
    # -----------------------------
    # Ambil teks sebelum peserta
    # untuk menghindari nama tim ikut terbaca

    text_sebelum_tim = text

    if peserta_tim:
        text_sebelum_tim = text.split(
            peserta_tim
        )[0]

    # Hapus bagian tanggal, skor,
    # status, dan nama kompetisi
    venue_text = re.sub(
        r'\d{1,2}\s+'
        r'(?:Januari|Februari|Maret|April|Mei|Juni|Juli|'
        r'Agustus|September|Oktober|November|Desember)'
        r'\s+\d{4}',
        '',
        text_sebelum_tim,
        flags=re.IGNORECASE
    )

    venue_text = re.sub(
        r'Selesai',
        '',
        venue_text,
        flags=re.IGNORECASE
    )

    venue_text = re.sub(
        r'\b\d+\s*-\s*\d+\b',
        '',
        venue_text
    )

    venue_text = re.sub(
        r'Final 1st Pl\.|Final 3rd Pl\.|'
        r'Semifinal|Perempat Final|8 Besar|'
        r'16 Besar|Grup [A-Z]',
        '',
        venue_text,
        flags=re.IGNORECASE
    )

    venue_text = re.sub(
        r'Piala Soeratin U-17',
        '',
        venue_text,
        flags=re.IGNORECASE
    )

    venue_text = re.sub(
        r'\bN/A\b',
        '',
        venue_text,
        flags=re.IGNORECASE
    )

    venue = venue_text.strip()

    data_soeratin.append({
        'id_event': f'SOERATIN-U17-{i:03d}',
        'nama_event': 'Piala Soeratin U-17',
        'jenis_olahraga': 'Sepak Bola',
        'tanggal_mulai': tanggal,
        'tanggal_selesai': tanggal,
        'nama_venue': venue,
        'level_event': 'Regional',
        'peserta_tim': peserta_tim,
        'hasil_skor': skor,
        'sumber': url_u17
    })


df_soeratin_u17 = pd.DataFrame(
    data_soeratin
)

df_soeratin_u17.head()

,id_event,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
0,SOERATIN-U17-001,Piala Soeratin U-17,Sepak Bola,2023-12-03,2023-12-03,"Minggu, Stadion Canda Bhirawa",Regional,Deltras Sidoarjo U-17 VS Persedikab Kediri U-17,0:4,https://pssijatim.com/page-piala-soeratin-u-17
1,SOERATIN-U17-002,Piala Soeratin U-17,Sepak Bola,2023-12-03,2023-12-03,"Minggu, Stadion Canda Bhirawa",Regional,Sinar Harapan U-17 VS Perseta Tulungagung U-17,3:2,https://pssijatim.com/page-piala-soeratin-u-17
2,SOERATIN-U17-003,Piala Soeratin U-17,Sepak Bola,2023-12-01,2023-12-01,"Jumat, Stadion Canda Bhirawa",Regional,Perseta Tulungagung U-17 VS Persedikab Kediri U-17,1:3,https://pssijatim.com/page-piala-soeratin-u-17
3,SOERATIN-U17-004,Piala Soeratin U-17,Sepak Bola,2023-12-01,2023-12-01,"Jumat, Stadion Canda Bhirawa",Regional,Deltras Sidoarjo U-17 VS Sinar Harapan U-17,1:0,https://pssijatim.com/page-piala-soeratin-u-17
4,SOERATIN-U17-005,Piala Soeratin U-17,Sepak Bola,2023-11-27,2023-11-27,"Senin, Stadion Soeprijadi Blitar",Regional,PSBR Kota Blitar U-17 VS NZR Sumbersari U-17,2:1,https://pssijatim.com/page-piala-soeratin-u-17

In [ ]:
print(
    "Jumlah pertandingan:",
    len(df_soeratin_u17)
)

print(
    "\nTahun:"
)

print(
    df_soeratin_u17[
        'tanggal_mulai'
    ].dt.year.value_counts().sort_index()
)

Jumlah pertandingan: 545

Tahun:
tanggal_mulai
2023    124
2024    136
2025    149
2026    136
Name: count, dtype: int64

In [ ]:
df_soeratin_u17[
    [
        'tanggal_mulai',
        'nama_venue',
        'peserta_tim',
        'hasil_skor'
    ]
].head(20)

,tanggal_mulai,nama_venue,peserta_tim,hasil_skor
0,2023-12-03,"Minggu, Stadion Canda Bhirawa",Deltras Sidoarjo U-17 VS Persedikab Kediri U-17,0:4
1,2023-12-03,"Minggu, Stadion Canda Bhirawa",Sinar Harapan U-17 VS Perseta Tulungagung U-17,3:2
2,2023-12-01,"Jumat, Stadion Canda Bhirawa",Perseta Tulungagung U-17 VS Persedikab Kediri U-17,1:3
3,2023-12-01,"Jumat, Stadion Canda Bhirawa",Deltras Sidoarjo U-17 VS Sinar Harapan U-17,1:0
4,2023-11-27,"Senin, Stadion Soeprijadi Blitar",PSBR Kota Blitar U-17 VS NZR Sumbersari U-17,2:1
5,2023-11-27,"Senin, Stadion Jenggolo Sidoarjo",Sinar Harapan U-17 VS PSMP Mojokerto U-17,1:2
6,2023-11-27,"Senin, Stadion Soeprijadi Blitar",Arema FC U-17 VS Perseta Tulungagung U-17,1:2
7,2023-11-27,"Senin, Stadion Jenggolo Sidoarjo",Persebaya Surabaya U-17 VS Deltras Sidoarjo U-17,1:2
8,2023-11-25,"Sabtu, Stadion Jenggolo Sidoarjo",Deltras Sidoarjo U-17 VS Persikoba Batu U-17,4:2
9,2023-11-25,"Sabtu, Stadion Soeprijadi Blitar",Perseta Tulungagung U-17 VS Persipro 1954 U-17,2:1
10,2023-11-25,"Sabtu, Stadion Soeprijadi Blitar",NZR Sumbersari U-17 VS Persedikab Kediri U-17,0:1
11,2023-11-25,"Sabtu, Stadion Jenggolo Sidoarjo",PSMP Mojokerto U-17 VS Persegres Putra U-17,0:1
12,2023-11-24,"Jumat, Stadion Jenggolo Sidoarjo",Persegres Putra U-17 VS Sinar Harapan U-17,2:4
13,2023-11-24,"Jumat, Stadion Soeprijadi Blitar",Persedikab Kediri U-17 VS PSBR Kota Blitar U-17,2:0
14,2023-11-24,"Jumat, Stadion Soeprijadi Blitar",Persipro 1954 U-17 VS Arema FC U-17,3:0
15,2023-11-24,"Jumat, Stadion Jenggolo Sidoarjo",Persikoba Batu U-17 VS Persebaya Surabaya U-17,1:3
16,2023-11-20,"Senin, Lapangan Brigif 2 Marinir SDA",Arema FC U-17 VS Inter Kediri U-17,3:1
17,2023-11-20,"Senin, Lapangan Brigif 2 Marinir SDA",Persebo Muda 1964 U-17 VS Deltras Sidoarjo U-17,0:2
18,2023-11-19,"Minggu, Lapangan Brigif 2 Marinir SDA",Arema FC U-17 VS Persebo Muda 1964 U-17,3:0
19,2023-11-19,"Minggu, Lapangan Brigif 2 Marinir SDA",Inter Kediri U-17 VS Deltras Sidoarjo U-17,0:2

In [ ]:
df_soeratin_u17[
    'nama_venue'
].value_counts()

nama_venue
Sabtu,      Gelora Panataran Blitar                                  8
Kamis,      Stadion Soeprijadi Blitar                                7
Sabtu,      Stadion Canda Bhirawa                                    6
Sabtu,      Jember Sport Garden                                      6
Sabtu,      Stadion Soeprijadi Blitar                                6
                                                                    ..
Kamis,    adu penalti : [  ]   Stadion Untung Surapati               1
Minggu,    32 Besar  Gelora Ratu Pamelingan                          1
Minggu,    adu penalti : [  ] 32 Besar  Stadion Soeprijadi Blitar    1
Minggu,    adu penalti : [  ] 32 Besar  Gelora Ratu Pamelingan       1
Minggu,    32 Besar  Stadion Soeprijadi Blitar                       1
Name: count, Length: 253, dtype: int64

In [ ]:
for no, row in enumerate(rows_u17[:5], start=1):
    print(f"\n========== PERTANDINGAN {no} ==========")

    for i, td in enumerate(row.find_all('td')):
        print(f"TD {i}: {td.get_text(' | ', strip=True)}")

========== PERTANDINGAN 1 ==========
TD 0: Minggu, 3 Desember 2023 | Selesai | 0 | - | 4 | Final 1st Pl. Piala Soeratin U-17 | Stadion Canda Bhirawa | N/A | Deltras Sidoarjo U-17 VS Persedikab Kediri U-17

========== PERTANDINGAN 2 ==========
TD 0: Minggu, 3 Desember 2023 | Selesai | 3 | - | 2 | Final 3rd Pl. Piala Soeratin U-17 | Stadion Canda Bhirawa | N/A | Sinar Harapan U-17 VS Perseta Tulungagung U-17

========== PERTANDINGAN 3 ==========
TD 0: Jumat, 1 Desember 2023 | Selesai | 1 | - | 3 | Semifinal Piala Soeratin U-17 | Stadion Canda Bhirawa | N/A | Perseta Tulungagung U-17 VS Persedikab Kediri U-17

========== PERTANDINGAN 4 ==========
TD 0: Jumat, 1 Desember 2023 | Selesai | 1 | - | 0 | Semifinal Piala Soeratin U-17 | Stadion Canda Bhirawa | N/A | Deltras Sidoarjo U-17 VS Sinar Harapan U-17

========== PERTANDINGAN 5 ==========
TD 0: Senin, 27 November 2023 | Selesai | 2 | - | 1 | Grup J Piala Soeratin U-17 | Stadion Soeprijadi Blitar | N/A | PSBR Kota Blitar U-17 VS NZR Sumbersari U-17

In [ ]:
def ekstrak_venue_soeratin(row):
    text = row.get_text(" ", strip=True)

    # Ambil bagian setelah nama kompetisi
    pola = re.search(
        r'Piala Soeratin U-17\s+(.*?)\s+N/A\b',
        text,
        re.IGNORECASE
    )

    if pola:
        return pola.group(1).strip()

    return None

In [ ]:
for i, row in enumerate(rows_u17[:20], start=1):
    print(i, "=>", ekstrak_venue_soeratin(row))

1 => Stadion Canda Bhirawa
2 => Stadion Canda Bhirawa
3 => Stadion Canda Bhirawa
4 => Stadion Canda Bhirawa
5 => Stadion Soeprijadi Blitar
6 => Stadion Jenggolo Sidoarjo
7 => Stadion Soeprijadi Blitar
8 => Stadion Jenggolo Sidoarjo
9 => Stadion Jenggolo Sidoarjo
10 => Stadion Soeprijadi Blitar
11 => Stadion Soeprijadi Blitar
12 => Stadion Jenggolo Sidoarjo
13 => Stadion Jenggolo Sidoarjo
14 => Stadion Soeprijadi Blitar
15 => Stadion Soeprijadi Blitar
16 => Stadion Jenggolo Sidoarjo
17 => Lapangan Brigif 2 Marinir SDA
18 => Lapangan Brigif 2 Marinir SDA
19 => Lapangan Brigif 2 Marinir SDA
20 => Lapangan Brigif 2 Marinir SDA

In [ ]:
data_soeratin = []

for i, row in enumerate(rows_u17, start=1):

    text = row.get_text(" ", strip=True)

    # Tanggal
    tanggal = parse_tanggal_u17(text)

    # Peserta
    title = row.select_one("h4.sp-event-title")
    peserta_tim = (
        title.get_text(" ", strip=True)
        if title else None
    )

    # Skor
    skor = None
    pola_skor = re.search(r'\b(\d+)\s*-\s*(\d+)\b', text)

    if pola_skor:
        skor = f"{pola_skor.group(1)}:{pola_skor.group(2)}"

    # Venue
    venue = ekstrak_venue_soeratin(row)

    data_soeratin.append({
        'id_event': f'SOERATIN-U17-{i:03d}',
        'nama_event': 'Piala Soeratin U-17',
        'jenis_olahraga': 'Sepak Bola',
        'tanggal_mulai': tanggal,
        'tanggal_selesai': tanggal,
        'nama_venue': venue,
        'level_event': None,
        'peserta_tim': peserta_tim,
        'hasil_skor': skor,
        'sumber': url_u17
    })

df_soeratin_u17 = pd.DataFrame(data_soeratin)

In [ ]:
print(df_soeratin_u17.shape)

print(
    df_soeratin_u17['nama_venue']
    .value_counts()
    .head(30)
)

display(
    df_soeratin_u17[
        ['tanggal_mulai', 'nama_venue', 'peserta_tim', 'hasil_skor']
    ].head(20)
)

(545, 10)
nama_venue
Stadion Soeprijadi Blitar              37
Stadion Canda Bhirawa                  32
Stadion Jenggolo Sidoarjo              29
Jember Sport Garden                    28
Gelora Panataran Blitar                28
Lapangan Ngeronggo Kediri              21
Lapangan Polda Jatim                   20
Stadion Brawijaya Kediri               20
Stadion Mini Gayam                     20
Stadion Surajaya Lamongan              18
Stadion Semeru Lumajang                16
Stadion Mini Dolok Gede, Bojonegoro    16
Stadion Diponegoro Banyuwangi          15
Stadion Untung Surapati                13
Stadion Kodam V Brawijaya              12
Lapangan Agro Kota Batu                12
Lapangan Gajah Mada, Lamongan          12
Stadion Brantas Kota Batu              12
Lapangan ABC Surabaya                  11
Stadion Jala Krida AAL Surabaya        10
Lapangan Yonzipur Kepanjen             10
Blayu Training Ground                  10
Stadion Plumbon Pandaan, Pasuruan      10
Stadion Pogar Pasuruan                 10
Gelora Ratu Pamelingan                  8
Gelora Muhammad Saleh, Situbondo        7
Stadion Ketonggo Ngawi                  7
Lapangan CJI Samsung Pasuruan           6
Stadion Bayuangga Probolinggo           6
Lapangan Kenongo Tulangan SDA           6
Name: count, dtype: int64

,tanggal_mulai,nama_venue,peserta_tim,hasil_skor
0,2023-12-03,Stadion Canda Bhirawa,Deltras Sidoarjo U-17 VS Persedikab Kediri U-17,0:4
1,2023-12-03,Stadion Canda Bhirawa,Sinar Harapan U-17 VS Perseta Tulungagung U-17,3:2
2,2023-12-01,Stadion Canda Bhirawa,Perseta Tulungagung U-17 VS Persedikab Kediri U-17,1:3
3,2023-12-01,Stadion Canda Bhirawa,Deltras Sidoarjo U-17 VS Sinar Harapan U-17,1:0
4,2023-11-27,Stadion Soeprijadi Blitar,PSBR Kota Blitar U-17 VS NZR Sumbersari U-17,2:1
5,2023-11-27,Stadion Jenggolo Sidoarjo,Sinar Harapan U-17 VS PSMP Mojokerto U-17,1:2
6,2023-11-27,Stadion Soeprijadi Blitar,Arema FC U-17 VS Perseta Tulungagung U-17,1:2
7,2023-11-27,Stadion Jenggolo Sidoarjo,Persebaya Surabaya U-17 VS Deltras Sidoarjo U-17,1:2
8,2023-11-25,Stadion Jenggolo Sidoarjo,Deltras Sidoarjo U-17 VS Persikoba Batu U-17,4:2
9,2023-11-25,Stadion Soeprijadi Blitar,Perseta Tulungagung U-17 VS Persipro 1954 U-17,2:1
10,2023-11-25,Stadion Soeprijadi Blitar,NZR Sumbersari U-17 VS Persedikab Kediri U-17,0:1
11,2023-11-25,Stadion Jenggolo Sidoarjo,PSMP Mojokerto U-17 VS Persegres Putra U-17,0:1
12,2023-11-24,Stadion Jenggolo Sidoarjo,Persegres Putra U-17 VS Sinar Harapan U-17,2:4
13,2023-11-24,Stadion Soeprijadi Blitar,Persedikab Kediri U-17 VS PSBR Kota Blitar U-17,2:0
14,2023-11-24,Stadion Soeprijadi Blitar,Persipro 1954 U-17 VS Arema FC U-17,3:0
15,2023-11-24,Stadion Jenggolo Sidoarjo,Persikoba Batu U-17 VS Persebaya Surabaya U-17,1:3
16,2023-11-20,Lapangan Brigif 2 Marinir SDA,Arema FC U-17 VS Inter Kediri U-17,3:1
17,2023-11-20,Lapangan Brigif 2 Marinir SDA,Persebo Muda 1964 U-17 VS Deltras Sidoarjo U-17,0:2
18,2023-11-19,Lapangan Brigif 2 Marinir SDA,Arema FC U-17 VS Persebo Muda 1964 U-17,3:0
19,2023-11-19,Lapangan Brigif 2 Marinir SDA,Inter Kediri U-17 VS Deltras Sidoarjo U-17,0:2

In [ ]:
venue_soeratin = (
    df_soeratin_u17['nama_venue']
    .value_counts()
    .rename_axis('nama_venue')
    .reset_index(name='jumlah_pertandingan')
)

display(venue_soeratin)

                                         nama_venue  jumlah_pertandingan
0                         Stadion Soeprijadi Blitar                   37
1                             Stadion Canda Bhirawa                   32
2                         Stadion Jenggolo Sidoarjo                   29
3                               Jember Sport Garden                   28
4                           Gelora Panataran Blitar                   28
5                         Lapangan Ngeronggo Kediri                   21
6                              Lapangan Polda Jatim                   20
7                          Stadion Brawijaya Kediri                   20
8                                Stadion Mini Gayam                   20
9                         Stadion Surajaya Lamongan                   18
10                          Stadion Semeru Lumajang                   16
11              Stadion Mini Dolok Gede, Bojonegoro                   16
12                    Stadion Diponegoro Banyuwangi                   15
13                          Stadion Untung Surapati                   13
14                        Stadion Kodam V Brawijaya                   12
15                          Lapangan Agro Kota Batu                   12
16                    Lapangan Gajah Mada, Lamongan                   12
17                        Stadion Brantas Kota Batu                   12
18                            Lapangan ABC Surabaya                   11
19                  Stadion Jala Krida AAL Surabaya                   10
20                       Lapangan Yonzipur Kepanjen                   10
21                            Blayu Training Ground                   10
22                Stadion Plumbon Pandaan, Pasuruan                   10
23                           Stadion Pogar Pasuruan                   10
24                           Gelora Ratu Pamelingan                    8
25                 Gelora Muhammad Saleh, Situbondo                    7
26                           Stadion Ketonggo Ngawi                    7
27                    Lapangan CJI Samsung Pasuruan                    6
28                    Stadion Bayuangga Probolinggo                    6
29                    Lapangan Kenongo Tulangan SDA                    6
30                    Lapangan Brigif 2 Marinir SDA                    6
31                      Lapangan Brigif Marinir SDA                    6
32                         Stadion Gelora Bangkalan                    6
33                          Lapangan Kalisat Jember                    6
34                         Stadion Rejoagung Kediri                    6
35                          Stadion Merdeka Jombang                    6
36                             Stadion Semen Gresik                    6
37                Lapangan yonkav 3 tank, Singosari                    6
38                Stadion Singojoyo, Kalisat Jember                    6
39                              Stadion Menak Sopal                    6
40                           Lapangan Thor Surabaya                    4
41                    Lap. Pusdik Arhanud Kota Batu                    4
42                       Stadion J. A. Yani Arhanud                    4
43  Lapangan Penegak Sapta Marga, Kostrad Singosari                    4
44                    Gelora Bung Sumardji, Nganjuk                    3
45                    Madura United Training Ground                    2
46                    Stadion Anjuk Ladang, Nganjuk                    1
47                         Lapangan Deltras Academy                    1

In [ ]:
venue_surabaya = [
    'Lapangan ABC Surabaya',
    'Stadion Jala Krida AAL Surabaya',
    'Lapangan Thor Surabaya'
]

soeratin_surabaya = df_soeratin_u17[
    df_soeratin_u17['nama_venue'].isin(venue_surabaya)
].copy()

print("Jumlah pertandingan Soeratin di venue Surabaya:",
      len(soeratin_surabaya))

display(
    soeratin_surabaya[
        [
            'tanggal_mulai',
            'nama_venue',
            'peserta_tim',
            'hasil_skor'
        ]
    ].sort_values('tanggal_mulai')
)

Jumlah pertandingan Soeratin di venue Surabaya: 25

,tanggal_mulai,nama_venue,peserta_tim,hasil_skor
106,2023-11-08,Stadion Jala Krida AAL Surabaya,Perseba Bangkalan U-17 VS Persegres Putra U-17,1:2
117,2023-11-08,Stadion Jala Krida AAL Surabaya,Persebaya Surabaya U-17 VS Gestra FC U-17,3:1
80,2023-11-09,Stadion Jala Krida AAL Surabaya,Persegres Putra U-17 VS Persebaya Surabaya U-17,0:4
90,2023-11-09,Stadion Jala Krida AAL Surabaya,Gestra FC U-17 VS Perseba Bangkalan U-17,1:1
63,2023-11-11,Stadion Jala Krida AAL Surabaya,Persegres Putra U-17 VS Gestra FC U-17,2:0
68,2023-11-11,Stadion Jala Krida AAL Surabaya,Persebaya Surabaya U-17 VS Perseba Bangkalan U-17,5:1
152,2024-11-25,Stadion Jala Krida AAL Surabaya,Persibo Bojonegoro VS Persida Sidoarjo,0:4
151,2024-11-25,Stadion Jala Krida AAL Surabaya,Persema Malang VS Persekabpas,1:1
140,2024-11-26,Stadion Jala Krida AAL Surabaya,Deltras VS PSPK Pasuruan,2:1
145,2024-11-26,Stadion Jala Krida AAL Surabaya,Persedikab VS PSBI Blitar,4:0
126,2024-12-04,Lapangan Thor Surabaya,Malang United VS Mojosari Putra,2:4
127,2024-12-04,Lapangan Thor Surabaya,Persedikab Kediri VS Bhayangkara FC,1:1
125,2024-12-05,Lapangan Thor Surabaya,Bhayangkara FC VS Malang United,3:3
124,2024-12-05,Lapangan Thor Surabaya,Persedikab Kediri VS Mojosari Putra,1:0
405,2025-07-09,Lapangan ABC Surabaya,Persesa Sampang VS Persepam Pamekasan,0:2
399,2025-07-09,Lapangan ABC Surabaya,Persem Mojokerto VS Perseba Bangkalan,2:1
385,2025-07-10,Lapangan ABC Surabaya,Persem Mojokerto VS Persesa Sampang,2:3
390,2025-07-10,Lapangan ABC Surabaya,Perseba Bangkalan VS Persebaya Surabaya,0:10
353,2025-07-12,Lapangan ABC Surabaya,Persepam Pamekasan VS Perseba Bangkalan,6:0
377,2025-07-12,Lapangan ABC Surabaya,Persebaya Surabaya VS Persem Mojokerto,7:0
335,2025-07-13,Lapangan ABC Surabaya,Persesa Sampang VS Persebaya Surabaya,0:2
337,2025-07-13,Lapangan ABC Surabaya,Persepam Pamekasan VS Persem Mojokerto,3:1
295,2025-07-15,Lapangan ABC Surabaya,Persebaya Surabaya VS Persepam Pamekasan,2:0
318,2025-07-15,Lapangan ABC Surabaya,Perseba Bangkalan VS Persesa Sampang,1:4
278,2025-07-20,Lapangan ABC Surabaya,Persebaya Surabaya VS Persegres Putra,5:0

In [ ]:
df_soeratin_u17[
    df_soeratin_u17['nama_venue'].str.contains(
        r'Gelora|Bung Tomo|Nopember|November',
        case=False,
        na=False
    )
]['nama_venue'].value_counts()

nama_venue
Gelora Panataran Blitar             28
Gelora Ratu Pamelingan               8
Gelora Muhammad Saleh, Situbondo     7
Stadion Gelora Bangkalan             6
Gelora Bung Sumardji, Nganjuk        3
Name: count, dtype: int64

In [ ]:
venue_tambahan = soeratin_surabaya[
    ['nama_venue']
].drop_duplicates().copy()

display(venue_tambahan)

                          nama_venue
63   Stadion Jala Krida AAL Surabaya
124           Lapangan Thor Surabaya
278            Lapangan ABC Surabaya

In [ ]:
master_venue_event = pd.DataFrame({
    'id_venue': ['V029', 'V030', 'V031'],
    'nama_venue': [
        'Lapangan ABC Surabaya',
        'Stadion Jala Krida AAL Surabaya',
        'Lapangan Thor Surabaya'
    ],
    'jenis_olahraga': ['Sepak Bola'] * 3,
    'kecamatan': [None] * 3,
    'kelurahan': [None] * 3,
    'alamatlokasi': [None] * 3,
    'luas': [None] * 3
})

In [ ]:
master_venue_final = pd.concat(
    [master_venue, master_venue_event],
    ignore_index=True
)

print("Jumlah master venue:", len(master_venue_final))

display(master_venue_final.tail())

Jumlah master venue: 31

/tmp/ipykernel_3409/807741238.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  master_venue_final = pd.concat(

,id_venue,nama_fasilitas_olahraga,jenis_olahraga,kecamatan,kelurahan,alamatlokasi,luas,nama_venue
26,V027,Lapangan Tennis Sambiroto,Tenis,Kec. Sambikerep,Kel. Sambikerep,Lapangan Tennis Sambiroto,504.000,Lapangan Tennis Sambiroto
27,V028,Stadion Indoor Gelora Bung Tomo,Futsal,Kec. Pakal,Kel. Pakal,GELORA BUNG TOMO SURABAYA,31.826,Stadion Indoor Gelora Bung Tomo
28,V029,NaN,Sepak Bola,None,None,None,NaN,Lapangan ABC Surabaya
29,V030,NaN,Sepak Bola,None,None,None,NaN,Stadion Jala Krida AAL Surabaya
30,V031,NaN,Sepak Bola,None,None,None,NaN,Lapangan Thor Surabaya

In [ ]:
soeratin_surabaya['tahun'] = (
    soeratin_surabaya['tanggal_mulai'].dt.year
)

display(
    pd.crosstab(
        soeratin_surabaya['nama_venue'],
        soeratin_surabaya['tahun']
    )
)

tahun                            2023  2024  2025
nama_venue
Lapangan ABC Surabaya               0     0    11
Lapangan Thor Surabaya              0     4     0
Stadion Jala Krida AAL Surabaya     6     4     0

In [ ]:
# Pastikan tanggal dalam format yang rapi
df_soeratin_u17['tanggal_mulai'] = pd.to_datetime(
    df_soeratin_u17['tanggal_mulai'],
    errors='coerce'
)

df_soeratin_u17['tanggal_selesai'] = pd.to_datetime(
    df_soeratin_u17['tanggal_selesai'],
    errors='coerce'
)

print("Tanggal Soeratin U-17 sudah dirapikan.")

File berhasil dibuat.
Ukuran: (545, 10)

### 6.4 Scraping Piala Soeratin U-13

In [ ]:
url_u13 = "https://pssijatim.com/page-piala-soeratin-u-13"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(
    url_u13,
    headers=headers,
    timeout=60
)

response.raise_for_status()

soup_u13 = BeautifulSoup(
    response.text,
    "html.parser"
)

print("Status:", response.status_code)

Status: 200

In [ ]:
rows_u13 = soup_u13.select("tr.sp-row.sp-post")

print("Jumlah baris U-13:", len(rows_u13))

Jumlah baris U-13: 135

In [ ]:
print(rows_u13[0].prettify())

<tr class="sp-row sp-post alternate" itemscope="" itemtype="http://schema.org/SportsEvent">
 <td>
  <span class="team-logo logo-odd" itemprop="competitor" itemscope="" itemtype="http://schema.org/SportsTeam" title="PS HW Babat">
   <meta content="PS HW Babat" itemprop="name"/>
   <a content="https://www.pssijatim.com/team/ps-hw-babat" href="https://www.pssijatim.com/team/ps-hw-babat" itemprop="url">
    <noscript>
     <img alt="PS HW Babat" class="attachment-sportspress-fit-icon size-sportspress-fit-icon wp-post-image" data-attachment-id="15472" data-comments-opened="0" data-image-caption="" data-image-description="" data-image-meta='{"aperture":"0","credit":"","camera":"","caption":"","created_timestamp":"0","copyright":"","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0","lens":""}' data-image-title="soccerFCC" data-large-file="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2023/11/soccerFCC.png?fit=536%2C465&amp;ssl=1" data-orig-file="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2023/11/soccerFCC.png?fit=536%2C465&amp;ssl=1" data-orig-size="536,465" data-permalink="https://www.pssijatim.com/soccerfcc" decoding="async" height="111" itemprop="logo" sizes="(max-width: 128px) 100vw, 128px" src="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2023/11/soccerFCC.png?fit=128%2C111&amp;ssl=1" srcset="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2023/11/soccerFCC.png 536w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2023/11/soccerFCC-300x260.png 300w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2023/11/soccerFCC-128x111.png 128w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2023/11/soccerFCC-32x28.png 32w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2023/11/soccerFCC-138x120.png 138w" title="PS HW Babat" width="128"/>
    </noscript>
    <img alt="PS HW Babat" class="lazyload attachment-sportspress-fit-icon size-sportspress-fit-icon wp-post-image" data-attachment-id="15472" data-comments-opened="0" data-image-caption="" data-image-description="" data-image-meta='{"aperture":"0","credit":"","camera":"","caption":"","created_timestamp":"0","copyright":"","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0","lens":""}' data-image-title="soccerFCC" data-large-file="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2023/11/soccerFCC.png?fit=536%2C465&amp;ssl=1" data-orig-file="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2023/11/soccerFCC.png?fit=536%2C465&amp;ssl=1" data-orig-size="536,465" data-permalink="https://www.pssijatim.com/soccerfcc" data-sizes="(max-width: 128px) 100vw, 128px" data-src="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2023/11/soccerFCC.png?fit=128%2C111&amp;ssl=1" data-srcset="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2023/11/soccerFCC.png 536w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2023/11/soccerFCC-300x260.png 300w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2023/11/soccerFCC-128x111.png 128w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2023/11/soccerFCC-32x28.png 32w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2023/11/soccerFCC-138x120.png 138w" decoding="async" height="111" itemprop="logo" src="data:image/svg+xml,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%20128%20111%22%3E%3C/svg%3E" title="PS HW Babat" width="128"/>
   </a>
  </span>
  <span class="team-logo logo-even" itemprop="competitor" itemscope="" itemtype="http://schema.org/SportsTeam" title="Turangga FC">
   <meta content="Turangga FC" itemprop="name"/>
   <a content="https://www.pssijatim.com/team/turangga-fc" href="https://www.pssijatim.com/team/turangga-fc" itemprop="url">
    <noscript>
     <img alt="Turangga FC" class="attachment-sportspress-fit-icon size-sportspress-fit-icon wp-post-image" data-attachment-id="21159" data-comments-opened="0" data-image-caption="" data-image-description="" data-image-meta='{"aperture":"0","credit":"","camera":"","caption":"","created_timestamp":"0","copyright":"","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0","alt":""}' data-image-title="Grassroots pssi-jatim" data-large-file="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim.png?fit=500%2C500&amp;ssl=1" data-orig-file="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim.png?fit=500%2C500&amp;ssl=1" data-orig-size="500,500" data-permalink="https://www.pssijatim.com/team/akademi-persela/grassroots-pssi-jatim" decoding="async" height="128" itemprop="logo" sizes="(max-width: 128px) 100vw, 128px" src="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim.png?fit=128%2C128&amp;ssl=1" srcset="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim.png 500w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim-300x300.png 300w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim-150x150.png 150w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim-128x128.png 128w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim-32x32.png 32w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim-75x75.png 75w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim-350x350.png 350w" title="Turangga FC" width="128"/>
    </noscript>
    <img alt="Turangga FC" class="lazyload attachment-sportspress-fit-icon size-sportspress-fit-icon wp-post-image" data-attachment-id="21159" data-comments-opened="0" data-image-caption="" data-image-description="" data-image-meta='{"aperture":"0","credit":"","camera":"","caption":"","created_timestamp":"0","copyright":"","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0","alt":""}' data-image-title="Grassroots pssi-jatim" data-large-file="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim.png?fit=500%2C500&amp;ssl=1" data-orig-file="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim.png?fit=500%2C500&amp;ssl=1" data-orig-size="500,500" data-permalink="https://www.pssijatim.com/team/akademi-persela/grassroots-pssi-jatim" data-sizes="(max-width: 128px) 100vw, 128px" data-src="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim.png?fit=128%2C128&amp;ssl=1" data-srcset="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim.png 500w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim-300x300.png 300w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim-150x150.png 150w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim-128x128.png 128w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim-32x32.png 32w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim-75x75.png 75w, https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2026/06/Grassroots-pssi-jatim-350x350.png 350w" decoding="async" height="128" itemprop="logo" src="data:image/svg+xml,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%20128%20128%22%3E%3C/svg%3E" title="Turangga FC" width="128"/>
   </a>
  </span>
  <time class="sp-event-date" content="2024-01-08T16:00+07:00" datetime="2024-01-08 16:00:27" itemprop="startDate">
   <a content="https://www.pssijatim.com/match/ps-hw-babat-vs-turangga-fc" href="https://www.pssijatim.com/match/ps-hw-babat-vs-turangga-fc" itemprop="url">
    Senin, 8 Januari 2024
   </a>
   <div class="blink-status">
    <span id="selesai-inner">
     Selesai
    </span>
   </div>
  </time>
  <h5 class="sp-event-results">
   <a content="https://www.pssijatim.com/match/ps-hw-babat-vs-turangga-fc" href="https://www.pssijatim.com/match/ps-hw-babat-vs-turangga-fc" itemprop="url">
    <span class="sp-result ok">
     16:00 WIB
    </span>
   </a>
  </h5>
  <div class="sp-event-league">
   Grup B Piala Soeratin U-13
  </div>
  <div class="sp-event-venue" itemprop="location" itemscope="" itemtype="http://schema.org/Place">
   <div itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">
    <div id="icon-std">
     <noscript>
      <img data-recalc-dims="1" decoding="async" src="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2025/12/stadion.png?ssl=1"/>
     </noscript>
     <img class="lazyload" data-recalc-dims="1" data-src="https://i0.wp.com/www.pssijatim.com/wp-content/uploads/2025/12/stadion.png?ssl=1" decoding="async" src="data:image/svg+xml,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%20210%20140%22%3E%3C/svg%3E"/>
    </div>
    <span class="sp-venue-tooltip" data-tooltip="Lapangan Secaba Jember" title="Lapangan Secaba Jember">
     Lapangan Secaba Jember
    </span>
   </div>
  </div>
  <div class="sp-event-venue" itemprop="location" itemscope="" itemtype="http://schema.org/Place" style="display:none;">
   <div itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">
    N/A
   </div>
  </div>
  <h4 class="sp-event-title" itemprop="name">
   <a content="https://www.pssijatim.com/match/ps-hw-babat-vs-turangga-fc" href="https://www.pssijatim.com/match/ps-hw-babat-vs-turangga-fc" itemprop="url">
    PS HW Babat VS Turangga FC
   </a>
  </h4>
 </td>
</tr>

In [ ]:
for element in rows_u13[0].find_all(
    ["td", "th", "h4", "a", "span", "div"]
):
    print(
        element.name,
        element.get("class"),
        "=>",
        element.get_text(" ", strip=True)
    )

td None => Senin, 8 Januari 2024 Selesai 16:00 WIB Grup B Piala Soeratin U-13 Lapangan Secaba Jember N/A PS HW Babat VS Turangga FC
span ['team-logo', 'logo-odd'] =>
a None =>
span ['team-logo', 'logo-even'] =>
a None =>
a None => Senin, 8 Januari 2024
div ['blink-status'] => Selesai
span None => Selesai
a None => 16:00 WIB
span ['sp-result', 'ok'] => 16:00 WIB
div ['sp-event-league'] => Grup B Piala Soeratin U-13
div ['sp-event-venue'] => Lapangan Secaba Jember
div None => Lapangan Secaba Jember
div None =>
span ['sp-venue-tooltip'] => Lapangan Secaba Jember
div ['sp-event-venue'] => N/A
div None => N/A
h4 ['sp-event-title'] => PS HW Babat VS Turangga FC
a None => PS HW Babat VS Turangga FC

### 6.5 Ekstraksi dan pembersihan data U-13

In [ ]:
import requests
import re
import pandas as pd
from bs4 import BeautifulSoup

# =========================================================
# 1. URL
# =========================================================

url_u13 = "https://pssijatim.com/page-piala-soeratin-u-13"

headers = {
    "User-Agent": "Mozilla/5.0"
}

# =========================================================
# 2. REQUEST
# =========================================================

response = requests.get(
    url_u13,
    headers=headers,
    timeout=60
)

response.raise_for_status()

soup_u13 = BeautifulSoup(
    response.text,
    "html.parser"
)

rows_u13 = soup_u13.select(
    "tr.sp-row.sp-post"
)

print(
    f"U-13: ditemukan {len(rows_u13)} baris pertandingan"
)


# =========================================================
# 3. PEMETAAN BULAN INDONESIA
# =========================================================

bulan_indo = {
    "Januari": 1,
    "Februari": 2,
    "Maret": 3,
    "April": 4,
    "Mei": 5,
    "Juni": 6,
    "Juli": 7,
    "Agustus": 8,
    "September": 9,
    "Oktober": 10,
    "November": 11,
    "Desember": 12
}


# =========================================================
# 4. FUNGSI PARSE TANGGAL
# =========================================================

def parse_tanggal_u13(row):

    # Cari semua elemen <a>
    semua_a = row.find_all("a")

    for a in semua_a:

        text = a.get_text(
            " ",
            strip=True
        )

        # Contoh:
        # Senin, 8 Januari 2024
        match = re.search(
            r'(\d{1,2})\s+'
            r'(Januari|Februari|Maret|April|Mei|Juni|'
            r'Juli|Agustus|September|Oktober|November|Desember)'
            r'\s+(\d{4})',
            text,
            re.IGNORECASE
        )

        if match:

            hari = int(match.group(1))
            nama_bulan = match.group(2)
            tahun = int(match.group(3))

            # Samakan kapitalisasi
            nama_bulan = nama_bulan.capitalize()

            nomor_bulan = bulan_indo.get(
                nama_bulan
            )

            if nomor_bulan:

                return pd.Timestamp(
                    year=tahun,
                    month=nomor_bulan,
                    day=hari
                )

    return None


# =========================================================
# 5. SCRAPING
# =========================================================

data_u13 = []

for i, row in enumerate(
    rows_u13,
    start=1
):

    # -----------------------------------------------------
    # TANGGAL
    # -----------------------------------------------------

    tanggal = parse_tanggal_u13(row)


    # -----------------------------------------------------
    # PESERTA / TIM
    # -----------------------------------------------------

    title = row.select_one(
        "h4.sp-event-title"
    )

    if title:

        peserta_tim = title.get_text(
            " ",
            strip=True
        )

    else:

        peserta_tim = None


    # -----------------------------------------------------
    # VENUE
    # -----------------------------------------------------

    semua_venue = row.select(
        "div.sp-event-venue"
    )

    if semua_venue:

        # Ambil venue pertama
        # karena elemen kedua biasanya N/A
        venue = semua_venue[0].get_text(
            " ",
            strip=True
        )

    else:

        venue = None


    # -----------------------------------------------------
    # LEVEL / GRUP
    # -----------------------------------------------------

    league_element = row.select_one(
        "div.sp-event-league"
    )

    level_event = None

    if league_element:

        league_text = league_element.get_text(
            " ",
            strip=True
        )

        pola_grup = re.search(
            r'\bGrup\s+([A-Z])\b',
            league_text,
            re.IGNORECASE
        )

        if pola_grup:

            level_event = (
                "Grup "
                + pola_grup.group(1).upper()
            )


    # -----------------------------------------------------
    # HASIL SKOR
    # -----------------------------------------------------

    # span.sp-result.ok berisi waktu pertandingan,
    # bukan skor.
    #
    # Karena belum ada elemen skor yang ditemukan,
    # sementara hasil_skor = None.

    hasil_skor = None


    # -----------------------------------------------------
    # SIMPAN
    # -----------------------------------------------------

    data_u13.append({

        "id_event":
            f"SOERATIN-U13-{i:03d}",

        "nama_event":
            "Piala Soeratin U-13",

        "jenis_olahraga":
            "Sepak Bola",

        "tanggal_mulai":
            tanggal,

        "tanggal_selesai":
            tanggal,

        "nama_venue":
            venue,

        "level_event":
            level_event,

        "peserta_tim":
            peserta_tim,

        "hasil_skor":
            hasil_skor,

        "sumber":
            url_u13
    })


# =========================================================
# 6. DATAFRAME
# =========================================================

df_u13 = pd.DataFrame(
    data_u13
)


# =========================================================
# 7. PASTIKAN URUTAN KOLOM
# =========================================================

kolom_event = [
    "id_event",
    "nama_event",
    "jenis_olahraga",
    "tanggal_mulai",
    "tanggal_selesai",
    "nama_venue",
    "level_event",
    "peserta_tim",
    "hasil_skor",
    "sumber"
]

df_u13 = df_u13[
    kolom_event
]


# =========================================================
# 8. HASIL
# =========================================================

print(
    "Ukuran data U-13:",
    df_u13.shape
)

display(
    df_u13.head()
)

U-13: ditemukan 135 baris pertandingan
Ukuran data U-13: (135, 10)

,id_event,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
0,SOERATIN-U13-001,Piala Soeratin U-13,Sepak Bola,2024-01-08,2024-01-08,Lapangan Secaba Jember,Grup B,PS HW Babat VS Turangga FC,None,https://pssijatim.com/page-piala-soeratin-u-13
1,SOERATIN-U13-002,Piala Soeratin U-13,Sepak Bola,2024-01-08,2024-01-08,"Lapangan Yonif 509, Jember",Grup D,Bangkalan Soccer Academy VS Putra Manggala,None,https://pssijatim.com/page-piala-soeratin-u-13
2,SOERATIN-U13-003,Piala Soeratin U-13,Sepak Bola,2024-01-08,2024-01-08,"Lapangan Brigif Bawah, Jember",Grup H,Phoenix Mojokerto FC VS Argent Genteng,None,https://pssijatim.com/page-piala-soeratin-u-13
3,SOERATIN-U13-004,Piala Soeratin U-13,Sepak Bola,2024-01-08,2024-01-08,"Lapangan Brigif Atas, Jember",Grup F,Football Class VS Putra Jaya Blitar,None,https://pssijatim.com/page-piala-soeratin-u-13
4,SOERATIN-U13-005,Piala Soeratin U-13,Sepak Bola,2024-01-08,2024-01-08,Lapangan Secaba Jember,Grup C,Bima Putra Blitar VS Samudra FC,None,https://pssijatim.com/page-piala-soeratin-u-13

### 6.6 Scraping Piala Soeratin U-15

In [ ]:
import requests
from bs4 import BeautifulSoup

# =========================================================
# 1. URL U-15
# =========================================================

url_u15 = "https://pssijatim.com/page-piala-soeratin-u-15"

headers = {
    "User-Agent": "Mozilla/5.0"
}


# =========================================================
# 2. REQUEST
# =========================================================

response_u15 = requests.get(
    url_u15,
    headers=headers,
    timeout=60
)

response_u15.raise_for_status()

soup_u15 = BeautifulSoup(
    response_u15.text,
    "html.parser"
)


# =========================================================
# 3. AMBIL BARIS PERTANDINGAN
# =========================================================

rows_u15 = soup_u15.select(
    "tr.sp-row.sp-post"
)

print(
    f"U-15: ditemukan {len(rows_u15)} baris pertandingan"
)


# =========================================================
# 4. INSPEKSI HTML PERTANDINGAN PERTAMA
# =========================================================

row = rows_u15[0]

for element in row.find_all(
    ["td", "th", "h4", "a", "span", "div"]
):

    print(
        element.name,
        element.get("class"),
        "=>",
        element.get_text(
            " ",
            strip=True
        )
    )

U-15: ditemukan 144 baris pertandingan
td None => Senin, 8 Januari 2024 Selesai 16:00 WIB Grup H Piala Soeratin U-15 Lapangan Pagu Kediri N/A Bangkalan Soccer Academy VS Putra Soerapati
span ['team-logo', 'logo-odd'] =>
a None =>
span ['team-logo', 'logo-even'] =>
a None =>
a None => Senin, 8 Januari 2024
div ['blink-status'] => Selesai
span None => Selesai
a None => 16:00 WIB
span ['sp-result', 'ok'] => 16:00 WIB
div ['sp-event-league'] => Grup H Piala Soeratin U-15
div ['sp-event-venue'] => Lapangan Pagu Kediri
div None => Lapangan Pagu Kediri
div None =>
span ['sp-venue-tooltip'] => Lapangan Pagu Kediri
div ['sp-event-venue'] => N/A
div None => N/A
h4 ['sp-event-title'] => Bangkalan Soccer Academy VS Putra Soerapati
a None => Bangkalan Soccer Academy VS Putra Soerapati

### 6.7 Ekstraksi dan pembersihan data U-15

In [ ]:
import requests
import re
import pandas as pd
from bs4 import BeautifulSoup

# =========================================================
# 1. URL U-15
# =========================================================

url_u15 = "https://pssijatim.com/page-piala-soeratin-u-15"

headers = {
    "User-Agent": "Mozilla/5.0"
}


# =========================================================
# 2. REQUEST
# =========================================================

response_u15 = requests.get(
    url_u15,
    headers=headers,
    timeout=60
)

response_u15.raise_for_status()

soup_u15 = BeautifulSoup(
    response_u15.text,
    "html.parser"
)

rows_u15 = soup_u15.select(
    "tr.sp-row.sp-post"
)

print(
    f"U-15: ditemukan {len(rows_u15)} baris pertandingan"
)


# =========================================================
# 3. PEMETAAN BULAN INDONESIA
# =========================================================

bulan_indo = {
    "Januari": 1,
    "Februari": 2,
    "Maret": 3,
    "April": 4,
    "Mei": 5,
    "Juni": 6,
    "Juli": 7,
    "Agustus": 8,
    "September": 9,
    "Oktober": 10,
    "November": 11,
    "Desember": 12
}


# =========================================================
# 4. FUNGSI TANGGAL
# =========================================================

def parse_tanggal_u15(row):

    for a in row.find_all("a"):

        text = a.get_text(
            " ",
            strip=True
        )

        match = re.search(
            r'(\d{1,2})\s+'
            r'(Januari|Februari|Maret|April|Mei|Juni|'
            r'Juli|Agustus|September|Oktober|November|Desember)'
            r'\s+(\d{4})',
            text,
            re.IGNORECASE
        )

        if match:

            hari = int(match.group(1))

            nama_bulan = match.group(2).capitalize()

            tahun = int(match.group(3))

            nomor_bulan = bulan_indo[nama_bulan]

            return pd.Timestamp(
                year=tahun,
                month=nomor_bulan,
                day=hari
            )

    return None


# =========================================================
# 5. FUNGSI SKOR
# =========================================================

def parse_skor_u15(row):

    # Cari semua link dalam baris pertandingan
    semua_a = row.find_all("a")

    for a in semua_a:

        text = a.get_text(
            " ",
            strip=True
        )

        # Pola:
        # 3 - 2
        # 1 - 0
        # 2-1

        match = re.fullmatch(
            r'\s*(\d+)\s*-\s*(\d+)\s*',
            text
        )

        if match:

            return (
                f"{match.group(1)}:"
                f"{match.group(2)}"
            )

    return None


# =========================================================
# 6. FUNGSI LEVEL / BABAK
# =========================================================

def parse_level_u15(row):

    league_element = row.select_one(
        "div.sp-event-league"
    )

    if not league_element:
        return None

    league_text = league_element.get_text(
        " ",
        strip=True
    )

    # Contoh:
    # Grup H Piala Soeratin U-15
    # Final Juara 1 Piala Soeratin U-15
    # Final Juara 3 Piala Soeratin U-15

    league_text = re.sub(
        r'\s+Piala Soeratin U-15\s*$',
        '',
        league_text,
        flags=re.IGNORECASE
    )

    return league_text.strip()


# =========================================================
# 7. SCRAPING
# =========================================================

data_u15 = []

for i, row in enumerate(
    rows_u15,
    start=1
):

    # -----------------------------------------------------
    # TANGGAL
    # -----------------------------------------------------

    tanggal = parse_tanggal_u15(row)


    # -----------------------------------------------------
    # PESERTA / TIM
    # -----------------------------------------------------

    title = row.select_one(
        "h4.sp-event-title"
    )

    if title:

        peserta_tim = title.get_text(
            " ",
            strip=True
        )

    else:

        peserta_tim = None


    # -----------------------------------------------------
    # VENUE
    # -----------------------------------------------------

    semua_venue = row.select(
        "div.sp-event-venue"
    )

    if semua_venue:

        venue = semua_venue[0].get_text(
            " ",
            strip=True
        )

    else:

        venue = None


    # -----------------------------------------------------
    # LEVEL / BABAK
    # -----------------------------------------------------

    level_event = parse_level_u15(row)


    # -----------------------------------------------------
    # HASIL SKOR
    # -----------------------------------------------------

    hasil_skor = parse_skor_u15(row)


    # -----------------------------------------------------
    # SIMPAN
    # -----------------------------------------------------

    data_u15.append({

        "id_event":
            f"SOERATIN-U15-{i:03d}",

        "nama_event":
            "Piala Soeratin U-15",

        "jenis_olahraga":
            "Sepak Bola",

        "tanggal_mulai":
            tanggal,

        "tanggal_selesai":
            tanggal,

        "nama_venue":
            venue,

        "level_event":
            level_event,

        "peserta_tim":
            peserta_tim,

        "hasil_skor":
            hasil_skor,

        "sumber":
            url_u15
    })


# =========================================================
# 8. DATAFRAME
# =========================================================

kolom_event = [
    "id_event",
    "nama_event",
    "jenis_olahraga",
    "tanggal_mulai",
    "tanggal_selesai",
    "nama_venue",
    "level_event",
    "peserta_tim",
    "hasil_skor",
    "sumber"
]

df_u15 = pd.DataFrame(
    data_u15
)[kolom_event]


# =========================================================
# 9. HASIL
# =========================================================

print(
    "Ukuran data U-15:",
    df_u15.shape
)

display(
    df_u15.head()
)

U-15: ditemukan 144 baris pertandingan
Ukuran data U-15: (144, 10)

,id_event,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
0,SOERATIN-U15-001,Piala Soeratin U-15,Sepak Bola,2024-01-08,2024-01-08,Lapangan Pagu Kediri,Grup H,Bangkalan Soccer Academy VS Putra Soerapati,None,https://pssijatim.com/page-piala-soeratin-u-15
1,SOERATIN-U15-002,Piala Soeratin U-15,Sepak Bola,2024-01-08,2024-01-08,Lapangan Ngino Kediri,Grup C,Pesad Centre VS Bintang Putra,None,https://pssijatim.com/page-piala-soeratin-u-15
2,SOERATIN-U15-003,Piala Soeratin U-15,Sepak Bola,2024-01-08,2024-01-08,Lapangan Puhjarak Kediri,Grup G,SSB Porass VS Gempur,None,https://pssijatim.com/page-piala-soeratin-u-15
3,SOERATIN-U15-004,Piala Soeratin U-15,Sepak Bola,2024-01-08,2024-01-08,Lapangan Sitimerto Kediri,Grup E,Ansor Putra Mas VS Bima Putra Blitar,None,https://pssijatim.com/page-piala-soeratin-u-15
4,SOERATIN-U15-005,Piala Soeratin U-15,Sepak Bola,2024-01-08,2024-01-08,Lapangan Pagu Kediri,Grup H,Persela FA VS Tulungagung Putra,None,https://pssijatim.com/page-piala-soeratin-u-15

In [ ]:
# Ambil semua link dari pertandingan pertama U-15
row = rows_u15[0]

for a in row.find_all("a", href=True):
    print(
        "TEXT:",
        a.get_text(" ", strip=True),
        "| HREF:",
        a["href"]
    )

TEXT:  | HREF: https://www.pssijatim.com/team/bangkalan-soccer-academy
TEXT:  | HREF: https://www.pssijatim.com/team/putra-soerapati
TEXT: Senin, 8 Januari 2024 | HREF: https://www.pssijatim.com/match/bangkalan-soccer-academy-vs-putra-soerapati
TEXT: 16:00 WIB | HREF: https://www.pssijatim.com/match/bangkalan-soccer-academy-vs-putra-soerapati
TEXT: Bangkalan Soccer Academy VS Putra Soerapati | HREF: https://www.pssijatim.com/match/bangkalan-soccer-academy-vs-putra-soerapati

In [ ]:
# Cari semua link pertandingan yang ada di halaman U-15

match_links = []

for row in rows_u15:

    for a in row.find_all("a", href=True):

        href = a["href"]
        text = a.get_text(" ", strip=True)

        if "/match/" in href:

            match_links.append({
                "text": text,
                "url": href
            })


df_links = pd.DataFrame(match_links)

display(
    df_links.head(20)
)

,text,url
0,"Senin, 8 Januari 2024",https://www.pssijatim.com/match/bangkalan-soccer-academy-vs-putra-soerapati
1,16:00 WIB,https://www.pssijatim.com/match/bangkalan-soccer-academy-vs-putra-soerapati
2,Bangkalan Soccer Academy VS Putra Soerapati,https://www.pssijatim.com/match/bangkalan-soccer-academy-vs-putra-soerapati
3,"Senin, 8 Januari 2024",https://www.pssijatim.com/match/pesad-centre-vs-bintang-putra
4,15:30 WIB,https://www.pssijatim.com/match/pesad-centre-vs-bintang-putra
5,Pesad Centre VS Bintang Putra,https://www.pssijatim.com/match/pesad-centre-vs-bintang-putra
6,"Senin, 8 Januari 2024",https://www.pssijatim.com/match/ssb-porass-vs-gempur
7,15:30 WIB,https://www.pssijatim.com/match/ssb-porass-vs-gempur
8,SSB Porass VS Gempur,https://www.pssijatim.com/match/ssb-porass-vs-gempur
9,"Senin, 8 Januari 2024",https://www.pssijatim.com/match/ansor-putra-mas-vs-bima-putra-blitar
10,15:30 WIB,https://www.pssijatim.com/match/ansor-putra-mas-vs-bima-putra-blitar
11,Ansor Putra Mas VS Bima Putra Blitar,https://www.pssijatim.com/match/ansor-putra-mas-vs-bima-putra-blitar
12,"Senin, 8 Januari 2024",https://www.pssijatim.com/match/persela-fa-vs-tulungagung-putra
13,14:30 WIB,https://www.pssijatim.com/match/persela-fa-vs-tulungagung-putra
14,Persela FA VS Tulungagung Putra,https://www.pssijatim.com/match/persela-fa-vs-tulungagung-putra
15,"Senin, 8 Januari 2024",https://www.pssijatim.com/match/biting-putra-jaya-vs-pelindo
16,14:00 WIB,https://www.pssijatim.com/match/biting-putra-jaya-vs-pelindo
17,Biting Putra Jaya VS Pelindo,https://www.pssijatim.com/match/biting-putra-jaya-vs-pelindo
18,"Senin, 8 Januari 2024",https://www.pssijatim.com/match/young-star-vs-majapahit-soccer-academy
19,14:00 WIB,https://www.pssijatim.com/match/young-star-vs-majapahit-soccer-academy

In [ ]:
for row in rows_u15:

    for a in row.find_all("a", href=True):

        text = a.get_text(
            " ",
            strip=True
        )

        href = a["href"]

        if "/match/" in href:

            print(
                "TEXT :", repr(text)
            )

            print(
                "URL  :", href
            )

            print("-" * 80)

TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/bangkalan-soccer-academy-vs-putra-soerapati
--------------------------------------------------------------------------------
TEXT : '16:00 WIB'
URL  : https://www.pssijatim.com/match/bangkalan-soccer-academy-vs-putra-soerapati
--------------------------------------------------------------------------------
TEXT : 'Bangkalan Soccer Academy VS Putra Soerapati'
URL  : https://www.pssijatim.com/match/bangkalan-soccer-academy-vs-putra-soerapati
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/pesad-centre-vs-bintang-putra
--------------------------------------------------------------------------------
TEXT : '15:30 WIB'
URL  : https://www.pssijatim.com/match/pesad-centre-vs-bintang-putra
--------------------------------------------------------------------------------
TEXT : 'Pesad Centre VS Bintang Putra'
URL  : https://www.pssijatim.com/match/pesad-centre-vs-bintang-putra
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/ssb-porass-vs-gempur
--------------------------------------------------------------------------------
TEXT : '15:30 WIB'
URL  : https://www.pssijatim.com/match/ssb-porass-vs-gempur
--------------------------------------------------------------------------------
TEXT : 'SSB Porass VS Gempur'
URL  : https://www.pssijatim.com/match/ssb-porass-vs-gempur
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/ansor-putra-mas-vs-bima-putra-blitar
--------------------------------------------------------------------------------
TEXT : '15:30 WIB'
URL  : https://www.pssijatim.com/match/ansor-putra-mas-vs-bima-putra-blitar
--------------------------------------------------------------------------------
TEXT : 'Ansor Putra Mas VS Bima Putra Blitar'
URL  : https://www.pssijatim.com/match/ansor-putra-mas-vs-bima-putra-blitar
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/persela-fa-vs-tulungagung-putra
--------------------------------------------------------------------------------
TEXT : '14:30 WIB'
URL  : https://www.pssijatim.com/match/persela-fa-vs-tulungagung-putra
--------------------------------------------------------------------------------
TEXT : 'Persela FA VS Tulungagung Putra'
URL  : https://www.pssijatim.com/match/persela-fa-vs-tulungagung-putra
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/biting-putra-jaya-vs-pelindo
--------------------------------------------------------------------------------
TEXT : '14:00 WIB'
URL  : https://www.pssijatim.com/match/biting-putra-jaya-vs-pelindo
--------------------------------------------------------------------------------
TEXT : 'Biting Putra Jaya VS Pelindo'
URL  : https://www.pssijatim.com/match/biting-putra-jaya-vs-pelindo
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/young-star-vs-majapahit-soccer-academy
--------------------------------------------------------------------------------
TEXT : '14:00 WIB'
URL  : https://www.pssijatim.com/match/young-star-vs-majapahit-soccer-academy
--------------------------------------------------------------------------------
TEXT : 'Young Star VS Majapahit Soccer Academy'
URL  : https://www.pssijatim.com/match/young-star-vs-majapahit-soccer-academy
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/persedikab-vs-bhinneka-indonesia
--------------------------------------------------------------------------------
TEXT : '14:00 WIB'
URL  : https://www.pssijatim.com/match/persedikab-vs-bhinneka-indonesia
--------------------------------------------------------------------------------
TEXT : 'Persedikab VS Bhinneka Indonesia'
URL  : https://www.pssijatim.com/match/persedikab-vs-bhinneka-indonesia
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/al-fath-vs-ps-maron-jaya
--------------------------------------------------------------------------------
TEXT : '13:00 WIB'
URL  : https://www.pssijatim.com/match/al-fath-vs-ps-maron-jaya
--------------------------------------------------------------------------------
TEXT : 'Al-Fath VS PS Maron Jaya'
URL  : https://www.pssijatim.com/match/al-fath-vs-ps-maron-jaya
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/boca-junior-vs-indonesia-muda
--------------------------------------------------------------------------------
TEXT : '10:00 WIB'
URL  : https://www.pssijatim.com/match/boca-junior-vs-indonesia-muda
--------------------------------------------------------------------------------
TEXT : 'Boca Junior VS Indonesia Muda'
URL  : https://www.pssijatim.com/match/boca-junior-vs-indonesia-muda
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/naga-emas-asri-vs-mitratama-fc
--------------------------------------------------------------------------------
TEXT : '09:00 WIB'
URL  : https://www.pssijatim.com/match/naga-emas-asri-vs-mitratama-fc
--------------------------------------------------------------------------------
TEXT : 'Naga Emas Asri VS Mitratama FC'
URL  : https://www.pssijatim.com/match/naga-emas-asri-vs-mitratama-fc
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/football-class-vs-bimantara
--------------------------------------------------------------------------------
TEXT : '09:00 WIB'
URL  : https://www.pssijatim.com/match/football-class-vs-bimantara
--------------------------------------------------------------------------------
TEXT : 'Football Class VS Bimantara'
URL  : https://www.pssijatim.com/match/football-class-vs-bimantara
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/ssb-masel-vs-ssb-satria-perkasa
--------------------------------------------------------------------------------
TEXT : '09:00 WIB'
URL  : https://www.pssijatim.com/match/ssb-masel-vs-ssb-satria-perkasa
--------------------------------------------------------------------------------
TEXT : 'SSB Masel VS SSB Satria Perkasa'
URL  : https://www.pssijatim.com/match/ssb-masel-vs-ssb-satria-perkasa
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/ssb-esge-vs-ps-putra-jaya
--------------------------------------------------------------------------------
TEXT : '08:30 WIB'
URL  : https://www.pssijatim.com/match/ssb-esge-vs-ps-putra-jaya
--------------------------------------------------------------------------------
TEXT : 'SSB ESGE VS PS Putra Jaya'
URL  : https://www.pssijatim.com/match/ssb-esge-vs-ps-putra-jaya
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/persebaya-surabaya-vs-bina-putra-fc
--------------------------------------------------------------------------------
TEXT : '07:30 WIB'
URL  : https://www.pssijatim.com/match/persebaya-surabaya-vs-bina-putra-fc
--------------------------------------------------------------------------------
TEXT : 'Persebaya Surabaya VS Bina Putra FC'
URL  : https://www.pssijatim.com/match/persebaya-surabaya-vs-bina-putra-fc
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/putra-patria-vs-skb-gudo
--------------------------------------------------------------------------------
TEXT : '07:30 WIB'
URL  : https://www.pssijatim.com/match/putra-patria-vs-skb-gudo
--------------------------------------------------------------------------------
TEXT : 'Putra Patria VS SKB Gudo'
URL  : https://www.pssijatim.com/match/putra-patria-vs-skb-gudo
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/golden-soccer-academy-vs-ssb-petrokimia-putra
--------------------------------------------------------------------------------
TEXT : '07:30 WIB'
URL  : https://www.pssijatim.com/match/golden-soccer-academy-vs-ssb-petrokimia-putra
--------------------------------------------------------------------------------
TEXT : 'Golden Soccer Academy VS SSB Petrokimia Putra'
URL  : https://www.pssijatim.com/match/golden-soccer-academy-vs-ssb-petrokimia-putra
--------------------------------------------------------------------------------
TEXT : 'Senin, 8 Januari 2024'
URL  : https://www.pssijatim.com/match/ketapang-fc-vs-new-gesic
--------------------------------------------------------------------------------
TEXT : '07:00 WIB'
URL  : https://www.pssijatim.com/match/ketapang-fc-vs-new-gesic
--------------------------------------------------------------------------------
TEXT : 'Ketapang FC VS New Gesic'
URL  : https://www.pssijatim.com/match/ketapang-fc-vs-new-gesic
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/ps-putra-jaya-vs-new-gesic
--------------------------------------------------------------------------------
TEXT : '0 - 1'
URL  : https://www.pssijatim.com/match/ps-putra-jaya-vs-new-gesic
--------------------------------------------------------------------------------
TEXT : 'PS Putra Jaya VS New Gesic'
URL  : https://www.pssijatim.com/match/ps-putra-jaya-vs-new-gesic
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/mitratama-fc-vs-skb-gudo
--------------------------------------------------------------------------------
TEXT : '0 - 1'
URL  : https://www.pssijatim.com/match/mitratama-fc-vs-skb-gudo
--------------------------------------------------------------------------------
TEXT : 'Mitratama FC VS SKB Gudo'
URL  : https://www.pssijatim.com/match/mitratama-fc-vs-skb-gudo
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/ssb-satria-perkasa-vs-ssb-petrokimia-putra
--------------------------------------------------------------------------------
TEXT : '1 - 2'
URL  : https://www.pssijatim.com/match/ssb-satria-perkasa-vs-ssb-petrokimia-putra
--------------------------------------------------------------------------------
TEXT : 'SSB Satria Perkasa VS SSB Petrokimia Putra'
URL  : https://www.pssijatim.com/match/ssb-satria-perkasa-vs-ssb-petrokimia-putra
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/bimantara-vs-bina-putra-fc
--------------------------------------------------------------------------------
TEXT : '1 - 2'
URL  : https://www.pssijatim.com/match/bimantara-vs-bina-putra-fc
--------------------------------------------------------------------------------
TEXT : 'Bimantara VS Bina Putra FC'
URL  : https://www.pssijatim.com/match/bimantara-vs-bina-putra-fc
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/bangkalan-soccer-academy-vs-persela-fa
--------------------------------------------------------------------------------
TEXT : '0 - 4'
URL  : https://www.pssijatim.com/match/bangkalan-soccer-academy-vs-persela-fa
--------------------------------------------------------------------------------
TEXT : 'Bangkalan Soccer Academy VS Persela FA'
URL  : https://www.pssijatim.com/match/bangkalan-soccer-academy-vs-persela-fa
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/pesad-centre-vs-biting-putra-jaya
--------------------------------------------------------------------------------
TEXT : '0 - 3'
URL  : https://www.pssijatim.com/match/pesad-centre-vs-biting-putra-jaya
--------------------------------------------------------------------------------
TEXT : 'Pesad Centre VS Biting Putra Jaya'
URL  : https://www.pssijatim.com/match/pesad-centre-vs-biting-putra-jaya
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/ssb-porass-vs-persedikab
--------------------------------------------------------------------------------
TEXT : '3 - 3'
URL  : https://www.pssijatim.com/match/ssb-porass-vs-persedikab
--------------------------------------------------------------------------------
TEXT : 'SSB Porass VS Persedikab'
URL  : https://www.pssijatim.com/match/ssb-porass-vs-persedikab
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/ansor-putra-mas-vs-young-star
--------------------------------------------------------------------------------
TEXT : '2 - 3'
URL  : https://www.pssijatim.com/match/ansor-putra-mas-vs-young-star
--------------------------------------------------------------------------------
TEXT : 'Ansor Putra Mas VS Young Star'
URL  : https://www.pssijatim.com/match/ansor-putra-mas-vs-young-star
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/putra-soerapati-vs-tulungagung-putra
--------------------------------------------------------------------------------
TEXT : '3 - 2'
URL  : https://www.pssijatim.com/match/putra-soerapati-vs-tulungagung-putra
--------------------------------------------------------------------------------
TEXT : 'Putra Soerapati VS Tulungagung Putra'
URL  : https://www.pssijatim.com/match/putra-soerapati-vs-tulungagung-putra
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/al-fath-vs-boca-junior
--------------------------------------------------------------------------------
TEXT : '1 - 1'
URL  : https://www.pssijatim.com/match/al-fath-vs-boca-junior
--------------------------------------------------------------------------------
TEXT : 'Al-Fath VS Boca Junior'
URL  : https://www.pssijatim.com/match/al-fath-vs-boca-junior
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/bima-putra-blitar-vs-majapahit-soccer-academy
--------------------------------------------------------------------------------
TEXT : '3 - 1'
URL  : https://www.pssijatim.com/match/bima-putra-blitar-vs-majapahit-soccer-academy
--------------------------------------------------------------------------------
TEXT : 'Bima Putra Blitar VS Majapahit Soccer Academy'
URL  : https://www.pssijatim.com/match/bima-putra-blitar-vs-majapahit-soccer-academy
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/gempur-vs-bhinneka-indonesia
--------------------------------------------------------------------------------
TEXT : '1 - 2'
URL  : https://www.pssijatim.com/match/gempur-vs-bhinneka-indonesia
--------------------------------------------------------------------------------
TEXT : 'Gempur VS Bhinneka Indonesia'
URL  : https://www.pssijatim.com/match/gempur-vs-bhinneka-indonesia
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/bintang-putra-vs-pelindo
--------------------------------------------------------------------------------
TEXT : '1 - 2'
URL  : https://www.pssijatim.com/match/bintang-putra-vs-pelindo
--------------------------------------------------------------------------------
TEXT : 'Bintang Putra VS Pelindo'
URL  : https://www.pssijatim.com/match/bintang-putra-vs-pelindo
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/ps-maron-jaya-vs-indonesia-muda
--------------------------------------------------------------------------------
TEXT : '0 - 2'
URL  : https://www.pssijatim.com/match/ps-maron-jaya-vs-indonesia-muda
--------------------------------------------------------------------------------
TEXT : 'PS Maron Jaya VS Indonesia Muda'
URL  : https://www.pssijatim.com/match/ps-maron-jaya-vs-indonesia-muda
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/ssb-masel-vs-golden-soccer-academy
--------------------------------------------------------------------------------
TEXT : '0 - 2'
URL  : https://www.pssijatim.com/match/ssb-masel-vs-golden-soccer-academy
--------------------------------------------------------------------------------
TEXT : 'SSB Masel VS Golden Soccer Academy'
URL  : https://www.pssijatim.com/match/ssb-masel-vs-golden-soccer-academy
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/naga-emas-asri-vs-putra-patria
--------------------------------------------------------------------------------
TEXT : '0 - 1'
URL  : https://www.pssijatim.com/match/naga-emas-asri-vs-putra-patria
--------------------------------------------------------------------------------
TEXT : 'Naga Emas Asri VS Putra Patria'
URL  : https://www.pssijatim.com/match/naga-emas-asri-vs-putra-patria
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/football-class-vs-persebaya-surabaya
--------------------------------------------------------------------------------
TEXT : '2 - 5'
URL  : https://www.pssijatim.com/match/football-class-vs-persebaya-surabaya
--------------------------------------------------------------------------------
TEXT : 'Football Class VS Persebaya Surabaya'
URL  : https://www.pssijatim.com/match/football-class-vs-persebaya-surabaya
--------------------------------------------------------------------------------
TEXT : 'Minggu, 7 Januari 2024'
URL  : https://www.pssijatim.com/match/ssb-esge-vs-ketapang-fc
--------------------------------------------------------------------------------
TEXT : '1 - 0'
URL  : https://www.pssijatim.com/match/ssb-esge-vs-ketapang-fc
--------------------------------------------------------------------------------
TEXT : 'SSB ESGE VS Ketapang FC'
URL  : https://www.pssijatim.com/match/ssb-esge-vs-ketapang-fc
--------------------------------------------------------------------------------
TEXT : 'Sabtu, 6 Januari 2024'
URL  : https://www.pssijatim.com/match/new-gesic-vs-ssb-esge
--------------------------------------------------------------------------------
TEXT : '1 - 3'
URL  : https://www.pssijatim.com/match/new-gesic-vs-ssb-esge
--------------------------------------------------------------------------------
TEXT : 'New Gesic VS SSB ESGE'

In [ ]:
# Cek jumlah pertandingan yang memiliki skor

print(
    "Jumlah pertandingan dengan skor:",
    df_u15["hasil_skor"].notna().sum()
)

print(
    "Jumlah pertandingan tanpa skor:",
    df_u15["hasil_skor"].isna().sum()
)

Jumlah pertandingan dengan skor: 125
Jumlah pertandingan tanpa skor: 19

In [ ]:
# Tampilkan pertandingan yang memiliki skor

display(
    df_u15[
        df_u15["hasil_skor"].notna()
    ].head(20)
)

,id_event,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
18,SOERATIN-U15-019,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Pagu Kediri,Grup I,PS Putra Jaya VS New Gesic,0:1,https://pssijatim.com/page-piala-soeratin-u-15
19,SOERATIN-U15-020,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Puhjarak Kediri,Grup B,Mitratama FC VS SKB Gudo,0:1,https://pssijatim.com/page-piala-soeratin-u-15
20,SOERATIN-U15-021,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Sitimerto Kediri,Grup F,SSB Satria Perkasa VS SSB Petrokimia Putra,1:2,https://pssijatim.com/page-piala-soeratin-u-15
21,SOERATIN-U15-022,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Ngino Kediri,Grup D,Bimantara VS Bina Putra FC,1:2,https://pssijatim.com/page-piala-soeratin-u-15
22,SOERATIN-U15-023,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Pagu Kediri,Grup H,Bangkalan Soccer Academy VS Persela FA,0:4,https://pssijatim.com/page-piala-soeratin-u-15
23,SOERATIN-U15-024,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Ngino Kediri,Grup C,Pesad Centre VS Biting Putra Jaya,0:3,https://pssijatim.com/page-piala-soeratin-u-15
24,SOERATIN-U15-025,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Puhjarak Kediri,Grup G,SSB Porass VS Persedikab,3:3,https://pssijatim.com/page-piala-soeratin-u-15
25,SOERATIN-U15-026,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Sitimerto Kediri,Grup E,Ansor Putra Mas VS Young Star,2:3,https://pssijatim.com/page-piala-soeratin-u-15
26,SOERATIN-U15-027,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Pagu Kediri,Grup H,Putra Soerapati VS Tulungagung Putra,3:2,https://pssijatim.com/page-piala-soeratin-u-15
27,SOERATIN-U15-028,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Pagu Kediri,Grup A,Al-Fath VS Boca Junior,1:1,https://pssijatim.com/page-piala-soeratin-u-15
28,SOERATIN-U15-029,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Sitimerto Kediri,Grup E,Bima Putra Blitar VS Majapahit Soccer Academy,3:1,https://pssijatim.com/page-piala-soeratin-u-15
29,SOERATIN-U15-030,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Puhjarak Kediri,Grup G,Gempur VS Bhinneka Indonesia,1:2,https://pssijatim.com/page-piala-soeratin-u-15
30,SOERATIN-U15-031,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Ngino Kediri,Grup C,Bintang Putra VS Pelindo,1:2,https://pssijatim.com/page-piala-soeratin-u-15
31,SOERATIN-U15-032,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Pagu Kediri,Grup A,PS Maron Jaya VS Indonesia Muda,0:2,https://pssijatim.com/page-piala-soeratin-u-15
32,SOERATIN-U15-033,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Sitimerto Kediri,Grup F,SSB Masel VS Golden Soccer Academy,0:2,https://pssijatim.com/page-piala-soeratin-u-15
33,SOERATIN-U15-034,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Puhjarak Kediri,Grup B,Naga Emas Asri VS Putra Patria,0:1,https://pssijatim.com/page-piala-soeratin-u-15
34,SOERATIN-U15-035,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Ngino Kediri,Grup D,Football Class VS Persebaya Surabaya,2:5,https://pssijatim.com/page-piala-soeratin-u-15
35,SOERATIN-U15-036,Piala Soeratin U-15,Sepak Bola,2024-01-07,2024-01-07,Lapangan Pagu Kediri,Grup I,SSB ESGE VS Ketapang FC,1:0,https://pssijatim.com/page-piala-soeratin-u-15
36,SOERATIN-U15-037,Piala Soeratin U-15,Sepak Bola,2024-01-06,2024-01-06,Lapangan Pagu Kediri,Grup I,New Gesic VS SSB ESGE,1:3,https://pssijatim.com/page-piala-soeratin-u-15
37,SOERATIN-U15-038,Piala Soeratin U-15,Sepak Bola,2024-01-06,2024-01-06,Lapangan Ngino Kediri,Grup D,Bina Putra FC VS Football Class,0:1,https://pssijatim.com/page-piala-soeratin-u-15

In [ ]:
df_u15

,id_event,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
0,SOERATIN-U15-001,Piala Soeratin U-15,Sepak Bola,2024-01-08,2024-01-08,Lapangan Pagu Kediri,Grup H,Bangkalan Soccer Academy VS Putra Soerapati,None,https://pssijatim.com/page-piala-soeratin-u-15
1,SOERATIN-U15-002,Piala Soeratin U-15,Sepak Bola,2024-01-08,2024-01-08,Lapangan Ngino Kediri,Grup C,Pesad Centre VS Bintang Putra,None,https://pssijatim.com/page-piala-soeratin-u-15
2,SOERATIN-U15-003,Piala Soeratin U-15,Sepak Bola,2024-01-08,2024-01-08,Lapangan Puhjarak Kediri,Grup G,SSB Porass VS Gempur,None,https://pssijatim.com/page-piala-soeratin-u-15
3,SOERATIN-U15-004,Piala Soeratin U-15,Sepak Bola,2024-01-08,2024-01-08,Lapangan Sitimerto Kediri,Grup E,Ansor Putra Mas VS Bima Putra Blitar,None,https://pssijatim.com/page-piala-soeratin-u-15
4,SOERATIN-U15-005,Piala Soeratin U-15,Sepak Bola,2024-01-08,2024-01-08,Lapangan Pagu Kediri,Grup H,Persela FA VS Tulungagung Putra,None,https://pssijatim.com/page-piala-soeratin-u-15
...,...,...,...,...,...,...,...,...,...,...
139,SOERATIN-U15-140,Piala Soeratin U-15,Sepak Bola,2026-09-09,2026-09-09,"Lapangan Glagahwero, Jember",16 Besar,Arema FC VS Probolinggo F.A,1:0,https://pssijatim.com/page-piala-soeratin-u-15
140,SOERATIN-U15-141,Piala Soeratin U-15,Sepak Bola,2026-09-09,2026-09-09,"Lapangan BRIGIF IX, Jember",16 Besar,Sejati Football VS Arunda Malang,0:1,https://pssijatim.com/page-piala-soeratin-u-15
141,SOERATIN-U15-142,Piala Soeratin U-15,Sepak Bola,2026-09-09,2026-09-09,"Lapangan Glagahwero, Jember",16 Besar,Pordes FC Jember VS Taufiq Kasrun,1:1,https://pssijatim.com/page-piala-soeratin-u-15
142,SOERATIN-U15-143,Piala Soeratin U-15,Sepak Bola,2026-09-09,2026-09-09,"Lapangan BRIGIF IX, Jember",16 Besar,Al Rayyan Surabaya VS Bhineka FC Jember,2:0,https://pssijatim.com/page-piala-soeratin-u-15
143,SOERATIN-U15-144,Piala Soeratin U-15,Sepak Bola,2026-09-09,2026-09-09,"Lapangan Glagahwero, Jember",16 Besar,PGP Ponggok VS Gress One,1:1,https://pssijatim.com/page-piala-soeratin-u-15

In [ ]:
df_u13

,id_event,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
0,SOERATIN-U13-001,Piala Soeratin U-13,Sepak Bola,2024-01-08,2024-01-08,Lapangan Secaba Jember,Grup B,PS HW Babat VS Turangga FC,None,https://pssijatim.com/page-piala-soeratin-u-13
1,SOERATIN-U13-002,Piala Soeratin U-13,Sepak Bola,2024-01-08,2024-01-08,"Lapangan Yonif 509, Jember",Grup D,Bangkalan Soccer Academy VS Putra Manggala,None,https://pssijatim.com/page-piala-soeratin-u-13
2,SOERATIN-U13-003,Piala Soeratin U-13,Sepak Bola,2024-01-08,2024-01-08,"Lapangan Brigif Bawah, Jember",Grup H,Phoenix Mojokerto FC VS Argent Genteng,None,https://pssijatim.com/page-piala-soeratin-u-13
3,SOERATIN-U13-004,Piala Soeratin U-13,Sepak Bola,2024-01-08,2024-01-08,"Lapangan Brigif Atas, Jember",Grup F,Football Class VS Putra Jaya Blitar,None,https://pssijatim.com/page-piala-soeratin-u-13
4,SOERATIN-U13-005,Piala Soeratin U-13,Sepak Bola,2024-01-08,2024-01-08,Lapangan Secaba Jember,Grup C,Bima Putra Blitar VS Samudra FC,None,https://pssijatim.com/page-piala-soeratin-u-13
...,...,...,...,...,...,...,...,...,...,...
130,SOERATIN-U13-131,Piala Soeratin U-13,Sepak Bola,2026-09-09,2026-09-09,Stadion Notohadinegoro Jember,None,Pordes FC Jember VS Cahaya Muda,None,https://pssijatim.com/page-piala-soeratin-u-13
131,SOERATIN-U13-132,Piala Soeratin U-13,Sepak Bola,2026-09-09,2026-09-09,"Lapangan Jenggawah, Jember",None,Malang United VS Absa Pasuruan,None,https://pssijatim.com/page-piala-soeratin-u-13
132,SOERATIN-U13-133,Piala Soeratin U-13,Sepak Bola,2026-09-09,2026-09-09,Stadion Notohadinegoro Jember,None,Persida Sidoarjo VS Bima Putra Kota Blitar,None,https://pssijatim.com/page-piala-soeratin-u-13
133,SOERATIN-U13-134,Piala Soeratin U-13,Sepak Bola,2026-09-09,2026-09-09,"Lapangan Jenggawah, Jember",None,Balenos FC VS Benteng FC,None,https://pssijatim.com/page-piala-soeratin-u-13
134,SOERATIN-U13-135,Piala Soeratin U-13,Sepak Bola,2026-09-09,2026-09-09,Stadion Notohadinegoro Jember,None,Gresik United VS Tunas 92 Penetaban,None,https://pssijatim.com/page-piala-soeratin-u-13

### 6.8 Menggabungkan data Soeratin U-13 dan U-15

In [ ]:
df_soeratin = pd.concat(
    [df_u13, df_u15],
    ignore_index=True
)

print("Ukuran data gabungan:", df_soeratin.shape)
display(df_soeratin.head())
display(df_soeratin.tail())

Ukuran data gabungan: (279, 10)

,id_event,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
0,SOERATIN-U13-001,Piala Soeratin U-13,Sepak Bola,2024-01-08,2024-01-08,Lapangan Secaba Jember,Grup B,PS HW Babat VS Turangga FC,None,https://pssijatim.com/page-piala-soeratin-u-13
1,SOERATIN-U13-002,Piala Soeratin U-13,Sepak Bola,2024-01-08,2024-01-08,"Lapangan Yonif 509, Jember",Grup D,Bangkalan Soccer Academy VS Putra Manggala,None,https://pssijatim.com/page-piala-soeratin-u-13
2,SOERATIN-U13-003,Piala Soeratin U-13,Sepak Bola,2024-01-08,2024-01-08,"Lapangan Brigif Bawah, Jember",Grup H,Phoenix Mojokerto FC VS Argent Genteng,None,https://pssijatim.com/page-piala-soeratin-u-13
3,SOERATIN-U13-004,Piala Soeratin U-13,Sepak Bola,2024-01-08,2024-01-08,"Lapangan Brigif Atas, Jember",Grup F,Football Class VS Putra Jaya Blitar,None,https://pssijatim.com/page-piala-soeratin-u-13
4,SOERATIN-U13-005,Piala Soeratin U-13,Sepak Bola,2024-01-08,2024-01-08,Lapangan Secaba Jember,Grup C,Bima Putra Blitar VS Samudra FC,None,https://pssijatim.com/page-piala-soeratin-u-13

,id_event,nama_event,jenis_olahraga,tanggal_mulai,tanggal_selesai,nama_venue,level_event,peserta_tim,hasil_skor,sumber
274,SOERATIN-U15-140,Piala Soeratin U-15,Sepak Bola,2026-09-09,2026-09-09,"Lapangan Glagahwero, Jember",16 Besar,Arema FC VS Probolinggo F.A,1:0,https://pssijatim.com/page-piala-soeratin-u-15
275,SOERATIN-U15-141,Piala Soeratin U-15,Sepak Bola,2026-09-09,2026-09-09,"Lapangan BRIGIF IX, Jember",16 Besar,Sejati Football VS Arunda Malang,0:1,https://pssijatim.com/page-piala-soeratin-u-15
276,SOERATIN-U15-142,Piala Soeratin U-15,Sepak Bola,2026-09-09,2026-09-09,"Lapangan Glagahwero, Jember",16 Besar,Pordes FC Jember VS Taufiq Kasrun,1:1,https://pssijatim.com/page-piala-soeratin-u-15
277,SOERATIN-U15-143,Piala Soeratin U-15,Sepak Bola,2026-09-09,2026-09-09,"Lapangan BRIGIF IX, Jember",16 Besar,Al Rayyan Surabaya VS Bhineka FC Jember,2:0,https://pssijatim.com/page-piala-soeratin-u-15
278,SOERATIN-U15-144,Piala Soeratin U-15,Sepak Bola,2026-09-09,2026-09-09,"Lapangan Glagahwero, Jember",16 Besar,PGP Ponggok VS Gress One,1:1,https://pssijatim.com/page-piala-soeratin-u-15

# 7. Ekspor Tiga Dataset Final

In [ ]:
# Pastikan ketiga dataset tersedia sebelum disimpan
dataset_final = {
    "data_event_liga1": df_event_liga1,
    "data_event_aff": df_aff,
    "data_event_soeratin": df_soeratin
}

# Simpan masing-masing dataset sebagai CSV
for nama_file, dataframe in dataset_final.items():
    dataframe.to_csv(
        f"{nama_file}.csv",
        index=False,
        encoding="utf-8-sig"
    )
    print(f"{nama_file}.csv berhasil dibuat | Jumlah baris: {len(dataframe)}")

# Unduh ketiga file jika notebook dijalankan di Google Colab
from google.colab import files

for nama_file in dataset_final:
    files.download(f"{nama_file}.csv")